/**
 * park-scene.ts
 * -------------
 * A colorful, Disney-style **amusement park** built in pure three.js, used as
 * the homepage hero background (see `components/layout/hero-three-park.tsx`).
 *
 * The park is laid out as recognizable themed "lands" radiating from a central
 * plaza hub, each with its own ground color, buildings and headline ride:
 *  - **Fantasyland** (back): the fairytale castle, carousel, teacups.
 *  - **Tomorrowland** (right): metallic domes, a rocket ride, the big wheel.
 *  - **Adventureland** (left): a lake, tiki huts and dense palms.
 *  - **Frontierland** (front-right): a western town under the wooden coaster.
 *  - **Main Street** (front): the striped entrance arch and food stalls.
 *
 * The drone-style camera flies a closed loop that swoops in over Main Street
 * and **through the castle gate**, then arcs around the whole park for an
 * overview. Fireworks burst over the castle (vivid at night).
 *
 * Texturing is hybrid: photographic **CC0 PBR maps** (ambientCG, public domain;
 * generated by `scripts/fetch-hero-textures.mjs` into `public/textures/hero/`)
 * for the big surfaces — grass, paving, stone, wood — plus procedural canvas
 * textures for accents (sky, stripes, water ripples).
 *
 * Rendering is deliberately simple and robust for a decorative web background:
 * direct rendering (no post-processing), moderate lighting, low metalness, and
 * **emissive glow** for the night "lights-on" look instead of bloom — so it
 * stays bright and legible on any GPU. Honors `prefers-reduced-motion` with a
 * single static frame. `dispose()` frees all GPU resources + listeners.
 *
 * Imported only by a `ssr:false` dynamic component, so three.js is code-split
 * into its own chunk and never touches SSR or the hero's LCP.
 */

import * as THREE from 'three';

export type SceneTheme = 'light' | 'dark';

export interface ParkSceneHandle {
  resize: (width: number, height: number) => void;
  setTheme: (theme: SceneTheme) => void;
  dispose: () => void;
}

interface CreateOptions {
  theme: SceneTheme;
  /** When true: build the scene, render ONE frame, never start the loop. */
  reducedMotion: boolean;
  /** Called once the scene is built and its textures have loaded (for a loader). */
  onReady?: () => void;
}

interface Animated {
  group: THREE.Object3D;
  update: (elapsed: number, delta: number) => void;
}

// ---------------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------------

const DAY = {
  skyTop: '#5fb4f0',
  skyBottom: '#dff0ff',
  fog: '#dceffb',
  fogNear: 70,
  fogFar: 200,
  hemiSky: 0xcfeaff,
  hemiGround: 0x9bbd84,
  hemiIntensity: 1.15,
  sun: 0xfff3d8,
  sunIntensity: 2.1,
  ambient: 0xffffff,
  ambientIntensity: 0.12,
  // A constant glow on emissive surfaces (lights, fountains, the marker, ride
  // accents) so the park reads bright and lively. The scene is theme-independent
  // — it always renders this daytime look regardless of the site's dark mode.
  emissive: 0.45,
  water: 0x3aa6d8,
  lampIntensity: 0,
};

type Palette = typeof DAY;

const C = {
  stoneLight: 0xfff0e6,
  stoneBlue: 0xdfe9ff,
  roofPink: 0xff7eb6,
  roofBlue: 0x4cc4ff,
  roofPurple: 0xb57bff,
  roofTeal: 0x33d6c0,
  gold: 0xffd166,
  flagRed: 0xff5d6c,
  flagYellow: 0xffd166,
  flagBlue: 0x5db8ff,
  coaster: 0xff4d8d,
  coasterSupport: 0xffc93c,
  leaf: 0x4fbf5f,
  leafDark: 0x3a9e4c,
} as const;

// Zone ground tints (kept separate so they're easy to read/tweak).
const ZONE = {
  fantasy: 0xe9d6ff,
  tomorrow: 0xcfe0f5,
  adventure: 0x8fbf6a,
  frontier: 0xe7c9a0,
  mainstreet: 0xf2dcc0,
};

const RIDE_COLORS = [0xff5d6c, 0xffd166, 0x5db8ff, 0x8be04e, 0xb57bff, 0xff9f43];
const FLOWER_COLORS = [0xff5d6c, 0xffd166, 0xff7eb6, 0xb57bff, 0xff9f43, 0xffffff];
const VISITOR_COLORS = [0xff5d6c, 0x5db8ff, 0x8be04e, 0xffd166, 0xb57bff, 0xff7eb6, 0xff9f43];
const FIREWORK_COLORS = [0xff5d6c, 0xffd166, 0x5db8ff, 0x8be04e, 0xb57bff, 0xff7eb6, 0xffffff];

// ---------------------------------------------------------------------------
// Procedural texture helpers
// ---------------------------------------------------------------------------

function makeSkyTexture(top: string, bottom: string): THREE.CanvasTexture {
  const canvas = document.createElement('canvas');
  canvas.width = 2;
  canvas.height = 256;
  const ctx = canvas.getContext('2d')!;
  const grad = ctx.createLinearGradient(0, 0, 0, 256);
  grad.addColorStop(0, top);
  grad.addColorStop(1, bottom);
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, 2, 256);
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}

function makeStripeTexture(colorA: string, colorB: string): THREE.CanvasTexture {
  const canvas = document.createElement('canvas');
  canvas.width = 128;
  canvas.height = 16;
  const ctx = canvas.getContext('2d')!;
  const stripes = 8;
  const w = canvas.width / stripes;
  for (let i = 0; i < stripes; i++) {
    ctx.fillStyle = i % 2 === 0 ? colorA : colorB;
    ctx.fillRect(i * w, 0, w + 1, canvas.height);
    const g = ctx.createLinearGradient(i * w, 0, (i + 1) * w, 0);
    g.addColorStop(0, 'rgba(0,0,0,0.16)');
    g.addColorStop(0.5, 'rgba(255,255,255,0.12)');
    g.addColorStop(1, 'rgba(0,0,0,0.16)');
    ctx.fillStyle = g;
    ctx.fillRect(i * w, 0, w + 1, canvas.height);
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  return tex;
}

/**
 * A tileable RollerCoaster-Tycoon-style paved path: a grid of slabs with grout
 * lines and slight per-slab tonal variation + speckle. Reads as classic park
 * pavement at any distance.
 */
function makePathTexture(): THREE.CanvasTexture {
  const size = 256;
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  ctx.fillStyle = '#766a5b'; // grout
  ctx.fillRect(0, 0, size, size);
  const n = 4;
  const w = size / n;
  const gap = 3;
  const bases = ['#cdbfa6', '#c5b699', '#d4c7af', '#bfb091'];
  for (let gy = 0; gy < n; gy++) {
    for (let gx = 0; gx < n; gx++) {
      ctx.fillStyle = bases[(gx + gy * 2) % bases.length];
      ctx.fillRect(gx * w + gap, gy * w + gap, w - gap * 2, w - gap * 2);
      ctx.fillStyle = 'rgba(0,0,0,0.05)';
      for (let s = 0; s < 7; s++) {
        ctx.fillRect(
          gx * w + gap + Math.random() * (w - 2 * gap),
          gy * w + gap + Math.random() * (w - 2 * gap),
          2,
          2
        );
      }
    }
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  return tex;
}

/** A tileable ripple normal map for the lake, built from summed sine waves. */
function makeWaterNormal(): THREE.CanvasTexture {
  const size = 256;
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const img = ctx.createImageData(size, size);
  const TAU = Math.PI * 2;
  const height = (x: number, y: number) => {
    const u = (x / size) * TAU;
    const v = (y / size) * TAU;
    return Math.sin(u * 3 + v) * 0.5 + Math.sin(v * 4 - u * 2) * 0.3 + Math.sin((u + v) * 2) * 0.2;
  };
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const hx = height((x + 1) % size, y) - height((x - 1 + size) % size, y);
      const hy = height(x, (y + 1) % size) - height(x, (y - 1 + size) % size);
      const nx = -hx * 0.5;
      const ny = -hy * 0.5;
      const len = Math.hypot(nx, ny, 1);
      const idx = (y * size + x) * 4;
      img.data[idx] = ((nx / len) * 0.5 + 0.5) * 255;
      img.data[idx + 1] = ((ny / len) * 0.5 + 0.5) * 255;
      img.data[idx + 2] = (1 / len) * 0.5 * 255 + 128;
      img.data[idx + 3] = 255;
    }
  }
  ctx.putImageData(img, 0, 0);
  const tex = new THREE.CanvasTexture(canvas);
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  return tex;
}

/** Vertical streaks for a scrolling waterfall sheet. */
function makeWaterfallTexture(): THREE.CanvasTexture {
  const w = 32;
  const h = 128;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;
  ctx.fillStyle = '#cfeefe';
  ctx.fillRect(0, 0, w, h);
  for (let x = 0; x < w; x++) {
    const shade = 200 + Math.floor(Math.random() * 55);
    ctx.fillStyle = `rgb(${shade},${shade + 5},255)`;
    ctx.fillRect(x, 0, 1, h);
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  return tex;
}

// ---------------------------------------------------------------------------
// Resource tracking
// ---------------------------------------------------------------------------

class Tracker {
  readonly geometries = new Set<THREE.BufferGeometry>();
  readonly materials = new Set<THREE.Material>();
  readonly textures = new Set<THREE.Texture>();

  geo<T extends THREE.BufferGeometry>(g: T): T {
    this.geometries.add(g);
    return g;
  }
  mat<T extends THREE.Material>(m: T): T {
    this.materials.add(m);
    return m;
  }
  tex<T extends THREE.Texture>(t: T): T {
    this.textures.add(t);
    return t;
  }
  disposeAll() {
    this.geometries.forEach((g) => g.dispose());
    this.materials.forEach((m) => m.dispose());
    this.textures.forEach((t) => t.dispose());
    this.geometries.clear();
    this.materials.clear();
    this.textures.clear();
  }
}

type MatFactory = (params: THREE.MeshStandardMaterialParameters) => THREE.MeshStandardMaterial;
type LitFactory = (
  params: THREE.MeshStandardMaterialParameters,
  glow?: number
) => THREE.MeshStandardMaterial;

interface PbrMaps {
  map: THREE.Texture;
  normalMap: THREE.Texture;
  roughnessMap: THREE.Texture;
}

interface BuildCtx {
  track: Tracker;
  plain: MatFactory;
  lit: LitFactory;
  pbr: Record<'grass' | 'paving' | 'stone' | 'wood', PbrMaps>;
  lampLights: THREE.PointLight[];
  registerWater: (m: THREE.MeshStandardMaterial) => void;
  /** Load a single sRGB image texture (e.g. the park.fan logo). */
  loadImage: (url: string) => THREE.Texture;
  /** Max anisotropy of the renderer (for crisp ground textures at grazing angles). */
  maxAniso: number;
}

// ---------------------------------------------------------------------------
// Scene factory
// ---------------------------------------------------------------------------

export function createParkScene(canvas: HTMLCanvasElement, opts: CreateOptions): ParkSceneHandle {
  const track = new Tracker();
  const palette: Palette = DAY; // theme-independent: always the bright daytime look

  const renderer = new THREE.WebGLRenderer({
    canvas,
    antialias: true,
    alpha: false,
    powerPreference: 'high-performance',
  });
  const initialW = canvas.clientWidth || 1280;
  const initialH = canvas.clientHeight || 600;
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const maxAniso = renderer.capabilities.getMaxAnisotropy();
  renderer.setPixelRatio(dpr);
  renderer.setSize(initialW, initialH, false);
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.0;

  const scene = new THREE.Scene();
  const skyTex = track.tex(makeSkyTexture(palette.skyTop, palette.skyBottom));
  scene.background = skyTex;
  scene.fog = new THREE.Fog(palette.fog, palette.fogNear, palette.fogFar);

  const camera = new THREE.PerspectiveCamera(52, initialW / initialH, 0.1, 500);
  camera.position.set(0, 6, 30);

  // -- Flying camera (cinematic): glide in low over Main Street, dead-straight
  // THROUGH the freestanding gate, THROUGH the castle's archway tunnel, and out
  // into the hidden courtyard garden behind it — then rise and arc wide around
  // the whole park past the mountains. Points 1–6 stay on x=0 so the whole
  // gate→tunnel→reveal run is a straight line. The look target reads a little
  // further along the same path, so the camera always faces where it's going.
  const flightPath = new THREE.CatmullRomCurve3(
    [
      new THREE.Vector3(0, 13, 42), // approach overview
      new THREE.Vector3(0, 6.5, 14), // descend toward the gate
      new THREE.Vector3(0, 4.5, -13), // brief dramatic dip THROUGH the gate
      new THREE.Vector3(0, 4.6, -30), // through the castle archway tunnel (x=0)
      new THREE.Vector3(0, 8, -44), // emerge into the courtyard, climbing
      new THREE.Vector3(0, 18, -56), // frame the finale lake + the mountain marker
      new THREE.Vector3(-36, 19, -46), // …then a closer overview orbit so the park,
      new THREE.Vector3(-52, 16, -4), //   its attractions and the wide castle stay
      new THREE.Vector3(-38, 14, 42), //   present and full in frame (not distant)
      new THREE.Vector3(0, 16, 54),
      new THREE.Vector3(38, 14, 42),
      new THREE.Vector3(52, 16, -4),
      new THREE.Vector3(36, 19, -46),
    ],
    true,
    'catmullrom',
    0.5
  );
  const LAP_SECONDS = 96; // slow, stately flight
  const LOOK_AHEAD = 0.016;
  const camPos = new THREE.Vector3();
  const camTarget = new THREE.Vector3();

  // -- Lights (no IBL; moderate so nothing washes out) --------------------
  const hemi = new THREE.HemisphereLight(
    palette.hemiSky,
    palette.hemiGround,
    palette.hemiIntensity
  );
  scene.add(hemi);
  const ambient = new THREE.AmbientLight(palette.ambient, palette.ambientIntensity);
  scene.add(ambient);
  const sun = new THREE.DirectionalLight(palette.sun, palette.sunIntensity);
  sun.position.set(-34, 48, 28);
  sun.castShadow = true;
  const shadowSize = initialW < 768 ? 1024 : 2048;
  sun.shadow.mapSize.set(shadowSize, shadowSize);
  sun.shadow.camera.near = 1;
  sun.shadow.camera.far = 160;
  sun.shadow.camera.left = -64;
  sun.shadow.camera.right = 64;
  sun.shadow.camera.top = 64;
  sun.shadow.camera.bottom = -54;
  sun.shadow.bias = -0.0004;
  sun.shadow.normalBias = 0.02;
  scene.add(sun);

  // -- Material factories. flatShading gives the faceted, toy-like "toon" look
  // the park is going for (stylized & playful), and a constant emissive glow
  // keeps lights/accents lively. Callers can still override flatShading.
  const emissiveMats: THREE.MeshStandardMaterial[] = [];
  const plainMaterial: MatFactory = (params) =>
    track.mat(new THREE.MeshStandardMaterial({ flatShading: true, ...params }));
  const litMaterial: LitFactory = (params, glow = 0.9) => {
    const m = track.mat(new THREE.MeshStandardMaterial({ flatShading: true, ...params }));
    m.emissive = new THREE.Color((params.color as THREE.ColorRepresentation) ?? 0xffffff);
    m.userData.glow = glow;
    m.emissiveIntensity = palette.emissive * glow;
    emissiveMats.push(m);
    return m;
  };

  // -- Textures (async; the scene renders immediately, onReady fires on load) --
  const manager = new THREE.LoadingManager();
  let readyFired = false;
  const fireReady = () => {
    if (readyFired) return;
    readyFired = true;
    opts.onReady?.();
  };
  manager.onLoad = fireReady;
  const texLoader = new THREE.TextureLoader(manager);
  const loadTex = (url: string, srgb: boolean, repeat: number) => {
    const t = texLoader.load(url);
    t.wrapS = t.wrapT = THREE.RepeatWrapping;
    t.repeat.set(repeat, repeat);
    t.anisotropy = maxAniso;
    t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    return track.tex(t);
  };
  const loadPbr = (name: string, repeat: number): PbrMaps => ({
    map: loadTex(`/textures/hero/${name}/color.webp`, true, repeat),
    normalMap: loadTex(`/textures/hero/${name}/normal.webp`, false, repeat),
    roughnessMap: loadTex(`/textures/hero/${name}/roughness.webp`, false, repeat),
  });
  const pbr: BuildCtx['pbr'] = {
    grass: loadPbr('grass', 30),
    paving: loadPbr('paving', 9),
    stone: loadPbr('stone', 3),
    wood: loadPbr('wood', 2),
  };
  const loadImage = (url: string) => {
    const t = texLoader.load(url);
    t.colorSpace = THREE.SRGBColorSpace;
    t.anisotropy = maxAniso;
    return track.tex(t);
  };

  // -- Build the world ----------------------------------------------------
  const lampLights: THREE.PointLight[] = [];
  const waterMats: THREE.MeshStandardMaterial[] = [];
  const ctx: BuildCtx = {
    track,
    plain: plainMaterial,
    lit: litMaterial,
    pbr,
    lampLights,
    registerWater: (m) => waterMats.push(m),
    loadImage,
    maxAniso,
  };

  const animated: Animated[] = [];
  const root = new THREE.Group();
  scene.add(root);

  root.add(buildGround(ctx));
  root.add(buildMountains(ctx)); // distant horizon backdrop for depth + scale

  // Fantasyland (back center) — the camera flies through the freestanding gate,
  // through the castle's archway tunnel, and into the hidden courtyard behind.
  const castle = buildCastle(ctx);
  castle.position.set(0, 0, -30);
  root.add(castle);
  root.add(buildCastleGate(ctx)); // freestanding flythrough arch at z≈-13
  root.add(buildCastleGarden(ctx)); // hidden courtyard garden right behind the castle

  // The bombastic reveal further back: a great lake with a dancing fountain
  // show, a waterfall mountain, and a giant glowing park.fan marker.
  const finale = buildGrandFinale(ctx);
  root.add(finale.group);
  animated.push(finale);

  // A whole second park sprawls BEHIND the castle, around the lake: a second
  // Ferris wheel, a drop-tower "Startflyer", an observation tower, a second
  // coaster (a different, bluer style), and rows of food/shop stalls.
  const backFerris = buildFerrisWheel(ctx);
  backFerris.group.position.set(-34, 0, -60);
  backFerris.group.rotation.y = 0.5;
  root.add(backFerris.group);
  animated.push(backFerris);

  const dropTower = buildDropTower(ctx);
  dropTower.group.position.set(34, 0, -58);
  root.add(dropTower.group);
  animated.push(dropTower);

  const obsTower = buildObservationTower(ctx);
  obsTower.group.position.set(-40, 0, -80);
  root.add(obsTower.group);
  animated.push(obsTower);

  // Second coaster — a compact, swooping steel circuit in a different (teal) style.
  const coaster2 = buildCoaster(ctx, {
    color: 0x33d6c0,
    speed: 0.07,
    pts: [
      new THREE.Vector3(20, 1, -52),
      new THREE.Vector3(34, 2, -62),
      new THREE.Vector3(40, 10, -74),
      new THREE.Vector3(30, 15, -84),
      new THREE.Vector3(14, 11, -82),
      new THREE.Vector3(10, 5, -70),
      new THREE.Vector3(18, 3, -60),
    ],
  });
  root.add(coaster2.group);
  animated.push(coaster2);

  // Rows of stalls around the back park (RCT-style abundance of stands).
  const backStalls: Array<[number, number, number, number]> = [
    [-14, -50, 0.2, 0xff5d6c],
    [-6, -50, -0.2, 0x5db8ff],
    [6, -50, 0.2, 0x8be04e],
    [14, -50, -0.2, 0xffd166],
    [-20, -54, 0.6, 0xff9f43],
    [20, -54, -0.6, 0xb57bff],
    [-24, -70, 0.8, 0x5db8ff],
    [24, -70, -0.8, 0xff5d6c],
  ];
  for (const [x, z, r, color] of backStalls) {
    const stall = buildStall(ctx, color);
    stall.position.set(x, 0, z);
    stall.rotation.y = r;
    root.add(stall);
  }

  const carousel = buildCarousel(ctx);
  carousel.group.position.set(-11, 0, -19);
  root.add(carousel.group);
  animated.push(carousel);

  const teacups = buildTeacups(ctx);
  teacups.group.position.set(11, 0, -19);
  root.add(teacups.group);
  animated.push(teacups);

  // Tomorrowland (right)
  const ferris = buildFerrisWheel(ctx);
  ferris.group.position.set(27, 0, -12);
  root.add(ferris.group);
  animated.push(ferris);

  const rocket = buildRocketRide(ctx);
  rocket.group.position.set(22, 0, 7);
  root.add(rocket.group);
  animated.push(rocket);

  buildDomes(ctx).forEach((d, i) => {
    d.position.set(32 + (i % 2) * 4, 0, -2 + i * 6);
    root.add(d);
  });

  // Adventureland (left): lake + tiki huts + palms
  const lake = buildLake(ctx);
  lake.group.position.set(-26, 0, 6);
  root.add(lake.group);
  animated.push(lake);

  const tikiSpots: Array<[number, number, number]> = [
    [-30, -7, 0.4],
    [-21, 13, -0.5],
    [-34, 4, 0.2],
  ];
  for (const [x, z, r] of tikiSpots) {
    const hut = buildTikiHut(ctx);
    hut.position.set(x, 0, z);
    hut.rotation.y = r;
    root.add(hut);
  }

  // Frontierland (front-right): western town
  const westernSpots: Array<[number, number, number, number]> = [
    [17, 19, 0.2, 0xc25b4a],
    [23, 14, -0.5, 0x9c6b3f],
    [13, 13, 0.5, 0xb98a52],
  ];
  for (const [x, z, r, color] of westernSpots) {
    const b = buildWesternBuilding(ctx, color);
    b.position.set(x, 0, z);
    b.rotation.y = r;
    root.add(b);
  }

  // Swing ride near the hub
  const swing = buildSwingRide(ctx);
  swing.group.position.set(-15, 0, -4);
  root.add(swing.group);
  animated.push(swing);

  // The coaster encircles the whole park (Frontierland-style wooden supports).
  const coaster = buildCoaster(ctx);
  root.add(coaster.group);
  animated.push(coaster);

  // Main Street (front): entrance arch + stalls + tents
  root.add(buildEntranceGate(ctx));
  // Plenty of stalls lining the main avenue + plaza edges (RCT-style abundance).
  const stallSpots: Array<[number, number, number, number]> = [
    [-6, 14, 0.3, 0xff5d6c],
    [6, 14, -0.3, 0x5db8ff],
    [-12, 20, 0.5, 0x8be04e],
    [12, 20, -0.5, 0xffd166],
    [-9, 26, 0.3, 0xff9f43],
    [9, 26, -0.3, 0xb57bff],
    [-16, 30, 0.6, 0x5db8ff],
    [16, 30, -0.6, 0xff5d6c],
    [-14, 9, 1.4, 0xffd166],
    [14, 9, -1.4, 0x8be04e],
    [-18, 15, 0.9, 0xb57bff],
    [18, 15, -0.9, 0xff9f43],
  ];
  for (const [x, z, r, color] of stallSpots) {
    const stall = buildStall(ctx, color);
    stall.position.set(x, 0, z);
    stall.rotation.y = r;
    root.add(stall);
  }
  const tentSpots: Array<[number, number, string, string]> = [
    [-9, 8, '#ff5d6c', '#fff3f7'],
    [9, 8, '#5db8ff', '#fff3f7'],
  ];
  for (const [x, z, a, b] of tentSpots) {
    const tent = buildTent(ctx, a, b);
    tent.position.set(x, 0, z);
    root.add(tent);
  }

  // Lanterns along the central paths (alternate ones cast a night point-light).
  const lanternSpots: Array<[number, number]> = [
    [3.5, 9],
    [-3.5, 9],
    [7, 3],
    [-7, 3],
    [4, -5],
    [-4, -5],
    [11, 1],
    [-11, 1],
  ];
  lanternSpots.forEach(([x, z], i) => root.add(buildLantern(ctx, x, z, i % 2 === 0)));

  // Trees framing the park + filling the empty stretches (front avenue, edges,
  // and all around the finale behind the castle) so no area reads as bare.
  const treeSpots: Array<[number, number]> = [
    // outer ring / edges
    [-40, 14],
    [-44, -18],
    [40, 16],
    [45, -4],
    [44, -24],
    [-46, -4],
    // front avenue (Main Street) — denser
    [-18, 24],
    [8, 24],
    [20, 26],
    [-26, 26],
    [-14, 30],
    [14, 30],
    [-22, 33],
    [22, 33],
    [-9, 27],
    [9, 27],
    // mid-park fill
    [34, 22],
    [-36, 22],
    [30, 4],
    [-31, -3],
    [33, -16],
    [-33, -14],
    // around the finale behind the castle (z further negative)
    [-22, -50],
    [22, -50],
    [-30, -60],
    [30, -60],
    [-16, -64],
    [16, -64],
    [-34, -44],
    [34, -44],
    [-12, -74],
    [12, -74],
  ];
  for (const [x, z] of treeSpots) {
    const tree = buildTree(ctx);
    tree.scale.setScalar(0.9 + ((x * 7 + z * 13) % 5) / 8);
    tree.position.set(x, 0, z);
    tree.rotation.y = (x + z) % 6;
    root.add(tree);
  }

  root.add(buildFences(ctx));
  root.add(buildFlowerBeds(ctx));
  root.add(buildStreetProps(ctx)); // RCT details: benches, bins, signs, bushes
  root.add(buildBunting(ctx)); // colorful pennant strings over the plaza

  const visitors = buildVisitors(ctx);
  root.add(visitors.group);
  animated.push(visitors);

  const clouds = buildClouds(ctx);
  root.add(clouds.group);
  animated.push(clouds);

  // Fireworks burst OVER THE CASTLE only.
  const fireworks = buildFireworks(ctx, new THREE.Vector3(0, 22, -30));
  root.add(fireworks.group);
  animated.push(fireworks);

  const stars = buildStars(track);
  scene.add(stars);

  // -- Theme application --------------------------------------------------
  // One-time look setup (theme-independent — always the bright daytime look).
  // Sky / fog / lights are already configured from DAY at init; here we apply the
  // constant glow to the emissive surfaces built above and tint the lake water.
  for (const m of emissiveMats) m.emissiveIntensity = palette.emissive * (m.userData.glow ?? 0.9);
  for (const w of waterMats) w.color.set(palette.water);
  for (const l of lampLights) l.intensity = palette.lampIntensity;
  stars.visible = false;

  // -- Render loop --------------------------------------------------------
  const clock = new THREE.Clock();
  let frameId = 0;
  let running = false;

  const renderFrame = (elapsed: number, delta: number) => {
    for (const a of animated) a.update(elapsed, delta);
    const t = (elapsed / LAP_SECONDS) % 1;
    flightPath.getPointAt(t, camPos);
    flightPath.getPointAt((t + LOOK_AHEAD) % 1, camTarget);
    camera.position.copy(camPos);
    camera.lookAt(camTarget);
    renderer.render(scene, camera);
  };

  const loop = () => {
    if (!running) return;
    frameId = requestAnimationFrame(loop);
    const delta = Math.min(clock.getDelta(), 0.05);
    renderFrame(clock.elapsedTime, delta);
  };
  const start = () => {
    if (running) return;
    running = true;
    clock.start();
    loop();
  };
  const stop = () => {
    running = false;
    if (frameId) cancelAnimationFrame(frameId);
    frameId = 0;
  };

  const onVisibility = () => {
    if (document.hidden) stop();
    else if (!opts.reducedMotion) start();
  };
  document.addEventListener('visibilitychange', onVisibility);

  if (opts.reducedMotion) {
    renderFrame(0, 0);
    fireReady();
  } else {
    start();
  }

  return {
    resize(width, height) {
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(width, height, false);
      if (opts.reducedMotion) renderFrame(clock.elapsedTime, 0);
    },
    setTheme() {
      // The park is intentionally theme-independent (always the bright daytime
      // look), so nothing changes when the site toggles light/dark.
    },
    dispose() {
      stop();
      document.removeEventListener('visibilitychange', onVisibility);
      scene.traverse((o) => {
        const im = o as THREE.InstancedMesh;
        if (im.isInstancedMesh) im.dispose();
      });
      track.disposeAll();
      renderer.dispose();
    },
  };
}

// ---------------------------------------------------------------------------
// Ground + themed zones
// ---------------------------------------------------------------------------

function buildGround({ track, plain, pbr, maxAniso }: BuildCtx): THREE.Group {
  const group = new THREE.Group();

  const grassMat = plain({ ...pbr.grass, roughness: 1, metalness: 0 });
  const ground = new THREE.Mesh(track.geo(new THREE.CircleGeometry(150, 72)), grassMat);
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  group.add(ground);

  // Soft colored discs mark each themed land (sit just above the grass).
  const zoneDisc = (x: number, z: number, r: number, color: number) => {
    const m = new THREE.Mesh(
      track.geo(new THREE.CircleGeometry(r, 40)),
      plain({ color, roughness: 1, metalness: 0, transparent: true, opacity: 0.5 })
    );
    m.rotation.x = -Math.PI / 2;
    m.position.set(x, 0.015, z);
    m.receiveShadow = true;
    group.add(m);
  };
  zoneDisc(0, -26, 18, ZONE.fantasy); // Fantasyland
  zoneDisc(28, -4, 16, ZONE.tomorrow); // Tomorrowland
  zoneDisc(-27, 5, 15, ZONE.adventure); // Adventureland
  zoneDisc(18, 16, 13, ZONE.frontier); // Frontierland
  zoneDisc(0, 16, 12, ZONE.mainstreet); // Main Street

  // Paved plaza hub + radiating paths — RCT-style slab pavement (procedural).
  const plazaTex = track.tex(makePathTexture());
  plazaTex.anisotropy = maxAniso;
  plazaTex.repeat.set(6, 6);
  const plazaMat = plain({ map: plazaTex, roughness: 0.95, metalness: 0 });
  const plaza = new THREE.Mesh(track.geo(new THREE.CircleGeometry(11, 56)), plazaMat);
  plaza.rotation.x = -Math.PI / 2;
  plaza.position.y = 0.03;
  plaza.receiveShadow = true;
  group.add(plaza);

  // Separate texture instance so the long radiating paths keep square slabs.
  const pathTex = track.tex(makePathTexture());
  pathTex.anisotropy = maxAniso;
  pathTex.repeat.set(1.4, 20);
  const pathMat = plain({ map: pathTex, roughness: 0.95, metalness: 0 });
  const pathGeo = track.geo(new THREE.PlaneGeometry(5.5, 80));
  for (let i = 0; i < 4; i++) {
    const path = new THREE.Mesh(pathGeo, pathMat);
    path.rotation.x = -Math.PI / 2;
    path.rotation.z = (i * Math.PI) / 4;
    path.position.y = 0.025;
    path.receiveShadow = true;
    group.add(path);
  }

  return group;
}

// ---------------------------------------------------------------------------
// Fantasyland
// ---------------------------------------------------------------------------

function buildCastle({ track, plain, lit, pbr, loadImage }: BuildCtx): THREE.Group {
  const group = new THREE.Group();

  const wallMat = plain({ ...pbr.stone, color: C.stoneLight, roughness: 0.9, metalness: 0 });
  const wallMat2 = plain({ ...pbr.stone, color: C.stoneBlue, roughness: 0.9, metalness: 0 });
  const goldMat = lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.5);

  const makeTower = (
    radius: number,
    height: number,
    roofColor: number,
    flagColor: number,
    body: THREE.MeshStandardMaterial
  ) => {
    const tower = new THREE.Group();
    const shaft = new THREE.Mesh(
      track.geo(new THREE.CylinderGeometry(radius, radius * 1.08, height, 20)),
      body
    );
    shaft.position.y = height / 2;
    shaft.castShadow = true;
    shaft.receiveShadow = true;
    tower.add(shaft);

    const roofH = radius * 3.4;
    const roof = new THREE.Mesh(
      track.geo(new THREE.ConeGeometry(radius * 1.25, roofH, 20)),
      lit({ color: roofColor, roughness: 0.55, metalness: 0 }, 0.45)
    );
    roof.position.y = height + roofH / 2;
    roof.castShadow = true;
    tower.add(roof);

    const finial = new THREE.Mesh(
      track.geo(new THREE.SphereGeometry(radius * 0.32, 12, 12)),
      goldMat
    );
    finial.position.y = height + roofH;
    tower.add(finial);

    const poleH = radius * 2.2;
    const pole = new THREE.Mesh(
      track.geo(new THREE.CylinderGeometry(radius * 0.05, radius * 0.05, poleH, 6)),
      goldMat
    );
    pole.position.y = height + roofH + poleH / 2;
    tower.add(pole);
    const flag = new THREE.Mesh(
      track.geo(new THREE.PlaneGeometry(radius * 1.3, radius * 0.7)),
      lit({ color: flagColor, roughness: 0.6, side: THREE.DoubleSide }, 0.5)
    );
    flag.position.set(radius * 0.7, height + roofH + poleH * 0.78, 0);
    tower.add(flag);
    return tower;
  };

  // --- Gatehouse with a central archway TUNNEL on x=0 ---------------------
  // The camera flies straight through, front to back. The clear opening is
  // x∈[-3.5, 3.5], y∈[0, 8], open at both ends (no geometry on the axis).
  const pierGeo = track.geo(new THREE.BoxGeometry(3, 9, 6));
  for (const sx of [-5.5, 5.5]) {
    const pier = new THREE.Mesh(pierGeo, wallMat);
    pier.position.set(sx, 4.5, 0);
    pier.castShadow = true;
    pier.receiveShadow = true;
    group.add(pier);
  }
  // Lintel spanning the piers — its underside (y=8) is the top of the opening,
  // well above the flight height (y≈4.4).
  const lintel = new THREE.Mesh(track.geo(new THREE.BoxGeometry(8.5, 2.6, 6)), wallMat);
  lintel.position.set(0, 9.3, 0);
  lintel.castShadow = true;
  lintel.receiveShadow = true;
  group.add(lintel);
  // Gold arch trim on the front + back faces of the opening.
  const archGeo = track.geo(new THREE.TorusGeometry(3.5, 0.45, 12, 24, Math.PI));
  for (const sz of [3.02, -3.02]) {
    const arch = new THREE.Mesh(archGeo, goldMat);
    arch.position.set(0, 8, sz);
    group.add(arch);
  }

  // Central tower over the tunnel — kept moderate so the castle reads WIDE.
  const central = makeTower(3.1, 11, C.roofBlue, C.flagRed, wallMat);
  central.position.set(0, 10.6, 0);
  group.add(central);

  // A broad spread of towers stepping down and outward (out to x≈±20), plus a
  // back row for depth — a sprawling, imposing footprint rather than one spire.
  const flank: Array<[number, number, number, number, number, THREE.MeshStandardMaterial]> = [
    [-9, 1, 9, C.roofPink, C.flagYellow, wallMat2],
    [9, 1, 9, C.roofPurple, C.flagBlue, wallMat2],
    [-15, 0, 7.5, C.roofTeal, C.flagRed, wallMat],
    [15, 0, 7.5, C.roofPink, C.flagBlue, wallMat],
    [-20.5, -2, 6, C.roofPurple, C.flagYellow, wallMat2],
    [20.5, -2, 6, C.roofTeal, C.flagBlue, wallMat2],
    [-11, -11, 7.5, C.roofBlue, C.flagRed, wallMat],
    [11, -11, 7.5, C.roofPink, C.flagYellow, wallMat],
  ];
  for (const [x, z, h, roof, flag, body] of flank) {
    const tower = makeTower(h >= 9 ? 2.0 : h >= 7 ? 1.6 : 1.3, h, roof, flag, body);
    tower.position.set(x, 0, z);
    group.add(tower);
  }

  // Broad crenellated curtain walls tie the towers into one sprawling mass.
  const makeWall = (x: number, w: number, h: number) => {
    const wall = new THREE.Mesh(track.geo(new THREE.BoxGeometry(w, h, 3)), wallMat);
    wall.position.set(x, h / 2, 0);
    wall.castShadow = true;
    wall.receiveShadow = true;
    group.add(wall);
    const cap = new THREE.Mesh(track.geo(new THREE.BoxGeometry(w, 0.8, 3.4)), wallMat2);
    cap.position.set(x, h + 0.4, 0);
    group.add(cap);
  };
  makeWall(-7, 4, 5);
  makeWall(7, 4, 5);
  makeWall(-12.5, 4.5, 4.5);
  makeWall(12.5, 4.5, 4.5);
  makeWall(-18, 4, 4);
  makeWall(18, 4, 4);

  // park.fan crest high on the central tower, facing the approach (+z). Unlit
  // (basic) material so it stays crisp and legible by day and night.
  const banner = new THREE.Group();
  const frame = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(6.2, 2.4, 0.3)),
    lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.5)
  );
  banner.add(frame);
  const board = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(5.7, 1.9, 0.32)),
    lit({ color: 0x16235c, roughness: 0.5 }, 0.35)
  );
  banner.add(board);
  const logoTex = loadImage('/parkfan-dark.png');
  const logoMat = track.mat(
    new THREE.MeshBasicMaterial({ map: logoTex, transparent: true, toneMapped: false })
  );
  const logo = new THREE.Mesh(track.geo(new THREE.PlaneGeometry(5.2, (5.2 * 219) / 768)), logoMat);
  logo.position.z = 0.2;
  banner.add(logo);
  banner.position.set(0, 15, 3.3); // on the central tower, toward the camera
  group.add(banner);

  return group;
}

/** The hidden courtyard garden revealed behind the castle (flythrough payoff). */
function buildCastleGarden({ track, plain, lit, pbr }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  group.position.set(0, 0, -44);

  // Paved courtyard disc.
  const court = new THREE.Mesh(
    track.geo(new THREE.CircleGeometry(11, 48)),
    plain({ ...pbr.paving, color: 0xf3e8d4, roughness: 0.95, metalness: 0 })
  );
  court.rotation.x = -Math.PI / 2;
  court.position.y = 0.02;
  court.receiveShadow = true;
  group.add(court);

  // Central tiered fountain with a little water jet.
  const stoneMat = plain({ ...pbr.stone, color: C.stoneLight, roughness: 0.9 });
  const basin = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(3, 3.3, 0.8, 28)), stoneMat);
  basin.position.y = 0.4;
  basin.castShadow = true;
  basin.receiveShadow = true;
  group.add(basin);
  const water = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(2.7, 2.7, 0.3, 28)),
    lit({ color: 0x3aa6d8, roughness: 0.2, transparent: true, opacity: 0.85 }, 0.2)
  );
  water.position.y = 0.75;
  group.add(water);
  const pedestal = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(0.4, 0.6, 2, 16)), stoneMat);
  pedestal.position.y = 1.6;
  group.add(pedestal);
  const topBowl = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(1.2, 0.5, 0.5, 20)),
    stoneMat
  );
  topBowl.position.y = 2.7;
  group.add(topBowl);
  const jet = new THREE.Mesh(
    track.geo(new THREE.SphereGeometry(0.35, 12, 12)),
    lit({ color: 0xbfe8ff, roughness: 0.2 }, 0.5)
  );
  jet.position.y = 3.2;
  group.add(jet);

  // Hedge ring with gaps, dotted with topiary balls.
  const hedgeMat = plain({ color: 0x3a8e3f, roughness: 1 });
  const ballMat = plain({ color: 0x4fbf5f, roughness: 1 });
  const hedgeGeo = track.geo(new THREE.BoxGeometry(2.4, 1.1, 0.9));
  const ballGeo = track.geo(new THREE.SphereGeometry(0.8, 12, 10));
  for (let i = 0; i < 12; i++) {
    const ang = (i / 12) * Math.PI * 2;
    if (i % 4 === 0) continue; // gaps
    const r = 8.5;
    const hedge = new THREE.Mesh(hedgeGeo, hedgeMat);
    hedge.position.set(Math.cos(ang) * r, 0.55, Math.sin(ang) * r);
    hedge.rotation.y = -ang;
    hedge.castShadow = true;
    group.add(hedge);
    const ball = new THREE.Mesh(ballGeo, ballMat);
    ball.position.set(Math.cos(ang) * r, 1.4, Math.sin(ang) * r);
    ball.castShadow = true;
    group.add(ball);
  }

  return group;
}

/** The big freestanding castle gate the camera flies through (front of castle). */
function buildCastleGate({ track, plain, lit, pbr }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  group.position.set(0, 0, -13);

  const stoneMat = plain({ ...pbr.stone, color: C.stoneLight, roughness: 0.9, metalness: 0 });
  // Two thick towers flanking a wide opening (clear from x≈-3.5..3.5, up to y≈9).
  const towerGeo = track.geo(new THREE.CylinderGeometry(2, 2.3, 11, 18));
  for (const sx of [-5.5, 5.5]) {
    const t = new THREE.Mesh(towerGeo, stoneMat);
    t.position.set(sx, 5.5, 0);
    t.castShadow = true;
    t.receiveShadow = true;
    group.add(t);
    const roof = new THREE.Mesh(
      track.geo(new THREE.ConeGeometry(2.5, 3.4, 18)),
      lit({ color: C.roofBlue, roughness: 0.55 }, 0.45)
    );
    roof.position.set(sx, 12.6, 0);
    roof.castShadow = true;
    group.add(roof);
  }
  // Arched lintel spanning the towers (well above the flight height).
  const span = new THREE.Mesh(track.geo(new THREE.BoxGeometry(9, 2.2, 2.4)), stoneMat);
  span.position.set(0, 9.6, 0);
  span.castShadow = true;
  group.add(span);
  const arch = new THREE.Mesh(
    track.geo(new THREE.TorusGeometry(3.6, 0.5, 12, 28, Math.PI)),
    lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.5)
  );
  arch.position.set(0, 8.4, 0);
  group.add(arch);

  return group;
}

function buildCarousel({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const R = 4.6;

  const base = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(R + 0.6, R + 0.9, 0.7, 36)),
    plain({ color: 0xf4d9ff, roughness: 0.7, metalness: 0 })
  );
  base.position.y = 0.35;
  base.castShadow = true;
  base.receiveShadow = true;
  group.add(base);

  const spinner = new THREE.Group();
  spinner.position.y = 0.7;
  group.add(spinner);

  const column = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.5, 0.5, 5.4, 16)),
    lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.45)
  );
  column.position.y = 2.7;
  spinner.add(column);

  const stripe = track.tex(makeStripeTexture('#ff5d6c', '#fff3f7'));
  stripe.repeat.set(8, 1);
  const roof = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(R + 1.1, 2.4, 28)),
    lit({ map: stripe, color: 0xffffff, roughness: 0.6 }, 0.4)
  );
  roof.position.y = 6.0;
  roof.castShadow = true;
  spinner.add(roof);

  const poleGeo = track.geo(new THREE.CylinderGeometry(0.07, 0.07, 3.4, 8));
  const poleMat = lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.45);
  const horses: Array<{ mount: THREE.Group; phase: number }> = [];
  const horseCount = 8;
  for (let i = 0; i < horseCount; i++) {
    const ang = (i / horseCount) * Math.PI * 2;
    const x = Math.cos(ang) * (R - 0.6);
    const z = Math.sin(ang) * (R - 0.6);
    const pole = new THREE.Mesh(poleGeo, poleMat);
    pole.position.set(x, 2.5, z);
    spinner.add(pole);

    const mount = new THREE.Group();
    mount.position.set(x, 2.1, z);
    const horseMat = lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.5 }, 0.5);
    const body = new THREE.Mesh(track.geo(new THREE.CapsuleGeometry(0.35, 0.9, 4, 8)), horseMat);
    body.rotation.z = Math.PI / 2;
    body.castShadow = true;
    mount.add(body);
    const head = new THREE.Mesh(track.geo(new THREE.BoxGeometry(0.5, 0.28, 0.26)), horseMat);
    head.position.set(0.9, 0.55, 0);
    mount.add(head);
    mount.rotation.y = -ang + Math.PI / 2;
    spinner.add(mount);
    horses.push({ mount, phase: i });
  }

  return {
    group,
    update: (elapsed) => {
      spinner.rotation.y = elapsed * 0.5;
      for (const h of horses) h.mount.position.y = 2.1 + Math.sin(elapsed * 2.2 + h.phase) * 0.28;
    },
  };
}

function buildTeacups({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const platform = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(3.6, 3.8, 0.5, 32)),
    plain({ color: 0xe9f4ff, roughness: 0.7, metalness: 0 })
  );
  platform.position.y = 0.25;
  platform.castShadow = true;
  platform.receiveShadow = true;
  group.add(platform);

  const turntable = new THREE.Group();
  turntable.position.y = 0.5;
  group.add(turntable);

  const cupGeo = track.geo(new THREE.CylinderGeometry(0.95, 0.7, 1.0, 18, 1, true));
  const cupBaseGeo = track.geo(new THREE.CylinderGeometry(0.7, 0.7, 0.12, 18));
  const cups: THREE.Group[] = [];
  for (let i = 0; i < 4; i++) {
    const ang = (i / 4) * Math.PI * 2;
    const cup = new THREE.Group();
    cup.position.set(Math.cos(ang) * 2.0, 0.5, Math.sin(ang) * 2.0);
    const cupMat = lit(
      { color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.45, side: THREE.DoubleSide },
      0.5
    );
    const shell = new THREE.Mesh(cupGeo, cupMat);
    shell.castShadow = true;
    cup.add(shell);
    const base = new THREE.Mesh(cupBaseGeo, cupMat);
    base.position.y = -0.44;
    cup.add(base);
    turntable.add(cup);
    cups.push(cup);
  }

  return {
    group,
    update: (elapsed) => {
      turntable.rotation.y = elapsed * 0.6;
      for (let i = 0; i < cups.length; i++) cups[i].rotation.y = -elapsed * (1.4 + i * 0.2);
    },
  };
}

// ---------------------------------------------------------------------------
// Tomorrowland
// ---------------------------------------------------------------------------

function buildFerrisWheel({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const R = 9;
  const spokes = 12;
  const frameMat = lit({ color: 0x5db8ff, metalness: 0.25, roughness: 0.4 }, 0.6);
  const legMat = plain({ color: 0xcad6e6, metalness: 0.2, roughness: 0.5 });
  const legGeo = track.geo(new THREE.CylinderGeometry(0.35, 0.45, R + 4, 12));
  for (const sx of [-3.2, 3.2]) {
    for (const sz of [2.4, -2.4]) {
      const leg = new THREE.Mesh(legGeo, legMat);
      leg.position.set(sx, (R + 4) / 2, sz);
      leg.rotation.x = sz > 0 ? 0.32 : -0.32;
      leg.castShadow = true;
      group.add(leg);
    }
  }

  const wheel = new THREE.Group();
  wheel.position.y = R + 1.5;
  group.add(wheel);
  const rimGeo = track.geo(new THREE.TorusGeometry(R, 0.22, 12, 56));
  for (const z of [0.9, -0.9]) {
    const rim = new THREE.Mesh(rimGeo, frameMat);
    rim.position.z = z;
    rim.castShadow = true;
    wheel.add(rim);
  }
  const spokeGeo = track.geo(new THREE.CylinderGeometry(0.07, 0.07, R * 2, 6));
  for (let i = 0; i < spokes; i++) {
    const spoke = new THREE.Mesh(spokeGeo, frameMat);
    spoke.rotation.z = (i / spokes) * Math.PI;
    wheel.add(spoke);
  }

  const cabinGeo = track.geo(new THREE.BoxGeometry(1.7, 1.5, 1.7));
  const gondolas: THREE.Group[] = [];
  for (let i = 0; i < spokes; i++) {
    const ang = (i / spokes) * Math.PI * 2;
    const pivot = new THREE.Group();
    pivot.position.set(Math.cos(ang) * R, Math.sin(ang) * R, 0);
    wheel.add(pivot);
    const cabin = new THREE.Mesh(
      cabinGeo,
      lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.45 }, 0.8)
    );
    cabin.castShadow = true;
    cabin.position.y = -1.4;
    pivot.add(cabin);
    gondolas.push(pivot);
  }

  return {
    group,
    update: (elapsed) => {
      const rot = elapsed * 0.28;
      wheel.rotation.z = rot;
      for (const g of gondolas) g.rotation.z = -rot;
    },
  };
}

/** Orbitron-style rocket ride: rockets on arms that spin and rise/fall. */
function buildRocketRide({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const tower = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.6, 1.0, 7, 16)),
    plain({ color: 0xc0ccda, metalness: 0.3, roughness: 0.4 })
  );
  tower.position.y = 3.5;
  tower.castShadow = true;
  group.add(tower);
  const topBall = new THREE.Mesh(
    track.geo(new THREE.SphereGeometry(0.8, 16, 16)),
    lit({ color: 0x5db8ff, metalness: 0.3, roughness: 0.3 }, 0.6)
  );
  topBall.position.y = 7.4;
  group.add(topBall);

  const spinner = new THREE.Group();
  spinner.position.y = 2.4;
  group.add(spinner);
  const arms: THREE.Group[] = [];
  const count = 6;
  for (let i = 0; i < count; i++) {
    const arm = new THREE.Group();
    arm.rotation.y = (i / count) * Math.PI * 2;
    const armBar = new THREE.Mesh(
      track.geo(new THREE.CylinderGeometry(0.1, 0.1, 3, 6)),
      plain({ color: 0xc0ccda, metalness: 0.3, roughness: 0.4 })
    );
    armBar.rotation.z = Math.PI / 2;
    armBar.position.x = 1.5;
    arm.add(armBar);

    const rocket = new THREE.Group();
    rocket.position.set(3, 0, 0);
    const bodyMat = lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.4 }, 0.6);
    const body = new THREE.Mesh(track.geo(new THREE.CapsuleGeometry(0.35, 1.0, 6, 10)), bodyMat);
    body.castShadow = true;
    rocket.add(body);
    const nose = new THREE.Mesh(
      track.geo(new THREE.ConeGeometry(0.35, 0.6, 10)),
      lit({ color: C.gold, roughness: 0.35 }, 0.5)
    );
    nose.position.y = 0.8;
    rocket.add(nose);
    arm.add(rocket);
    spinner.add(arm);
    arms.push(arm);
  }

  return {
    group,
    update: (elapsed) => {
      spinner.rotation.y = elapsed * 0.8;
      arms.forEach((arm, i) => {
        const rocket = arm.children[1];
        rocket.position.y = Math.sin(elapsed * 1.5 + i) * 0.8 + 0.4;
      });
    },
  };
}

/** Futuristic metallic domes for Tomorrowland. */
function buildDomes({ track, plain, lit }: BuildCtx): THREE.Group[] {
  const domes: THREE.Group[] = [];
  const palette = [0xbfe3ff, 0xd7c4ff, 0xc0ccda];
  for (let i = 0; i < 3; i++) {
    const g = new THREE.Group();
    const base = new THREE.Mesh(
      track.geo(new THREE.CylinderGeometry(2, 2.2, 1.4, 20)),
      plain({ color: 0xdfe9ff, metalness: 0.3, roughness: 0.5 })
    );
    base.position.y = 0.7;
    base.castShadow = true;
    base.receiveShadow = true;
    g.add(base);
    const dome = new THREE.Mesh(
      track.geo(new THREE.SphereGeometry(2, 20, 12, 0, Math.PI * 2, 0, Math.PI / 2)),
      lit({ color: palette[i % palette.length], metalness: 0.35, roughness: 0.3 }, 0.4)
    );
    dome.position.y = 1.4;
    dome.castShadow = true;
    g.add(dome);
    const spire = new THREE.Mesh(
      track.geo(new THREE.ConeGeometry(0.18, 2, 8)),
      lit({ color: C.gold, roughness: 0.35 }, 0.6)
    );
    spire.position.y = 4.2;
    g.add(spire);
    domes.push(g);
  }
  return domes;
}

// ---------------------------------------------------------------------------
// Adventureland
// ---------------------------------------------------------------------------

function buildLake({ track, plain, pbr, registerWater }: BuildCtx): Animated {
  const group = new THREE.Group();
  const shore = new THREE.Mesh(
    track.geo(new THREE.CircleGeometry(8.4, 48)),
    plain({ ...pbr.paving, color: 0xe8dcc0, roughness: 1, metalness: 0 })
  );
  shore.rotation.x = -Math.PI / 2;
  shore.position.y = 0.02;
  shore.receiveShadow = true;
  group.add(shore);

  const waterNormal = track.tex(makeWaterNormal());
  waterNormal.repeat.set(3, 3);
  const waterMat = plain({
    color: DAY.water,
    roughness: 0.25,
    metalness: 0.0,
    normalMap: waterNormal,
    transparent: true,
    opacity: 0.85,
  });
  waterMat.normalScale = new THREE.Vector2(0.45, 0.45);
  waterMat.emissive = new THREE.Color(DAY.water);
  waterMat.emissiveIntensity = 0.12;
  registerWater(waterMat);
  const water = new THREE.Mesh(track.geo(new THREE.CircleGeometry(7.4, 48)), waterMat);
  water.rotation.x = -Math.PI / 2;
  water.position.y = 0.08;
  group.add(water);

  return {
    group,
    update: (elapsed) => waterNormal.offset.set(elapsed * 0.015, elapsed * 0.022),
  };
}

/** A tiki hut: wooden posts under a thatched cone roof. */
function buildTikiHut({ track, plain, lit }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  const postMat = plain({ color: 0x6b4a2b, roughness: 0.9 });
  const postGeo = track.geo(new THREE.CylinderGeometry(0.16, 0.18, 2.4, 8));
  for (const [sx, sz] of [
    [-1.4, -1.4],
    [1.4, -1.4],
    [-1.4, 1.4],
    [1.4, 1.4],
  ]) {
    const post = new THREE.Mesh(postGeo, postMat);
    post.position.set(sx, 1.2, sz);
    post.castShadow = true;
    group.add(post);
  }
  const platform = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(3.4, 0.3, 3.4)),
    plain({ color: 0x8a5a2b, roughness: 0.9 })
  );
  platform.position.y = 0.15;
  platform.receiveShadow = true;
  group.add(platform);
  const roof = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(3, 2, 4)),
    lit({ color: 0xc7a24b, roughness: 0.9 }, 0.25)
  );
  roof.position.y = 3.4;
  roof.rotation.y = Math.PI / 4;
  roof.castShadow = true;
  group.add(roof);
  return group;
}

// ---------------------------------------------------------------------------
// Frontierland
// ---------------------------------------------------------------------------

/** A western-town building: wooden box, false front and gable roof. */
function buildWesternBuilding({ track, plain, pbr }: BuildCtx, color: number): THREE.Group {
  const group = new THREE.Group();
  const wallMat = plain({ ...pbr.wood, color, roughness: 0.85, metalness: 0 });
  const body = new THREE.Mesh(track.geo(new THREE.BoxGeometry(4, 4, 4)), wallMat);
  body.position.y = 2;
  body.castShadow = true;
  body.receiveShadow = true;
  group.add(body);
  // False front (taller facade).
  const front = new THREE.Mesh(track.geo(new THREE.BoxGeometry(4.4, 1.8, 0.3)), wallMat);
  front.position.set(0, 4.6, 2);
  front.castShadow = true;
  group.add(front);
  // Gable roof.
  const roof = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(2.9, 2.9, 4.2, 3, 1)),
    plain({ ...pbr.wood, color: 0x6b4a2b, roughness: 0.9 })
  );
  roof.rotation.z = Math.PI / 2;
  roof.rotation.y = Math.PI / 2;
  roof.position.y = 4.6;
  roof.scale.set(1, 1, 0.7);
  roof.castShadow = true;
  group.add(roof);
  // Awning over the porch.
  const awning = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(4.2, 0.15, 1.4)),
    plain({ color: 0x4a341f, roughness: 0.9 })
  );
  awning.position.set(0, 2.7, 2.6);
  group.add(awning);
  return group;
}

// ---------------------------------------------------------------------------
// Shared rides / props
// ---------------------------------------------------------------------------

function buildSwingRide({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const tower = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.7, 1.0, 11, 16)),
    lit({ color: 0x8be04e, metalness: 0.1, roughness: 0.5 }, 0.4)
  );
  tower.position.y = 5.5;
  tower.castShadow = true;
  group.add(tower);
  const cap = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(2.6, 1.8, 20)),
    lit({ color: C.flagRed, roughness: 0.5 }, 0.5)
  );
  cap.position.y = 11.6;
  cap.castShadow = true;
  group.add(cap);

  const spinner = new THREE.Group();
  spinner.position.y = 10.6;
  group.add(spinner);
  const disc = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(2.4, 2.4, 0.3, 20)),
    lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.45)
  );
  spinner.add(disc);

  const chainMat = plain({ color: 0x888888, metalness: 0.4, roughness: 0.5 });
  const chainGeo = track.geo(new THREE.CylinderGeometry(0.02, 0.02, 3.4, 4));
  const seatGeo = track.geo(new THREE.BoxGeometry(0.5, 0.4, 0.5));
  const arms: THREE.Group[] = [];
  const seatCount = 10;
  for (let i = 0; i < seatCount; i++) {
    const arm = new THREE.Group();
    arm.rotation.y = (i / seatCount) * Math.PI * 2;
    const chain = new THREE.Mesh(chainGeo, chainMat);
    chain.position.set(2.3, -1.7, 0);
    arm.add(chain);
    const seat = new THREE.Mesh(
      seatGeo,
      lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.5 }, 0.5)
    );
    seat.position.set(2.3, -3.4, 0);
    seat.castShadow = true;
    arm.add(seat);
    spinner.add(arm);
    arms.push(arm);
  }

  return {
    group,
    update: (elapsed) => {
      spinner.rotation.y = elapsed * 0.9;
      const flare = 0.5 + Math.sin(elapsed * 0.3) * 0.18;
      for (const a of arms) a.children.forEach((c) => (c.rotation.z = -flare));
    },
  };
}

function buildCoaster(
  { track, plain, lit }: BuildCtx,
  opts?: { pts?: THREE.Vector3[]; color?: number; speed?: number }
): Animated {
  const group = new THREE.Group();
  const pts = opts?.pts ?? [
    new THREE.Vector3(-34, 1, 24),
    new THREE.Vector3(-40, 1.5, 2),
    new THREE.Vector3(-32, 9, -16),
    new THREE.Vector3(-12, 13, -24),
    new THREE.Vector3(10, 7, -22),
    new THREE.Vector3(24, 3, -6),
    new THREE.Vector3(36, 5, 12),
    new THREE.Vector3(28, 2, 28),
    new THREE.Vector3(2, 1.2, 32),
    new THREE.Vector3(-18, 2, 30),
  ];
  const railColor = opts?.color ?? C.coaster;
  const trainSpeed = opts?.speed ?? 0.05;
  const curve = new THREE.CatmullRomCurve3(pts, true, 'catmullrom', 0.5);
  const SEG = 360;
  const frames = curve.computeFrenetFrames(SEG, true);
  const railOffset = 0.55;
  const leftPts: THREE.Vector3[] = [];
  const rightPts: THREE.Vector3[] = [];
  const centers: THREE.Vector3[] = [];
  for (let i = 0; i <= SEG; i++) {
    const p = curve.getPointAt(i / SEG);
    centers.push(p);
    const side = frames.binormals[i].clone().multiplyScalar(railOffset);
    leftPts.push(p.clone().add(side));
    rightPts.push(p.clone().sub(side));
  }
  const railMat = lit({ color: railColor, metalness: 0.2, roughness: 0.4 }, 0.7);
  const makeRail = (points: THREE.Vector3[]) => {
    const c = new THREE.CatmullRomCurve3(points, true);
    const mesh = new THREE.Mesh(track.geo(new THREE.TubeGeometry(c, SEG, 0.16, 8, true)), railMat);
    mesh.castShadow = true;
    return mesh;
  };
  group.add(makeRail(leftPts));
  group.add(makeRail(rightPts));

  const tieMat = lit({ color: 0xffe08a, roughness: 0.5 }, 0.4);
  const tieGeo = track.geo(new THREE.BoxGeometry(railOffset * 2 + 0.2, 0.1, 0.18));
  for (let i = 0; i < SEG; i += 5) {
    const tie = new THREE.Mesh(tieGeo, tieMat);
    tie.position.copy(centers[i]);
    const m = new THREE.Matrix4();
    m.lookAt(new THREE.Vector3(0, 0, 0), curve.getTangentAt(i / SEG), frames.normals[i]);
    tie.quaternion.setFromRotationMatrix(m);
    group.add(tie);
  }
  const postMat = plain({ color: 0x8a5a2b, metalness: 0, roughness: 0.85 });
  for (let i = 0; i < SEG; i += 14) {
    const p = centers[i];
    if (p.y < 1.2) continue;
    const post = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(0.18, 0.22, p.y, 8)), postMat);
    post.position.set(p.x, p.y / 2, p.z);
    post.castShadow = true;
    group.add(post);
  }

  const train = new THREE.Group();
  group.add(train);
  const cars: THREE.Group[] = [];
  const carBodyGeo = track.geo(new THREE.BoxGeometry(0.9, 0.6, 1.3));
  const headGeo = track.geo(new THREE.SphereGeometry(0.22, 10, 10));
  const headMat = plain({ color: 0xffe0bd, roughness: 0.7 });
  for (let i = 0; i < 5; i++) {
    const car = new THREE.Group();
    const carMat = lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.4 }, 0.8);
    const body = new THREE.Mesh(carBodyGeo, carMat);
    body.position.y = 0.35;
    body.castShadow = true;
    car.add(body);
    for (const hx of [-0.22, 0.22]) {
      const head = new THREE.Mesh(headGeo, headMat);
      head.position.set(hx, 0.78, -0.1);
      car.add(head);
    }
    train.add(car);
    cars.push(car);
  }
  const up = new THREE.Vector3(0, 1, 0);
  const tmpT = new THREE.Vector3();
  const tmpM = new THREE.Matrix4();
  const place = (car: THREE.Group, t: number) => {
    const tt = ((t % 1) + 1) % 1;
    car.position.copy(curve.getPointAt(tt));
    curve.getTangentAt(tt, tmpT);
    car.position.y += 0.32;
    tmpM.lookAt(new THREE.Vector3(0, 0, 0), tmpT, up);
    car.quaternion.setFromRotationMatrix(tmpM);
  };

  return {
    group,
    update: (elapsed) => {
      const head = (elapsed * trainSpeed) % 1;
      for (let i = 0; i < cars.length; i++) place(cars[i], head - i * 0.018);
    },
  };
}

function buildEntranceGate({ track, plain, lit }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  group.position.set(0, 0, 34);
  const pillarMat = plain({ color: 0xfff0e6, roughness: 0.85 });
  const pillarGeo = track.geo(new THREE.BoxGeometry(1.6, 6, 1.6));
  const capGeo = track.geo(new THREE.ConeGeometry(1.3, 1.6, 4));
  for (const sx of [-5, 5]) {
    const pillar = new THREE.Mesh(pillarGeo, pillarMat);
    pillar.position.set(sx, 3, 0);
    pillar.castShadow = true;
    group.add(pillar);
    const cap = new THREE.Mesh(capGeo, lit({ color: C.roofPink, roughness: 0.5 }, 0.5));
    cap.position.set(sx, 6.8, 0);
    cap.rotation.y = Math.PI / 4;
    group.add(cap);
  }
  const stripe = track.tex(makeStripeTexture('#ff5d6c', '#fff3f7'));
  stripe.repeat.set(10, 1);
  const arch = new THREE.Mesh(
    track.geo(new THREE.TorusGeometry(5, 0.7, 12, 32, Math.PI)),
    lit({ map: stripe, color: 0xffffff, roughness: 0.6 }, 0.4)
  );
  arch.position.set(0, 6, 0);
  arch.castShadow = true;
  group.add(arch);
  const sign = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(6.4, 1.4, 0.3)),
    lit({ color: C.gold, metalness: 0.2, roughness: 0.35 }, 0.6)
  );
  sign.position.set(0, 7.4, 0);
  group.add(sign);
  return group;
}

function buildTent({ track }: BuildCtx, colorA: string, colorB: string): THREE.Group {
  const group = new THREE.Group();
  const stripe = track.tex(makeStripeTexture(colorA, colorB));
  stripe.repeat.set(10, 1);
  const roofMat = track.mat(new THREE.MeshStandardMaterial({ map: stripe, roughness: 0.7 }));
  const wallMat = track.mat(new THREE.MeshStandardMaterial({ color: 0xfff3f7, roughness: 0.85 }));
  const wall = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(2.4, 2.4, 2, 24)), wallMat);
  wall.position.y = 1;
  wall.castShadow = true;
  wall.receiveShadow = true;
  group.add(wall);
  const roof = new THREE.Mesh(track.geo(new THREE.ConeGeometry(3.1, 2.6, 24)), roofMat);
  roof.position.y = 3.3;
  roof.castShadow = true;
  group.add(roof);
  return group;
}

function buildStall({ track, plain, lit, pbr }: BuildCtx, accent: number): THREE.Group {
  const group = new THREE.Group();
  const counter = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(3, 1.4, 1.6)),
    plain({ ...pbr.wood, roughness: 0.8, metalness: 0 })
  );
  counter.position.y = 0.7;
  counter.castShadow = true;
  counter.receiveShadow = true;
  group.add(counter);
  const postMat = plain({ ...pbr.wood, roughness: 0.8 });
  const postGeo = track.geo(new THREE.CylinderGeometry(0.08, 0.08, 2.6, 8));
  for (const sx of [-1.4, 1.4]) {
    const post = new THREE.Mesh(postGeo, postMat);
    post.position.set(sx, 1.3, 0.7);
    group.add(post);
  }
  const awning = new THREE.Mesh(
    track.geo(new THREE.BoxGeometry(3.3, 0.18, 1.8)),
    lit({ color: accent, roughness: 0.6 }, 0.45)
  );
  awning.position.set(0, 2.6, 0.2);
  awning.rotation.x = -0.18;
  awning.castShadow = true;
  group.add(awning);
  return group;
}

function buildLantern(
  { track, plain, lit, lampLights }: BuildCtx,
  x: number,
  z: number,
  withLight: boolean
): THREE.Group {
  const group = new THREE.Group();
  group.position.set(x, 0, z);
  const post = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.08, 0.12, 3.2, 10)),
    plain({ color: 0x2a2f3a, metalness: 0.3, roughness: 0.6 })
  );
  post.position.y = 1.6;
  post.castShadow = true;
  group.add(post);
  const bulb = new THREE.Mesh(
    track.geo(new THREE.SphereGeometry(0.26, 14, 14)),
    lit({ color: 0xffe6a8, roughness: 0.3 }, 1.8)
  );
  bulb.position.y = 3.4;
  group.add(bulb);
  if (withLight) {
    const light = new THREE.PointLight(0xffd79a, 0, 18, 2);
    light.position.set(0, 3.4, 0);
    lampLights.push(light);
    group.add(light);
  }
  return group;
}

function buildFences({ track, plain }: BuildCtx): THREE.InstancedMesh {
  const count = 72;
  const geo = track.geo(new THREE.BoxGeometry(0.9, 0.7, 0.08));
  const mat = plain({ color: 0xffffff, roughness: 0.8 });
  const inst = new THREE.InstancedMesh(geo, mat, count);
  inst.castShadow = true;
  const R = 13.4;
  const m = new THREE.Matrix4();
  const q = new THREE.Quaternion();
  const pos = new THREE.Vector3();
  const scl = new THREE.Vector3(1, 1, 1);
  const up = new THREE.Vector3(0, 1, 0);
  const gapAngles = [
    0,
    Math.PI / 2,
    Math.PI,
    (3 * Math.PI) / 2,
    Math.PI / 4,
    (3 * Math.PI) / 4,
    (5 * Math.PI) / 4,
    (7 * Math.PI) / 4,
  ];
  for (let i = 0; i < count; i++) {
    const ang = (i / count) * Math.PI * 2;
    const near = Math.min(
      ...gapAngles.map((a) => Math.abs(((ang - a + Math.PI) % (Math.PI * 2)) - Math.PI))
    );
    pos.set(Math.cos(ang) * R, near < 0.12 ? -3 : 0.35, Math.sin(ang) * R);
    q.setFromAxisAngle(up, -ang);
    m.compose(pos, q, scl);
    inst.setMatrixAt(i, m);
  }
  inst.instanceMatrix.needsUpdate = true;
  return inst;
}

function buildFlowerBeds({ track, lit }: BuildCtx): THREE.InstancedMesh {
  const count = 180;
  const geo = track.geo(new THREE.SphereGeometry(0.22, 6, 5));
  const mat = lit({ color: 0xffffff, roughness: 0.7 }, 0.3);
  const inst = new THREE.InstancedMesh(geo, mat, count);
  const m = new THREE.Matrix4();
  const q = new THREE.Quaternion();
  const pos = new THREE.Vector3();
  const scl = new THREE.Vector3();
  const color = new THREE.Color();
  for (let i = 0; i < count; i++) {
    const ang = Math.random() * Math.PI * 2;
    const r = 12 + Math.random() * 24;
    const s = 0.6 + Math.random() * 0.9;
    pos.set(Math.cos(ang) * r, 0.18 * s, Math.sin(ang) * r);
    scl.set(s, s * (0.7 + Math.random() * 0.5), s);
    m.compose(pos, q, scl);
    inst.setMatrixAt(i, m);
    color.set(FLOWER_COLORS[i % FLOWER_COLORS.length]);
    inst.setColorAt(i, color);
  }
  inst.instanceMatrix.needsUpdate = true;
  if (inst.instanceColor) inst.instanceColor.needsUpdate = true;
  return inst;
}

function buildTree({ track, plain }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  const trunk = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.3, 0.4, 2, 8)),
    plain({ color: 0x8a5a2b, roughness: 0.95 })
  );
  trunk.position.y = 1;
  trunk.castShadow = true;
  group.add(trunk);
  const lower = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(1.7, 2.6, 12)),
    plain({ color: C.leafDark, roughness: 1 })
  );
  lower.position.y = 2.6;
  lower.castShadow = true;
  group.add(lower);
  const upper = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(1.3, 2.2, 12)),
    plain({ color: C.leaf, roughness: 1 })
  );
  upper.position.y = 3.8;
  upper.castShadow = true;
  group.add(upper);
  return group;
}

/**
 * Articulated RCT-style "peeps": head + hair, a colored torso, and swinging
 * arms and legs driven by a simple walk cycle as they stroll the paths.
 */
function buildVisitors({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const skinMat = plain({ color: 0xffd9b8, roughness: 0.75 });
  // Chunky RCT "peep" proportions: big round head, short stout body, stubby limbs.
  const headGeo = track.geo(new THREE.SphereGeometry(0.27, 14, 12));
  const hairGeo = track.geo(
    new THREE.SphereGeometry(0.28, 14, 10, 0, Math.PI * 2, 0, Math.PI * 0.52)
  );
  const torsoGeo = track.geo(new THREE.CapsuleGeometry(0.24, 0.16, 4, 10));
  const limbGeo = track.geo(new THREE.CapsuleGeometry(0.085, 0.18, 3, 6));
  const hairColors = [0x3a2a1a, 0x6b4a2b, 0x141414, 0xc9a24b, 0x8a8a8a, 0xb5532a];
  const pantsColors = [0x2a3b6b, 0x44464d, 0x6b4a2b, 0x2a5b3b, 0x5b2a4a];

  interface Peep {
    g: THREE.Group;
    legL: THREE.Group;
    legR: THREE.Group;
    armL: THREE.Group;
    armR: THREE.Group;
    radius: number;
    speed: number;
    phase: number;
  }
  const people: Peep[] = [];
  const count = 24;

  for (let i = 0; i < count; i++) {
    const person = new THREE.Group();
    const shirtMat = lit(
      { color: VISITOR_COLORS[i % VISITOR_COLORS.length], roughness: 0.7 },
      0.25
    );
    const pantsMat = plain({ color: pantsColors[i % pantsColors.length], roughness: 0.8 });

    const torso = new THREE.Mesh(torsoGeo, shirtMat);
    torso.position.y = 0.7;
    torso.castShadow = true;
    person.add(torso);

    const head = new THREE.Mesh(headGeo, skinMat);
    head.position.y = 1.16;
    head.castShadow = true;
    person.add(head);
    const hair = new THREE.Mesh(
      hairGeo,
      plain({ color: hairColors[i % hairColors.length], roughness: 0.85 })
    );
    hair.position.y = 1.2;
    person.add(hair);

    // Limb on a pivot at the hip/shoulder so rotation.x swings it like a hinge.
    const makeLimb = (mat: THREE.MeshStandardMaterial, x: number, y: number) => {
      const pivot = new THREE.Group();
      pivot.position.set(x, y, 0);
      const limb = new THREE.Mesh(limbGeo, mat);
      limb.position.y = -0.14;
      limb.castShadow = true;
      pivot.add(limb);
      person.add(pivot);
      return pivot;
    };
    const legL = makeLimb(pantsMat, -0.11, 0.44);
    const legR = makeLimb(pantsMat, 0.11, 0.44);
    const armL = makeLimb(shirtMat, -0.27, 0.86);
    const armR = makeLimb(shirtMat, 0.27, 0.86);

    // Peeps are small; scale up a touch so they read from the flying camera.
    person.scale.setScalar(1.25);
    group.add(person);
    people.push({
      g: person,
      legL,
      legR,
      armL,
      armR,
      radius: 7 + (i % 6) * 1.2,
      speed: (0.1 + (i % 4) * 0.035) * (i % 2 === 0 ? 1 : -1),
      phase: (i / count) * Math.PI * 2,
    });
  }

  return {
    group,
    update: (elapsed) => {
      for (const p of people) {
        const a = p.phase + elapsed * p.speed;
        p.g.position.set(Math.cos(a) * p.radius, 0, Math.sin(a) * p.radius);
        p.g.rotation.y = -a + (p.speed > 0 ? Math.PI / 2 : -Math.PI / 2);
        // Walk cycle: legs + arms swing in opposition, body bobs gently.
        const step = elapsed * 6 * (p.speed > 0 ? 1 : -1) + p.phase * 3;
        const sw = Math.sin(step) * 0.5;
        p.legL.rotation.x = sw;
        p.legR.rotation.x = -sw;
        p.armL.rotation.x = -sw * 0.8;
        p.armR.rotation.x = sw * 0.8;
        p.g.position.y = Math.abs(Math.sin(step)) * 0.04;
      }
    },
  };
}

/** Low-poly mountains ringing the park on the horizon — depth + scale. */
function buildMountains({ track, plain }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  const rockMat = plain({ color: 0x8a9bb0, roughness: 1, metalness: 0 });
  const snowMat = plain({ color: 0xf2f6ff, roughness: 0.9, metalness: 0 });
  const count = 16;
  for (let i = 0; i < count; i++) {
    const ang = (i / count) * Math.PI * 2 + (i % 2) * 0.2;
    const dist = 92 + (i % 4) * 8;
    const h = 22 + ((i * 7) % 18);
    const r = 12 + ((i * 5) % 8);
    const peak = new THREE.Mesh(track.geo(new THREE.ConeGeometry(r, h, 6)), rockMat);
    peak.position.set(Math.cos(ang) * dist, h / 2 - 2, Math.sin(ang) * dist);
    peak.rotation.y = i;
    group.add(peak);
    // Snow cap.
    const cap = new THREE.Mesh(track.geo(new THREE.ConeGeometry(r * 0.42, h * 0.32, 6)), snowMat);
    cap.position.set(peak.position.x, h * 0.84 - 2, peak.position.z);
    cap.rotation.y = i;
    group.add(cap);
  }
  return group;
}

function buildClouds({ track, plain }: BuildCtx): Animated {
  const group = new THREE.Group();
  const cloudMat = plain({ color: 0xffffff, roughness: 1, transparent: true, opacity: 0.92 });
  const puffGeo = track.geo(new THREE.SphereGeometry(2, 12, 10));
  const clouds: Array<{ mesh: THREE.Group; speed: number }> = [];
  for (let i = 0; i < 8; i++) {
    const cloud = new THREE.Group();
    const puffs = 3 + (i % 3);
    for (let j = 0; j < puffs; j++) {
      const puff = new THREE.Mesh(puffGeo, cloudMat);
      puff.position.set(
        (j - puffs / 2) * 2.4 + ((i * 7) % 2),
        ((j * 5) % 3) * 0.6,
        ((j * 3) % 4) - 1
      );
      puff.scale.set(1 + ((i + j) % 3) * 0.25, 0.7, 1);
      cloud.add(puff);
    }
    cloud.position.set(((i * 17) % 90) - 45, 30 + ((i * 11) % 10), -36 - ((i * 13) % 30));
    cloud.scale.setScalar(1.2 + ((i * 5) % 4) / 3);
    group.add(cloud);
    clouds.push({ mesh: cloud, speed: 0.4 + ((i * 3) % 5) / 6 });
  }
  return {
    group,
    update: (_elapsed, delta) => {
      for (const c of clouds) {
        c.mesh.position.x += c.speed * delta * 1.4;
        if (c.mesh.position.x > 58) c.mesh.position.x = -58;
      }
    },
  };
}

/**
 * Particle fireworks bursting at a fixed origin (over the castle). Rockets rise
 * from the ground, explode into colored sparks that fall and fade. Additive
 * blending makes them glow against the night sky without any post-processing.
 */
function buildFireworks({ track }: BuildCtx, origin: THREE.Vector3): Animated {
  const MAX = 600;
  const positions = new Float32Array(MAX * 3);
  const colors = new Float32Array(MAX * 3);
  const geo = track.geo(new THREE.BufferGeometry());
  geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
  const mat = track.mat(
    new THREE.PointsMaterial({
      size: 0.6,
      vertexColors: true,
      transparent: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
      sizeAttenuation: true,
    })
  );
  const points = new THREE.Points(geo, mat);
  points.frustumCulled = false;
  const group = new THREE.Group();
  group.add(points);

  type P = {
    x: number;
    y: number;
    z: number;
    vx: number;
    vy: number;
    vz: number;
    life: number;
    max: number;
    r: number;
    g: number;
    b: number;
    active: boolean;
  };
  const pool: P[] = Array.from({ length: MAX }, () => ({
    x: 0,
    y: 0,
    z: 0,
    vx: 0,
    vy: 0,
    vz: 0,
    life: 0,
    max: 1,
    r: 0,
    g: 0,
    b: 0,
    active: false,
  }));
  type Rocket = {
    x: number;
    y: number;
    z: number;
    vy: number;
    target: number;
    r: number;
    g: number;
    b: number;
    active: boolean;
  };
  const rockets: Rocket[] = Array.from({ length: 4 }, () => ({
    x: 0,
    y: 0,
    z: 0,
    vy: 0,
    target: 0,
    r: 1,
    g: 1,
    b: 1,
    active: false,
  }));
  const col = new THREE.Color();
  let timer = 0.4;

  const launch = () => {
    const r = rockets.find((x) => !x.active);
    if (!r) return;
    col.set(FIREWORK_COLORS[Math.floor(Math.random() * FIREWORK_COLORS.length)]);
    r.x = origin.x + (Math.random() - 0.5) * 12;
    r.z = origin.z + (Math.random() - 0.5) * 8;
    r.y = 1;
    r.vy = 12 + Math.random() * 3;
    r.target = origin.y + (Math.random() - 0.5) * 6;
    r.r = col.r;
    r.g = col.g;
    r.b = col.b;
    r.active = true;
  };

  const burst = (x: number, y: number, z: number, r: number, g: number, b: number) => {
    let spawned = 0;
    const n = 70;
    const speed = 5 + Math.random() * 3;
    for (const p of pool) {
      if (p.active) continue;
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(2 * Math.random() - 1);
      const s = speed * (0.6 + Math.random() * 0.4);
      p.x = x;
      p.y = y;
      p.z = z;
      p.vx = Math.sin(phi) * Math.cos(theta) * s;
      p.vy = Math.cos(phi) * s;
      p.vz = Math.sin(phi) * Math.sin(theta) * s;
      p.max = 1.1 + Math.random() * 0.7;
      p.life = p.max;
      p.r = r;
      p.g = g;
      p.b = b;
      p.active = true;
      if (++spawned >= n) break;
    }
  };

  return {
    group,
    update: (_elapsed, delta) => {
      const dt = delta > 0 ? delta : 0.016;
      timer -= dt;
      if (timer <= 0) {
        launch();
        timer = 0.9 + Math.random() * 1.1;
      }
      // Rockets rise, then explode.
      for (const r of rockets) {
        if (!r.active) continue;
        r.y += r.vy * dt;
        r.vy -= 6 * dt;
        if (r.y >= r.target || r.vy <= 0) {
          burst(r.x, r.y, r.z, r.r, r.g, r.b);
          r.active = false;
        }
      }
      // Sparks fall + fade.
      for (const p of pool) {
        if (!p.active) continue;
        p.life -= dt;
        if (p.life <= 0) {
          p.active = false;
          continue;
        }
        p.vy -= 5.5 * dt;
        p.x += p.vx * dt;
        p.y += p.vy * dt;
        p.z += p.vz * dt;
        p.vx *= 0.98;
        p.vz *= 0.98;
      }
      // Write buffers: rockets as bright heads, sparks faded by remaining life.
      let n = 0;
      for (const r of rockets) {
        if (!r.active) continue;
        positions[n * 3] = r.x;
        positions[n * 3 + 1] = r.y;
        positions[n * 3 + 2] = r.z;
        colors[n * 3] = r.r;
        colors[n * 3 + 1] = r.g;
        colors[n * 3 + 2] = r.b;
        n++;
      }
      for (const p of pool) {
        if (!p.active) continue;
        const f = p.life / p.max;
        positions[n * 3] = p.x;
        positions[n * 3 + 1] = p.y;
        positions[n * 3 + 2] = p.z;
        colors[n * 3] = p.r * f;
        colors[n * 3 + 1] = p.g * f;
        colors[n * 3 + 2] = p.b * f;
        n++;
        if (n >= MAX) break;
      }
      geo.setDrawRange(0, n);
      (geo.attributes.position as THREE.BufferAttribute).needsUpdate = true;
      (geo.attributes.color as THREE.BufferAttribute).needsUpdate = true;
    },
  };
}

/**
 * The grand finale behind the castle: a great reflecting lake with a dancing
 * fountain show, a snow-capped waterfall mountain, and a giant glowing park.fan
 * location marker hovering above. Everything is tall so it reads ABOVE the
 * centered glass content panel; the camera banks left before reaching the
 * central jet/marker, so the x≈0 axis stays clear for the flythrough.
 */
function buildGrandFinale({ track, plain, lit, loadImage }: BuildCtx): Animated {
  const group = new THREE.Group();
  group.position.set(0, 0, -64);

  // Great reflecting lake + stone rim.
  const lakeMat = plain({
    color: 0x2f8fd0,
    roughness: 0.2,
    metalness: 0,
    transparent: true,
    opacity: 0.9,
  });
  lakeMat.emissive = new THREE.Color(0x1c4a6b);
  lakeMat.emissiveIntensity = 0.25;
  const lake = new THREE.Mesh(track.geo(new THREE.CircleGeometry(17, 56)), lakeMat);
  lake.rotation.x = -Math.PI / 2;
  lake.position.y = 0.1;
  group.add(lake);
  const rim = new THREE.Mesh(
    track.geo(new THREE.TorusGeometry(17, 0.6, 10, 64)),
    plain({ color: 0xd8cbb0, roughness: 0.9 })
  );
  rim.rotation.x = -Math.PI / 2;
  rim.position.y = 0.2;
  group.add(rim);

  // Fountain show: an outer + inner ring of jets and a tall central jet. Each
  // jet is a cylinder whose height pulses on a phase offset (a "wave").
  const jetMat = lit({ color: 0xbfe8ff, roughness: 0.2, transparent: true, opacity: 0.8 }, 0.85);
  const jetGeo = track.geo(new THREE.CylinderGeometry(0.18, 0.28, 1, 8));
  interface Jet {
    mesh: THREE.Mesh;
    phase: number;
    max: number;
  }
  const jets: Jet[] = [];
  const addJet = (x: number, z: number, phase: number, max: number) => {
    const jet = new THREE.Mesh(jetGeo, jetMat);
    jet.position.set(x, 0, z);
    group.add(jet);
    jets.push({ mesh: jet, phase, max });
  };
  for (let i = 0; i < 16; i++) {
    const a = (i / 16) * Math.PI * 2;
    addJet(Math.cos(a) * 10.5, Math.sin(a) * 10.5, i * 0.5, 7);
  }
  for (let i = 0; i < 10; i++) {
    const a = (i / 10) * Math.PI * 2 + 0.3;
    addJet(Math.cos(a) * 5.5, Math.sin(a) * 5.5, i * 0.7 + 1, 5);
  }
  const central = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(0.4, 0.6, 1, 12)), jetMat);
  group.add(central);
  jets.push({ mesh: central, phase: 0, max: 16 });

  // Snow-capped waterfall mountain behind the lake.
  const mtn = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(20, 44, 7)),
    plain({ color: 0x8a9bb0, roughness: 1 })
  );
  mtn.position.set(0, 22, -22);
  mtn.castShadow = true;
  group.add(mtn);
  const cap = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(8, 14, 7)),
    plain({ color: 0xf2f6ff, roughness: 0.9 })
  );
  cap.position.set(0, 37, -22);
  group.add(cap);
  const fallTex = track.tex(makeWaterfallTexture());
  fallTex.repeat.set(1, 4);
  const fallMat = lit(
    {
      map: fallTex,
      color: 0xffffff,
      transparent: true,
      opacity: 0.85,
      roughness: 0.2,
      side: THREE.DoubleSide,
    },
    0.5
  );
  const fall = new THREE.Mesh(track.geo(new THREE.PlaneGeometry(3.4, 30)), fallMat);
  fall.position.set(0, 15, -12.4);
  group.add(fall);
  const splash = new THREE.Mesh(
    track.geo(new THREE.CircleGeometry(3, 24)),
    lit({ color: 0xbfe8ff, roughness: 0.2, transparent: true, opacity: 0.7 }, 0.4)
  );
  splash.rotation.x = -Math.PI / 2;
  splash.position.set(0, 0.18, -12);
  group.add(splash);

  // Giant glowing park.fan marker crowning the mountain peak — high against the
  // sky so it never clips into geometry or the camera path, and reads above the
  // glass panel. Faces the approach (+z); a gentle sway keeps it lively.
  const markerTex = loadImage('/logo-dark.png'); // 569×683 pin marker
  const markerH = 13;
  const marker = new THREE.Mesh(
    track.geo(new THREE.PlaneGeometry((markerH * 569) / 683, markerH)),
    track.mat(
      new THREE.MeshBasicMaterial({
        map: markerTex,
        transparent: true,
        toneMapped: false,
        side: THREE.DoubleSide,
      })
    )
  );
  const markerY = 54;
  marker.position.set(0, markerY, -22); // above the peak (mountain is at z=-22 local)
  group.add(marker);
  const halo = new THREE.Mesh(
    track.geo(new THREE.CircleGeometry(8, 32)),
    lit({ color: 0x5db8ff, transparent: true, opacity: 0.2 }, 1.2)
  );
  halo.position.set(0, markerY + 0.5, -22.3);
  group.add(halo);

  return {
    group,
    update: (elapsed) => {
      for (const j of jets) {
        const h = (Math.sin(elapsed * 1.6 + j.phase) * 0.5 + 0.5) * j.max + 0.5;
        j.mesh.scale.y = h;
        j.mesh.position.y = h / 2;
      }
      fallTex.offset.y = -elapsed * 0.6;
      marker.position.y = markerY + Math.sin(elapsed * 0.8) * 0.8;
      marker.rotation.y = Math.sin(elapsed * 0.3) * 0.35;
      halo.position.y = marker.position.y + 0.5;
    },
  };
}

/**
 * Classic RCT park dressing: benches, litter bins, directional signposts and
 * bushes placed around the plaza ring and paths (kept off the central x≈0
 * flight axis so the gate flythrough stays clear).
 */
function buildStreetProps({ track, plain, lit }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  const woodMat = plain({ color: 0x9c6b3f, roughness: 0.85 });
  const metalMat = plain({ color: 0x39414f, metalness: 0.4, roughness: 0.5 });
  const bushMat = plain({ color: 0x4aa34f, roughness: 1 });

  const seatGeo = track.geo(new THREE.BoxGeometry(1.6, 0.12, 0.5));
  const backGeo = track.geo(new THREE.BoxGeometry(1.6, 0.45, 0.1));
  const benchLegGeo = track.geo(new THREE.BoxGeometry(0.12, 0.5, 0.5));
  const makeBench = (x: number, z: number, rot: number) => {
    const b = new THREE.Group();
    const seat = new THREE.Mesh(seatGeo, woodMat);
    seat.position.y = 0.5;
    seat.castShadow = true;
    b.add(seat);
    const back = new THREE.Mesh(backGeo, woodMat);
    back.position.set(0, 0.73, -0.2);
    b.add(back);
    for (const lx of [-0.7, 0.7]) {
      const leg = new THREE.Mesh(benchLegGeo, metalMat);
      leg.position.set(lx, 0.25, 0);
      b.add(leg);
    }
    b.position.set(x, 0, z);
    b.rotation.y = rot;
    group.add(b);
  };

  const binGeo = track.geo(new THREE.CylinderGeometry(0.25, 0.22, 0.7, 12));
  const makeBin = (x: number, z: number) => {
    const bin = new THREE.Mesh(binGeo, metalMat);
    bin.position.set(x, 0.35, z);
    bin.castShadow = true;
    group.add(bin);
  };

  const signPostGeo = track.geo(new THREE.CylinderGeometry(0.08, 0.08, 2.4, 8));
  const armGeo = track.geo(new THREE.BoxGeometry(1.2, 0.4, 0.08));
  const makeSign = (x: number, z: number, rot: number) => {
    const s = new THREE.Group();
    const post = new THREE.Mesh(signPostGeo, woodMat);
    post.position.y = 1.2;
    post.castShadow = true;
    s.add(post);
    const a1 = new THREE.Mesh(armGeo, lit({ color: 0x5db8ff, roughness: 0.6 }, 0.3));
    a1.position.set(0.5, 2.0, 0);
    s.add(a1);
    const a2 = new THREE.Mesh(armGeo, lit({ color: 0xff9f43, roughness: 0.6 }, 0.3));
    a2.position.set(-0.5, 1.55, 0);
    s.add(a2);
    s.position.set(x, 0, z);
    s.rotation.y = rot;
    group.add(s);
  };

  const bushGeo = track.geo(new THREE.SphereGeometry(0.6, 10, 8));
  const makeBush = (x: number, z: number, sc: number) => {
    const bush = new THREE.Mesh(bushGeo, bushMat);
    bush.position.set(x, 0.4 * sc, z);
    bush.scale.setScalar(sc);
    group.add(bush);
  };

  const benchSpots: Array<[number, number, number]> = [
    [8, 7, -0.6],
    [-8, 7, 0.6],
    [7, -7, -2.4],
    [-7, -7, 2.4],
    [10.5, 1, -1.57],
    [-10.5, 1, 1.57],
  ];
  for (const [x, z, r] of benchSpots) makeBench(x, z, r);
  const binSpots: Array<[number, number]> = [
    [6.5, 8],
    [-6.5, 8],
    [9.5, -4],
    [-9.5, -4],
    [5.5, -8.5],
    [-5.5, -8.5],
  ];
  for (const [x, z] of binSpots) makeBin(x, z);
  const signSpots: Array<[number, number, number]> = [
    [6, 6, 0.4],
    [-6, 6, -0.4],
    [6, -6, 2.7],
    [-6, -6, -2.7],
  ];
  for (const [x, z, r] of signSpots) makeSign(x, z, r);
  for (let i = 0; i < 30; i++) {
    const ang = (i / 30) * Math.PI * 2;
    const r = 12.2 + (i % 3) * 0.8;
    makeBush(Math.cos(ang) * r, Math.sin(ang) * r, 0.7 + (i % 3) * 0.18);
  }

  return group;
}

/** Strings of colorful triangular pennants (bunting) over the side paths. */
function buildBunting({ track, lit }: BuildCtx): THREE.Group {
  const group = new THREE.Group();
  const ropeMat = track.mat(new THREE.MeshStandardMaterial({ color: 0x6b5a3a, roughness: 0.9 }));
  const postMat = track.mat(new THREE.MeshStandardMaterial({ color: 0x9c6b3f, roughness: 0.85 }));
  const postGeo = track.geo(new THREE.CylinderGeometry(0.08, 0.1, 4, 8));
  const flagGeo = track.geo(new THREE.ConeGeometry(0.22, 0.5, 3));
  const colors = [0xff5d6c, 0xffd166, 0x5db8ff, 0x8be04e, 0xb57bff];

  // Each string spans two posts. Kept on the sides (|x| large) to avoid the
  // central flight corridor.
  const strings: Array<[number, number, number, number]> = [
    [-14, 6, -22, 14],
    [14, 6, 22, 14],
    [-15, -6, -24, -14],
    [15, -6, 24, -14],
  ];
  for (const [x1, z1, x2, z2] of strings) {
    for (const [px, pz] of [
      [x1, z1],
      [x2, z2],
    ]) {
      const post = new THREE.Mesh(postGeo, postMat);
      post.position.set(px, 2, pz);
      post.castShadow = true;
      group.add(post);
    }
    const a = new THREE.Vector3(x1, 3.7, z1);
    const b = new THREE.Vector3(x2, 3.7, z2);
    const len = a.distanceTo(b);
    const rope = new THREE.Mesh(track.geo(new THREE.CylinderGeometry(0.03, 0.03, len, 5)), ropeMat);
    rope.position.copy(a).lerp(b, 0.5);
    rope.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), b.clone().sub(a).normalize());
    group.add(rope);
    const n = Math.max(4, Math.floor(len / 1.1));
    for (let i = 1; i < n; i++) {
      const p = a.clone().lerp(b, i / n);
      const flag = new THREE.Mesh(
        flagGeo,
        lit({ color: colors[i % colors.length], roughness: 0.6, side: THREE.DoubleSide }, 0.4)
      );
      flag.position.set(p.x, p.y - 0.35, p.z);
      group.add(flag);
    }
  }
  return group;
}

/** A drop-tower "Startflyer": a ring of seats hauled up a mast, then dropped. */
function buildDropTower({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const H = 27;
  const mast = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.55, 0.8, H, 8)),
    plain({ color: 0xff4d8d, metalness: 0.3, roughness: 0.5 })
  );
  mast.position.y = H / 2;
  mast.castShadow = true;
  group.add(mast);
  const top = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(1.4, 2.4, 8)),
    lit({ color: C.gold, roughness: 0.4 }, 0.5)
  );
  top.position.y = H + 1.2;
  group.add(top);

  const gondola = new THREE.Group();
  const hub = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(1, 1, 0.6, 12)),
    plain({ color: 0xdfe9ff, metalness: 0.3, roughness: 0.5 })
  );
  gondola.add(hub);
  const seatGeo = track.geo(new THREE.BoxGeometry(0.7, 0.7, 0.7));
  for (let i = 0; i < 8; i++) {
    const a = (i / 8) * Math.PI * 2;
    const seat = new THREE.Mesh(
      seatGeo,
      lit({ color: RIDE_COLORS[i % RIDE_COLORS.length], roughness: 0.5 }, 0.5)
    );
    seat.position.set(Math.cos(a) * 1.9, -0.2, Math.sin(a) * 1.9);
    seat.castShadow = true;
    gondola.add(seat);
  }
  group.add(gondola);

  return {
    group,
    update: (e) => {
      const t = (e * 0.4) % 1; // ride cycle: slow climb, brief hang, fast drop
      let h;
      if (t < 0.62) h = (t / 0.62) * (H - 4);
      else if (t < 0.7) h = H - 4;
      else h = (H - 4) * Math.max(0, 1 - (t - 0.7) / 0.1);
      gondola.position.y = 1.6 + h;
    },
  };
}

/** An observation tower: a rotating ring gondola slowly rising on a tall mast. */
function buildObservationTower({ track, plain, lit }: BuildCtx): Animated {
  const group = new THREE.Group();
  const H = 34;
  const mast = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(0.9, 1.4, H, 10)),
    plain({ color: 0xdfe9ff, metalness: 0.3, roughness: 0.5 })
  );
  mast.position.y = H / 2;
  mast.castShadow = true;
  group.add(mast);
  const spire = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(1.6, 3.5, 10)),
    lit({ color: C.gold, roughness: 0.4 }, 0.5)
  );
  spire.position.y = H + 1.7;
  group.add(spire);

  const gondola = new THREE.Group();
  const ring = new THREE.Mesh(
    track.geo(new THREE.CylinderGeometry(3, 3, 1.8, 22, 1, true)),
    lit(
      { color: 0x5db8ff, roughness: 0.4, transparent: true, opacity: 0.7, side: THREE.DoubleSide },
      0.45
    )
  );
  gondola.add(ring);
  const roof = new THREE.Mesh(
    track.geo(new THREE.ConeGeometry(3.5, 1.4, 22)),
    lit({ color: C.flagRed, roughness: 0.5 }, 0.45)
  );
  roof.position.y = 1.6;
  gondola.add(roof);
  group.add(gondola);

  return {
    group,
    update: (e) => {
      gondola.rotation.y = e * 0.35;
      gondola.position.y = 6 + (Math.sin(e * 0.18) * 0.5 + 0.5) * (H - 13);
    },
  };
}

function buildStars(track: Tracker): THREE.Points {
  const count = 280;
  const positions = new Float32Array(count * 3);
  for (let i = 0; i < count; i++) {
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.random() * Math.PI * 0.42;
    const r = 170;
    positions[i * 3] = Math.cos(theta) * Math.sin(phi) * r;
    positions[i * 3 + 1] = Math.cos(phi) * r * 0.7 + 14;
    positions[i * 3 + 2] = Math.sin(theta) * Math.sin(phi) * r - 30;
  }
  const geo = track.geo(new THREE.BufferGeometry());
  geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  const mat = track.mat(
    new THREE.PointsMaterial({
      color: 0xffffff,
      size: 1.1,
      sizeAttenuation: false,
      transparent: true,
      opacity: 0,
    })
  );
  const points = new THREE.Points(geo, mat);
  points.visible = false;
  return points;
}
