/**
 * Deterministic value noise. DOM-free, Babylon-free, allocation-free — the sim, the texture
 * generator and the showcase landscape all run through it, so it must stay importable on the
 * worker and under node's strip-only mode.
 *
 * `Math.random` is banned in `lib/game/**`; every value here is a pure function of its integer
 * lattice coordinates and a seed, which is also what lets a texture be regenerated byte-identically
 * after a reload instead of being cached.
 */

/** Hash of an integer lattice point to [0, 1). */
export function hash2(ix: number, iy: number, seed: number): number {
  let h = (Math.imul(ix, 374761393) + Math.imul(iy, 668265263) + Math.imul(seed, 1274126177)) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  h ^= h >>> 16;
  return (h >>> 0) / 4294967296;
}

/**
 * Value noise with a smoothstep interpolant. `wrap > 0` folds the lattice, which is what makes a
 * generated texture tile: at frequency f over a unit square, wrapping at f makes the left and
 * right edges read the same lattice column.
 */
export function valueNoise(x: number, y: number, wrap: number, seed: number): number {
  const xi = Math.floor(x);
  const yi = Math.floor(y);
  const xf = x - xi;
  const yf = y - yi;
  const u = xf * xf * (3 - 2 * xf);
  const v = yf * yf * (3 - 2 * yf);
  const x0 = wrap > 0 ? ((xi % wrap) + wrap) % wrap : xi;
  const y0 = wrap > 0 ? ((yi % wrap) + wrap) % wrap : yi;
  const x1 = wrap > 0 ? (x0 + 1) % wrap : xi + 1;
  const y1 = wrap > 0 ? (y0 + 1) % wrap : yi + 1;
  const a = hash2(x0, y0, seed);
  const b = hash2(x1, y0, seed);
  const c = hash2(x0, y1, seed);
  const d = hash2(x1, y1, seed);
  const top = a + (b - a) * u;
  return top + (c + (d - c) * u - top) * v;
}

/**
 * Tileable fractal noise over the unit square. `baseFreq` must be an integer or the wrap is not
 * on a lattice line and the seam comes back.
 */
export function tileableFbm(
  u: number,
  v: number,
  baseFreq: number,
  octaves: number,
  seed: number,
  gain = 0.5
): number {
  let f = baseFreq;
  let amp = 1;
  let sum = 0;
  let norm = 0;
  for (let o = 0; o < octaves; o++) {
    sum += amp * valueNoise(u * f, v * f, f, seed + o * 1013);
    norm += amp;
    amp *= gain;
    f *= 2;
  }
  return sum / norm;
}

/** Fractal noise in world metres; no wrap, for landscapes that are never tiled. */
export function fbm2(
  x: number,
  y: number,
  frequency: number,
  octaves: number,
  seed: number,
  gain = 0.5
): number {
  let f = frequency;
  let amp = 1;
  let sum = 0;
  let norm = 0;
  for (let o = 0; o < octaves; o++) {
    sum += amp * valueNoise(x * f, y * f, 0, seed + o * 7919);
    norm += amp;
    amp *= gain;
    f *= 2;
  }
  return sum / norm;
}

/**
 * Ridged noise — the |2n-1| fold that gives eroded rock its creases. Squaring the result sharpens
 * the ridges; without it the fold reads as soft dunes, which is what sand wants and rock does not.
 */
export function ridgedFbm(
  u: number,
  v: number,
  baseFreq: number,
  octaves: number,
  seed: number
): number {
  let f = baseFreq;
  let amp = 1;
  let sum = 0;
  let norm = 0;
  for (let o = 0; o < octaves; o++) {
    const n = 1 - Math.abs(valueNoise(u * f, v * f, f, seed + o * 3571) * 2 - 1);
    sum += amp * n * n;
    norm += amp;
    amp *= 0.5;
    f *= 2;
  }
  return sum / norm;
}

export function smoothstep(edge0: number, edge1: number, x: number): number {
  const t = Math.max(0, Math.min(1, (x - edge0) / (edge1 - edge0 || 1e-6)));
  return t * t * (3 - 2 * t);
}

export function mix(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

export function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}
