packages:
  - .
overrides:
  postcss: ^8.5.10
onlyBuiltDependencies:
  - '@swc/core'
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  sharp: false
  unrs-resolver: false
