/**
 * `core-classic` — the default vocabulary.
 *
 * Everything here is a **declaration**. Nothing in this file is imported by a module; the registry
 * reads it, validates it and hands definitions back by id. Adding a ride, a shop, a need or a
 * scenery prop is an entry in this array and nothing else, which is the claim CONTENT_PACKS.md
 * makes and this pack is half the proof of.
 */

export const coreClassicPack = {
  id: 'core-classic',
  version: '1.0.0',
  name: { en: 'Classic Park', de: 'Klassischer Park' },
  requires: { engine: '>=1.0.0', packs: [] },
  license: 'CC0-1.0',
  definitions: [
    // -- needs ------------------------------------------------------------
    // A need is a declaration, which is the answer to "can a pack add a guest need": yes.
    {
      id: 'cc.hunger',
      kind: 'need',
      name: { en: 'Hunger', de: 'Hunger' },
      decayPerHour: 26,
      moodWeight: 1.2,
      urgentAt: 170,
      criticalAt: 225,
      thoughts: [{ en: 'I could eat.', de: 'Ich hätte Hunger.' }],
    },
    {
      id: 'cc.thirst',
      kind: 'need',
      name: { en: 'Thirst', de: 'Durst' },
      decayPerHour: 34,
      moodWeight: 1.1,
      urgentAt: 165,
      criticalAt: 220,
      thoughts: [{ en: 'I need a drink.', de: 'Ich bräuchte was zu trinken.' }],
    },
    {
      id: 'cc.toilet',
      kind: 'need',
      name: { en: 'Toilet', de: 'Toilette' },
      decayPerHour: 21,
      moodWeight: 1.6,
      urgentAt: 185,
      criticalAt: 235,
      thoughts: [{ en: 'Where are the toilets?', de: 'Wo sind hier die Toiletten?' }],
    },
    {
      id: 'cc.boredom',
      kind: 'need',
      name: { en: 'Boredom', de: 'Langeweile' },
      decayPerHour: 30,
      moodWeight: 1.4,
      urgentAt: 190,
      criticalAt: 240,
      thoughts: [{ en: 'I want to ride something.', de: 'Ich will endlich fahren.' }],
    },

    // -- themes -----------------------------------------------------------
    {
      id: 'cc.classic',
      kind: 'theme',
      name: { en: 'Classic', de: 'Klassisch' },
      palette: ['#E8603C', '#F2C14E', '#4E7A3C', '#B9B2A6', '#2F4858'],
      water: { absorptionHex: '#0E4B5A', scatterHex: '#7FD9D0', causticScale: 1 },
      fogDensity: 0.0012,
      foliage: ['cc.oak', 'cc.pine', 'cc.hedge'],
      props: ['cc.bench', 'cc.bin', 'cc.lamp', 'cc.planter'],
      pathStyle: 'cc.concrete',
      uiAccentHex: '#E8603C',
    },

    // -- path styles ------------------------------------------------------
    {
      id: 'cc.concrete',
      kind: 'path-style',
      name: { en: 'Concrete', de: 'Beton' },
      surface: { material: 'cc.concrete-mat', tileM: 2 },
      kerb: true,
      railing: null,
    },
    {
      id: 'cc.boardwalk',
      kind: 'path-style',
      name: { en: 'Boardwalk', de: 'Holzsteg' },
      surface: { material: 'cc.timber-mat', tileM: 1.2 },
      kerb: false,
      railing: 'cc.rail-timber',
    },

    // -- flat rides -------------------------------------------------------
    {
      id: 'cc.chair-swing',
      kind: 'flat-ride',
      name: { en: 'Chair Swing', de: 'Kettenkarussell' },
      tags: ['gentle', 'family'],
      theme: 'cc.classic',
      cost: { build: 78_000_00, runPerHour: 210_00 },
      model: 'core-classic/rides/chair-swing.glb',
      footprint: { w: 14, d: 14, clearanceY: 14 },
      capacity: 24,
      cycleSeconds: 90,
      loadSeconds: 45,
      riders: { minHeightCm: 110, maxHeightCm: 210, seats: 24 },
      rig: {
        joints: [
          { node: 'Hub', track: 'spin', axis: 'y', kind: 'rotate' },
          { node: 'Boom', track: 'lift', axis: 'x', kind: 'rotate' },
        ],
        tracks: {
          spin: { loop: true, keys: [[0, 0], [8, 360]], ease: 'linear' },
          lift: { loop: false, keys: [[0, 0], [12, 26], [70, 26], [85, 0]], ease: 'inOutSine' },
        },
        riderNodes: 'Seat_*',
      },
      ratings: { excitement: 4.6, fear: 2.1, nausea: 3.4 },
      power: { kw: 45 },
    },
    {
      id: 'cc.carousel',
      kind: 'flat-ride',
      name: { en: 'Carousel', de: 'Karussell' },
      tags: ['gentle', 'children'],
      theme: 'cc.classic',
      cost: { build: 42_000_00, runPerHour: 120_00 },
      model: 'core-classic/rides/carousel.glb',
      footprint: { w: 12, d: 12, clearanceY: 8 },
      capacity: 30,
      cycleSeconds: 75,
      loadSeconds: 50,
      riders: { minHeightCm: 0, maxHeightCm: 210, seats: 30 },
      rig: {
        joints: [{ node: 'Platform', track: 'spin', axis: 'y', kind: 'rotate' }],
        tracks: { spin: { loop: true, keys: [[0, 0], [12, 360]], ease: 'linear' } },
        riderNodes: 'Horse_*',
      },
      ratings: { excitement: 2.4, fear: 0.5, nausea: 1.2 },
      power: { kw: 22 },
    },
    {
      id: 'cc.drop-tower',
      kind: 'flat-ride',
      name: { en: 'Drop Tower', de: 'Freifallturm' },
      tags: ['thrill'],
      theme: 'cc.classic',
      cost: { build: 195_000_00, runPerHour: 420_00 },
      model: 'core-classic/rides/drop-tower.glb',
      footprint: { w: 10, d: 10, clearanceY: 62 },
      capacity: 16,
      cycleSeconds: 55,
      loadSeconds: 60,
      riders: { minHeightCm: 130, maxHeightCm: 205, seats: 16 },
      rig: {
        joints: [{ node: 'Carriage', track: 'height', axis: 'y', kind: 'translate' }],
        tracks: {
          height: {
            loop: false,
            keys: [[0, 0], [22, 52], [30, 52], [32.4, 2], [34, 0]],
            ease: 'inOutCubic',
          },
        },
        riderNodes: 'Seat_*',
      },
      ratings: { excitement: 7.1, fear: 7.8, nausea: 4.2 },
      power: { kw: 160 },
    },
    {
      id: 'cc.teacups',
      kind: 'flat-ride',
      name: { en: 'Spinning Cups', de: 'Tassenfahrt' },
      tags: ['family', 'spinner'],
      theme: 'cc.classic',
      cost: { build: 56_000_00, runPerHour: 160_00 },
      model: 'core-classic/rides/teacups.glb',
      footprint: { w: 13, d: 13, clearanceY: 7 },
      capacity: 20,
      cycleSeconds: 80,
      loadSeconds: 40,
      riders: { minHeightCm: 90, maxHeightCm: 210, seats: 20 },
      rig: {
        joints: [
          { node: 'Platform', track: 'spin', axis: 'y', kind: 'rotate' },
          { node: 'Cup_*', track: 'cupSpin', axis: 'y', kind: 'rotate' },
        ],
        tracks: {
          spin: { loop: true, keys: [[0, 0], [10, 360]], ease: 'linear' },
          cupSpin: { loop: true, keys: [[0, 0], [4, 360]], ease: 'linear' },
        },
        riderNodes: 'Cup_*',
      },
      ratings: { excitement: 3.8, fear: 1.2, nausea: 6.4 },
      power: { kw: 30 },
    },

    // -- coasters ---------------------------------------------------------
    {
      id: 'cc.steel-looper',
      kind: 'coaster',
      name: { en: 'Steel Looper', de: 'Stahl-Looping' },
      tags: ['thrill', 'steel'],
      theme: 'cc.classic',
      cost: { build: 640_000_00, runPerHour: 980_00 },
      track: { gauge: 1.6, railRadius: 0.07, tieSpacing: 1.2, spineProfile: 'box', material: 'cc.track-steel' },
      car: { seatsPerCar: 4, carsPerTrain: [4, 5, 6, 7], mass: 1250, lengthM: 3.2 },
      physics: { frictionRolling: 0.0035, dragK: 0.0021, liftSpeed: 4, launchSpeed: null },
      pieces: ['straight', 'curve-l', 'curve-r', 'hill', 'drop', 'loop', 'corkscrew', 'banked-l', 'banked-r', 'station', 'lift-chain', 'brake', 'block-brake'],
      supports: { style: 'cc.support-steel', maxSpan: 9, footingRadius: 0.9 },
      limits: { maxGVertical: 6, maxGLateral: 2.5, minRadius: 6 },
    },
    {
      id: 'cc.wooden-classic',
      kind: 'coaster',
      name: { en: 'Wooden Classic', de: 'Holzachterbahn' },
      tags: ['thrill', 'wooden', 'airtime'],
      theme: 'cc.classic',
      cost: { build: 520_000_00, runPerHour: 860_00 },
      track: { gauge: 1.45, railRadius: 0.05, tieSpacing: 0.6, spineProfile: 'wooden', material: 'cc.track-timber' },
      car: { seatsPerCar: 4, carsPerTrain: [5, 6, 7], mass: 1400, lengthM: 3 },
      physics: { frictionRolling: 0.0052, dragK: 0.0025, liftSpeed: 3.6, launchSpeed: null },
      pieces: ['straight', 'curve-l', 'curve-r', 'hill', 'drop', 'banked-l', 'banked-r', 'station', 'lift-chain', 'brake', 'block-brake'],
      supports: { style: 'cc.support-timber', maxSpan: 5, footingRadius: 1.1 },
      limits: { maxGVertical: 4.5, maxGLateral: 1.8, minRadius: 9 },
    },
    {
      id: 'cc.family-coaster',
      kind: 'coaster',
      name: { en: 'Family Coaster', de: 'Familienachterbahn' },
      tags: ['family', 'steel'],
      theme: 'cc.classic',
      cost: { build: 240_000_00, runPerHour: 420_00 },
      track: { gauge: 1.2, railRadius: 0.05, tieSpacing: 1.4, spineProfile: 'tube', material: 'cc.track-steel' },
      car: { seatsPerCar: 4, carsPerTrain: [3, 4, 5], mass: 850, lengthM: 2.6 },
      physics: { frictionRolling: 0.004, dragK: 0.0019, liftSpeed: 3.2, launchSpeed: null },
      pieces: ['straight', 'curve-l', 'curve-r', 'hill', 'drop', 'banked-l', 'banked-r', 'station', 'lift-chain', 'brake'],
      supports: { style: 'cc.support-steel', maxSpan: 8, footingRadius: 0.7 },
      limits: { maxGVertical: 3.5, maxGLateral: 1.5, minRadius: 8 },
    },

    // -- flume ------------------------------------------------------------
    {
      id: 'cc.log-flume',
      kind: 'flume',
      name: { en: 'Log Flume', de: 'Wildwasserbahn' },
      tags: ['water', 'family'],
      theme: 'cc.classic',
      cost: { build: 380_000_00, runPerHour: 520_00 },
      track: { gauge: 1.8, railRadius: 0.02, tieSpacing: 2, spineProfile: 'box', material: 'cc.flume-trough' },
      car: { seatsPerCar: 4, carsPerTrain: [1], mass: 700, lengthM: 4 },
      physics: { frictionRolling: 0.012, dragK: 0.006, liftSpeed: 2.4, launchSpeed: null },
      pieces: ['straight', 'curve-l', 'curve-r', 'drop', 'station', 'lift-chain', 'brake'],
      supports: { style: 'cc.support-timber', maxSpan: 6, footingRadius: 1 },
      limits: { maxGVertical: 3, maxGLateral: 1.2, minRadius: 7 },
    },

    // -- shops ------------------------------------------------------------
    {
      id: 'cc.burger-stand',
      kind: 'shop',
      name: { en: 'Burger Stand', de: 'Burgerbude' },
      category: 'food',
      theme: 'cc.classic',
      cost: { build: 34_000_00, runPerHour: 60_00 },
      model: 'core-classic/shops/burger-stand.glb',
      footprint: { w: 5, d: 4, clearanceY: 5 },
      satisfies: [{ need: 'cc.hunger', amount: 165 }],
      sells: [{ sku: 'burger', cost: 180, defaultPrice: 640 }],
      staffSlots: 1,
      queueCapacity: 14,
      power: { kw: 8 },
    },
    {
      id: 'cc.drinks-kiosk',
      kind: 'shop',
      name: { en: 'Drinks Kiosk', de: 'Getränkekiosk' },
      category: 'drink',
      theme: 'cc.classic',
      cost: { build: 24_000_00, runPerHour: 40_00 },
      model: 'core-classic/shops/drinks-kiosk.glb',
      footprint: { w: 4, d: 3.5, clearanceY: 4.5 },
      satisfies: [{ need: 'cc.thirst', amount: 190 }],
      sells: [{ sku: 'soda', cost: 60, defaultPrice: 290 }],
      staffSlots: 1,
      queueCapacity: 12,
      power: { kw: 5 },
    },
    {
      id: 'cc.toilets',
      kind: 'shop',
      name: { en: 'Toilets', de: 'Toiletten' },
      category: 'toilet',
      theme: 'cc.classic',
      cost: { build: 46_000_00, runPerHour: 55_00 },
      model: 'core-classic/shops/toilets.glb',
      footprint: { w: 8, d: 5, clearanceY: 4 },
      satisfies: [{ need: 'cc.toilet', amount: 255 }],
      sells: [],
      staffSlots: 0,
      queueCapacity: 16,
      power: { kw: 3 },
    },
    {
      id: 'cc.souvenirs',
      kind: 'shop',
      name: { en: 'Souvenir Shop', de: 'Souvenirladen' },
      category: 'souvenir',
      theme: 'cc.classic',
      cost: { build: 52_000_00, runPerHour: 70_00 },
      model: 'core-classic/shops/souvenirs.glb',
      footprint: { w: 7, d: 5, clearanceY: 5 },
      satisfies: [],
      sells: [{ sku: 'plush', cost: 420, defaultPrice: 1490 }],
      staffSlots: 1,
      queueCapacity: 10,
      power: { kw: 4 },
    },
    {
      id: 'cc.first-aid',
      kind: 'shop',
      name: { en: 'First Aid', de: 'Sanitätsstation' },
      category: 'firstAid',
      theme: 'cc.classic',
      cost: { build: 38_000_00, runPerHour: 90_00 },
      model: 'core-classic/shops/first-aid.glb',
      footprint: { w: 6, d: 5, clearanceY: 4 },
      satisfies: [],
      sells: [],
      staffSlots: 1,
      queueCapacity: 6,
      power: { kw: 6 },
    },
    {
      id: 'cc.changing-rooms',
      kind: 'shop',
      name: { en: 'Changing Rooms', de: 'Umkleiden' },
      category: 'changing',
      theme: 'cc.classic',
      cost: { build: 64_000_00, runPerHour: 80_00 },
      model: 'core-classic/shops/changing.glb',
      footprint: { w: 10, d: 6, clearanceY: 4 },
      satisfies: [],
      sells: [],
      staffSlots: 0,
      queueCapacity: 20,
      power: { kw: 7 },
    },
    {
      id: 'cc.atm',
      kind: 'shop',
      name: { en: 'Cash Machine', de: 'Geldautomat' },
      category: 'atm',
      theme: 'cc.classic',
      cost: { build: 18_000_00, runPerHour: 20_00 },
      model: 'core-classic/shops/atm.glb',
      footprint: { w: 2, d: 1.4, clearanceY: 2.6 },
      satisfies: [],
      sells: [],
      staffSlots: 0,
      queueCapacity: 6,
      power: { kw: 1 },
    },

    // -- scenery ----------------------------------------------------------
    { id: 'cc.oak', kind: 'scenery', name: { en: 'Oak', de: 'Eiche' }, procedural: 'tree', heightM: 11, cost: { build: 900_00, runPerHour: 0 }, scatter: { minScale: 0.75, maxScale: 1.35 } },
    { id: 'cc.pine', kind: 'scenery', name: { en: 'Pine', de: 'Kiefer' }, procedural: 'tree', heightM: 14, cost: { build: 850_00, runPerHour: 0 }, scatter: { minScale: 0.8, maxScale: 1.4 } },
    { id: 'cc.hedge', kind: 'scenery', name: { en: 'Hedge', de: 'Hecke' }, procedural: 'bush', heightM: 1.4, cost: { build: 320_00, runPerHour: 0 }, scatter: { minScale: 0.9, maxScale: 1.2 } },
    { id: 'cc.bench', kind: 'scenery', name: { en: 'Bench', de: 'Bank' }, procedural: 'bench', heightM: 0.85, cost: { build: 480_00, runPerHour: 0 } },
    { id: 'cc.bin', kind: 'scenery', name: { en: 'Litter Bin', de: 'Mülleimer' }, procedural: 'bin', heightM: 0.95, cost: { build: 260_00, runPerHour: 0 } },
    { id: 'cc.lamp', kind: 'scenery', name: { en: 'Lamp Post', de: 'Laterne' }, procedural: 'lamp', heightM: 4.2, cost: { build: 640_00, runPerHour: 0 }, lightAtNight: { colorHex: '#FFD9A0', intensity: 1.4, rangeM: 12 } },
    { id: 'cc.planter', kind: 'scenery', name: { en: 'Planter', de: 'Pflanzkübel' }, procedural: 'planter', heightM: 1.1, cost: { build: 380_00, runPerHour: 0 }, tintable: true },
    { id: 'cc.rock', kind: 'scenery', name: { en: 'Boulder', de: 'Felsblock' }, procedural: 'rock', heightM: 2.4, cost: { build: 540_00, runPerHour: 0 }, scatter: { minScale: 0.6, maxScale: 2.2 } },
    { id: 'cc.fence', kind: 'scenery', name: { en: 'Fence', de: 'Zaun' }, procedural: 'fence', heightM: 1.1, cost: { build: 180_00, runPerHour: 0 } },
    { id: 'cc.flag', kind: 'scenery', name: { en: 'Flag', de: 'Fahne' }, procedural: 'flag', heightM: 6.5, cost: { build: 420_00, runPerHour: 0 }, tintable: true },

    // -- scenarios --------------------------------------------------------
    {
      id: 'cc.sandbox',
      kind: 'scenario',
      name: { en: 'Sandbox', de: 'Sandkasten' },
      description: { en: 'No objectives, unlimited money.', de: 'Keine Ziele, unbegrenztes Geld.' },
      start: { cash: 5_000_000_00, loan: 0, loanLimit: 0, day: 0, season: 1, unlocked: ['*'], terrainSize: 256 },
      objectives: [],
      fail: [],
    },
    {
      id: 'cc.first-season',
      kind: 'scenario',
      name: { en: 'First Season', de: 'Erste Saison' },
      description: {
        en: '900 guests and a park rating of 700 by day 120, without going bankrupt.',
        de: '900 Gäste und Parkwertung 700 bis Tag 120, ohne pleite zu gehen.',
      },
      start: { cash: 250_000_00, loan: 100_000_00, loanLimit: 400_000_00, day: 0, season: 0, unlocked: ['cc.carousel', 'cc.chair-swing', 'cc.teacups', 'cc.family-coaster', 'cc.*'], terrainSize: 192 },
      objectives: [
        { id: 'guests', type: 'guestsAtOnce', target: 900, byDay: 120 },
        { id: 'rating', type: 'parkRating', target: 700, byDay: 120 },
        { id: 'solvent', type: 'neverBankrupt' },
      ],
      fail: [{ type: 'bankrupt' }, { type: 'ratingBelow', value: 300, forDays: 21 }],
    },
    {
      id: 'cc.thrill-seekers',
      kind: 'scenario',
      name: { en: 'Thrill Seekers', de: 'Nervenkitzel' },
      description: {
        en: 'Build a coaster rated 8.0 excitement or better, and keep 1,500 guests happy.',
        de: 'Bau eine Achterbahn mit Nervenkitzel 8,0 und halte 1.500 Gäste bei Laune.',
      },
      start: { cash: 900_000_00, loan: 0, loanLimit: 1_200_000_00, day: 0, season: 1, unlocked: ['*'], terrainSize: 256 },
      objectives: [
        { id: 'coaster', type: 'coasterExcitement', target: 8, byDay: 180 },
        { id: 'guests', type: 'guestsAtOnce', target: 1500, byDay: 180 },
      ],
      fail: [{ type: 'bankrupt' }],
    },
  ],
  strings: {
    en: { 'pack.core-classic': 'Classic Park' },
    de: { 'pack.core-classic': 'Klassischer Park' },
  },
} as const;
