import 'server-only';
import type { BlogImage } from './types';
import { BLOG_GALLERY_FOLDERS } from './manifest';

/**
 * Return the images registered in the build-time manifest for the given
 * folder under /public. The manifest is generated by
 * scripts/generate-blog-manifest.mjs as part of prebuild and includes
 * captions.json overrides where present.
 *
 * Returns an empty array when the folder is unknown — useful for blog
 * post authors who reference a folder that has been renamed or deleted.
 */
export function listFolderImages(folder: string): BlogImage[] {
  const normalized = folder.startsWith('/') ? folder : `/${folder}`;
  return BLOG_GALLERY_FOLDERS[normalized] ?? BLOG_GALLERY_FOLDERS[`${normalized}/`] ?? [];
}

/**
 * Resolve a polymorphic gallery declaration from frontmatter into BlogImage[].
 *
 * Accepts:
 *   - Array of BlogImage objects
 *   - String — interpreted as a folder path under /public
 *   - Object with { folder: '...' }
 */
export function resolveGallery(
  input: BlogImage[] | string | { folder: string } | undefined
): BlogImage[] {
  if (!input) return [];
  if (Array.isArray(input)) return input;
  if (typeof input === 'string') return listFolderImages(input);
  if (typeof input === 'object' && 'folder' in input && typeof input.folder === 'string') {
    return listFolderImages(input.folder);
  }
  return [];
}
