import type { Metadata, Viewport } from 'next';
import './globals.css';

// The icon set is generated by `pnpm generate:icons`, never hand-exported. `app/favicon.ico`
// comes from the file convention and is what Google reads; only what the convention cannot
// express is declared here. This object lives here and nowhere else: the nearest segment that
// declares `icons` replaces the whole object. See
// docs/rules/the-favicon-is-generated-from-two-sources-and-it-carries-no.md.
export const metadata: Metadata = {
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
    apple: '/apple-touch-icon.png',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // One value, not a pair keyed off `prefers-color-scheme`: the theme does not follow the OS
  // (dark by default, light on request). This is `--background` in the dark theme.
  themeColor: '#0a0a0a',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

/** Passes its children through: `<html>` and `<body>` render in [locale]/layout.tsx, for `lang`. */
export default function RootLayout({ children }: RootLayoutProps) {
  return children;
}
