import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'park.fan – Theme Park Wait Times',
    short_name: 'park.fan',
    description:
      'Live wait times, AI crowd predictions, and crowd calendars for 200+ theme parks worldwide.',
    start_url: '/',
    display: 'standalone',
    background_color: '#293B47',
    theme_color: '#2191D3',
    // Generated by `pnpm generate:icons`. The `maskable` entry is a separate file rather than a
    // second `purpose` on the 512: an adaptive launcher may keep only the central 80 % circle,
    // which would cut the pin's tip off, so that one is drawn with more room around the mark.
    icons: [
      {
        src: '/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
