import type { MetadataRoute } from 'next';
import { getGeoStructure } from '@/lib/api/discovery';
import { locales } from '@/i18n/config';

const BASE_URL = 'https://park.fan';

// 1h revalidation — primary sitemap (home+parks) needs hourly freshness.
// Attractions and geo sitemaps share this TTL; getGeoStructure(86400) provides
// its own 24h fetch cache so their content only changes when the geo data does.
export const revalidate = 3600;

/**
 * Three logical sitemaps exposed via Next.js generateSitemaps():
 *   /sitemap/0.xml → home + all park pages  (priority 1.0)
 *   /sitemap/1.xml → all attraction pages   (priority 0.7)
 *   /sitemap/2.xml → geo hub pages          (priority 0.6–0.8)
 *   /sitemap.xml   → sitemap index (auto-generated by Next.js)
 * IDs must be numeric — Next.js ignores string IDs and returns 404 for /sitemap.xml.
 */
export function generateSitemaps() {
  return [{ id: 0 }, { id: 1 }, { id: 2 }];
}

export default async function sitemap({ id }: { id: number }): Promise<MetadataRoute.Sitemap> {
  switch (id) {
    case 0:
      return generateHomeParksSitemap();
    case 1:
      return generateAttractionsSitemap();
    case 2:
      return generateGeoSitemap();
    default:
      return [];
  }
}

// ── home + parks ────────────────────────────────────────────────────────────

async function generateHomeParksSitemap(): Promise<MetadataRoute.Sitemap> {
  const routes: MetadataRoute.Sitemap = [];

  // Root x-default
  routes.push({ url: BASE_URL, lastModified: new Date(), changeFrequency: 'daily', priority: 1 });

  // Locale home pages
  for (const locale of locales) {
    routes.push({
      url: `${BASE_URL}/${locale}`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    });
  }

  // Parks overview per locale
  for (const locale of locales) {
    routes.push({
      url: `${BASE_URL}/${locale}/parks`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    });
  }

  // Individual park pages
  try {
    const geo = await getGeoStructure(86400);

    for (const continent of geo.continents) {
      for (const country of continent.countries) {
        for (const city of country.cities) {
          for (const park of city.parks) {
            const parkPath = `/parks/${continent.slug}/${country.slug}/${city.slug}/${park.slug}`;
            for (const locale of locales) {
              routes.push({
                url: `${BASE_URL}/${locale}${parkPath}`,
                lastModified: new Date(),
                changeFrequency: 'hourly',
                priority: 1,
              });
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('[sitemap home-parks] Failed to generate park entries:', error);
  }

  return routes;
}

// ── attractions ──────────────────────────────────────────────────────────────

async function generateAttractionsSitemap(): Promise<MetadataRoute.Sitemap> {
  const routes: MetadataRoute.Sitemap = [];

  try {
    const geo = await getGeoStructure(86400);

    for (const continent of geo.continents) {
      for (const country of continent.countries) {
        for (const city of country.cities) {
          for (const park of city.parks) {
            const parkPath = `/parks/${continent.slug}/${country.slug}/${city.slug}/${park.slug}`;

            for (const attraction of park.attractions) {
              // Skip variant slugs (e.g. "coaster-2") — those are noindex pages
              // pointing to the canonical base slug, no sitemap entry needed.
              if (/^.+-\d+$/.test(attraction.slug)) continue;

              for (const locale of locales) {
                routes.push({
                  url: `${BASE_URL}/${locale}${parkPath}/${attraction.slug}`,
                  lastModified: new Date(),
                  changeFrequency: 'hourly',
                  priority: 0.7,
                });
              }
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('[sitemap attractions] Failed to generate attraction entries:', error);
  }

  return routes;
}

// ── geo hub pages ────────────────────────────────────────────────────────────

async function generateGeoSitemap(): Promise<MetadataRoute.Sitemap> {
  const routes: MetadataRoute.Sitemap = [];

  try {
    const geo = await getGeoStructure(86400);

    for (const continent of geo.continents) {
      for (const locale of locales) {
        routes.push({
          url: `${BASE_URL}/${locale}/parks/${continent.slug}`,
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
        });
      }

      for (const country of continent.countries) {
        for (const locale of locales) {
          routes.push({
            url: `${BASE_URL}/${locale}/parks/${continent.slug}/${country.slug}`,
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.7,
          });
        }

        for (const city of country.cities) {
          // Single-park cities redirect to the park page — skip
          if (city.parks.length <= 1) continue;

          for (const locale of locales) {
            routes.push({
              url: `${BASE_URL}/${locale}/parks/${continent.slug}/${country.slug}/${city.slug}`,
              lastModified: new Date(),
              changeFrequency: 'weekly',
              priority: 0.6,
            });
          }
        }
      }
    }
  } catch (error) {
    console.error('[sitemap geo] Failed to generate geo entries:', error);
  }

  return routes;
}
