/**
 * Static demo fixtures for the weather card showcase on the /ui style guide.
 */
import type { WeatherDay } from '@/lib/api/types';

export const FORECAST_TEMPLATE: Omit<WeatherDay, 'date' | 'dataType'>[] = [
  {
    temperatureMax: '15',
    temperatureMin: '7',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 1,
    weatherDescription: 'Mainly clear',
    windSpeedMax: '10',
  },
  {
    temperatureMax: '12',
    temperatureMin: '6',
    precipitationSum: '3',
    rainSum: '3',
    snowfallSum: '0',
    weatherCode: 61,
    weatherDescription: 'Rain',
    windSpeedMax: '18',
  },
  {
    temperatureMax: '16',
    temperatureMin: '8',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 2,
    weatherDescription: 'Partly cloudy',
    windSpeedMax: '12',
  },
  {
    temperatureMax: '19',
    temperatureMin: '10',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 0,
    weatherDescription: 'Clear sky',
    windSpeedMax: '8',
  },
  {
    temperatureMax: '11',
    temperatureMin: '5',
    precipitationSum: '8',
    rainSum: '8',
    snowfallSum: '0',
    weatherCode: 63,
    weatherDescription: 'Moderate rain',
    windSpeedMax: '25',
  },
  {
    temperatureMax: '14',
    temperatureMin: '7',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 3,
    weatherDescription: 'Overcast',
    windSpeedMax: '15',
  },
  {
    temperatureMax: '17',
    temperatureMin: '9',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 1,
    weatherDescription: 'Mainly clear',
    windSpeedMax: '12',
  },
  {
    temperatureMax: '18',
    temperatureMin: '10',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 0,
    weatherDescription: 'Clear sky',
    windSpeedMax: '10',
  },
  {
    temperatureMax: '13',
    temperatureMin: '7',
    precipitationSum: '4',
    rainSum: '4',
    snowfallSum: '0',
    weatherCode: 80,
    weatherDescription: 'Showers',
    windSpeedMax: '20',
  },
  {
    temperatureMax: '10',
    temperatureMin: '4',
    precipitationSum: '2',
    rainSum: '2',
    snowfallSum: '0',
    weatherCode: 71,
    weatherDescription: 'Snow',
    windSpeedMax: '15',
  },
  {
    temperatureMax: '12',
    temperatureMin: '5',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 2,
    weatherDescription: 'Partly cloudy',
    windSpeedMax: '10',
  },
  {
    temperatureMax: '15',
    temperatureMin: '7',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 1,
    weatherDescription: 'Mainly clear',
    windSpeedMax: '8',
  },
  {
    temperatureMax: '18',
    temperatureMin: '9',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 0,
    weatherDescription: 'Clear sky',
    windSpeedMax: '12',
  },
  {
    temperatureMax: '16',
    temperatureMin: '8',
    precipitationSum: '1',
    rainSum: '1',
    snowfallSum: '0',
    weatherCode: 51,
    weatherDescription: 'Drizzle',
    windSpeedMax: '14',
  },
  {
    temperatureMax: '14',
    temperatureMin: '6',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 3,
    weatherDescription: 'Overcast',
    windSpeedMax: '16',
  },
  {
    temperatureMax: '19',
    temperatureMin: '11',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 0,
    weatherDescription: 'Clear sky',
    windSpeedMax: '10',
  },
];

export type Variant = 'sunny' | 'partly' | 'rainy' | 'stormy' | 'snowy' | 'fog';

export const VARIANT_CURRENT: Record<
  Variant,
  Omit<WeatherDay, 'date' | 'dataType'> & {
    now: {
      temperature: number;
      apparentTemperature: number;
      humidity: number;
      weatherCode: number;
      weatherDescription: string;
      isDay: boolean;
    };
  }
> = {
  sunny: {
    temperatureMax: '18',
    temperatureMin: '9',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 0,
    weatherDescription: 'Clear sky',
    windSpeedMax: '12',
    now: {
      temperature: 15,
      apparentTemperature: 14,
      humidity: 48,
      weatherCode: 0,
      weatherDescription: 'Clear sky',
      isDay: true,
    },
  },
  partly: {
    temperatureMax: '14',
    temperatureMin: '8',
    precipitationSum: '2',
    rainSum: '2',
    snowfallSum: '0',
    weatherCode: 2,
    weatherDescription: 'Partly cloudy',
    windSpeedMax: '18',
    now: {
      temperature: 11,
      apparentTemperature: 9,
      humidity: 62,
      weatherCode: 2,
      weatherDescription: 'Partly cloudy',
      isDay: true,
    },
  },
  rainy: {
    temperatureMax: '10',
    temperatureMin: '6',
    precipitationSum: '14',
    rainSum: '14',
    snowfallSum: '0',
    weatherCode: 63,
    weatherDescription: 'Moderate rain',
    windSpeedMax: '28',
    now: {
      temperature: 8,
      apparentTemperature: 5,
      humidity: 91,
      weatherCode: 63,
      weatherDescription: 'Moderate rain',
      isDay: true,
    },
  },
  stormy: {
    temperatureMax: '8',
    temperatureMin: '4',
    precipitationSum: '25',
    rainSum: '25',
    snowfallSum: '0',
    weatherCode: 95,
    weatherDescription: 'Thunderstorm',
    windSpeedMax: '55',
    now: {
      temperature: 6,
      apparentTemperature: 1,
      humidity: 96,
      weatherCode: 95,
      weatherDescription: 'Thunderstorm',
      isDay: true,
    },
  },
  snowy: {
    temperatureMax: '-1',
    temperatureMin: '-6',
    precipitationSum: '8',
    rainSum: '0',
    snowfallSum: '8',
    weatherCode: 73,
    weatherDescription: 'Moderate snow',
    windSpeedMax: '20',
    now: {
      temperature: -3,
      apparentTemperature: -8,
      humidity: 85,
      weatherCode: 73,
      weatherDescription: 'Moderate snow',
      isDay: true,
    },
  },
  fog: {
    temperatureMax: '6',
    temperatureMin: '3',
    precipitationSum: '0',
    rainSum: '0',
    snowfallSum: '0',
    weatherCode: 45,
    weatherDescription: 'Fog',
    windSpeedMax: '5',
    now: {
      temperature: 4,
      apparentTemperature: 3,
      humidity: 97,
      weatherCode: 45,
      weatherDescription: 'Fog',
      isDay: false,
    },
  },
};
