// Auto-generated by scripts/generate-attraction-images.mjs
// DO NOT EDIT MANUALLY - Run 'pnpm build' or 'pnpm generate:attraction-images' to regenerate

/**
 * Available attraction images for park detail pages
 * Generated at build time from public/images/parks/[park]/[attraction].{jpg,png,webp}
 * Maps parkSlug/attractionSlug to image path
 */
export const ATTRACTION_IMAGES: Record<string, string> = {
  'attractiepark-toverland/fenix': '/images/parks/attractiepark-toverland/fenix.jpg',
  'attractiepark-toverland/maximus-blitzbahn':
    '/images/parks/attractiepark-toverland/maximus-blitzbahn.jpeg',
  'attractiepark-toverland/troy': '/images/parks/attractiepark-toverland/troy.jpg',
  'attractiepark-toverland/villa-fiasko': '/images/parks/attractiepark-toverland/villa-fiasko.jpg',
  'bobbejaanland/fury': '/images/parks/bobbejaanland/fury.jpg',
  'bobbejaanland/typhoon': '/images/parks/bobbejaanland/typhoon.jpg',
  'phantasialand/black-mamba': '/images/parks/phantasialand/black-mamba.jpg',
  'phantasialand/fly': '/images/parks/phantasialand/fly.jpg',
  'phantasialand/mystery-castle': '/images/parks/phantasialand/mystery-castle.jpg',
  'phantasialand/river-quest': '/images/parks/phantasialand/river-quest.jpg',
  'phantasialand/taron': '/images/parks/phantasialand/taron.jpg',
  'phantasialand/winjas-fear': '/images/parks/phantasialand/winjas-fear.jpg',
  'phantasialand/winjas-force': '/images/parks/phantasialand/winjas-force.jpg',
  'walibi-belgium/kondaa': '/images/parks/walibi-belgium/kondaa.jpg',
  'walibi-belgium/mecalodon': '/images/parks/walibi-belgium/mecalodon.jpg',
};

/**
 * Get attraction background image path
 * @param parkSlug - Park slug
 * @param attractionSlug - Attraction slug
 * @returns Image path or null if not found
 */
export function getAttractionImage(parkSlug: string, attractionSlug: string): string | null {
  return ATTRACTION_IMAGES[`${parkSlug}/${attractionSlug}`] || null;
}
