// Auto-generated by scripts/generate-attraction-images.mjs
// DO NOT EDIT MANUALLY - Run 'pnpm build' or 'pnpm generate:attraction-images' to regenerate

/**
 * Available attraction images for park detail pages
 * Generated at build time from public/images/parks/[park]/[attraction].{jpg,png,webp}
 * Maps parkSlug/attractionSlug to image path
 */
export const ATTRACTION_IMAGES: Record<string, string> = {
  'attractiepark-toverland/fenix': '/images/parks/attractiepark-toverland/fenix.jpg',
  'attractiepark-toverland/maximus-blitzbahn': '/images/parks/attractiepark-toverland/maximus-blitzbahn.jpeg',
  'attractiepark-toverland/troy': '/images/parks/attractiepark-toverland/troy.jpg',
  'attractiepark-toverland/villa-fiasko': '/images/parks/attractiepark-toverland/villa-fiasko.jpg',
  'bobbejaanland/fury': '/images/parks/bobbejaanland/fury.jpg',
  'bobbejaanland/typhoon': '/images/parks/bobbejaanland/typhoon.jpg',
  'efteling/baron-1898': '/images/parks/efteling/baron-1898.jpg',
  'efteling/danse-macabre': '/images/parks/efteling/danse-macabre.jpg',
  'efteling/droomvlucht': '/images/parks/efteling/droomvlucht.jpg',
  'efteling/fata-morgana': '/images/parks/efteling/fata-morgana.jpg',
  'efteling/pagode': '/images/parks/efteling/pagode.jpg',
  'efteling/python': '/images/parks/efteling/python.jpg',
  'efteling/stoomcarrousel': '/images/parks/efteling/stoomcarrousel.jpg',
  'efteling/symbolica': '/images/parks/efteling/symbolica.jpg',
  'efteling/vogel-rok': '/images/parks/efteling/vogel-rok.jpg',
  'europa-park/arthur': '/images/parks/europa-park/arthur.jpg',
  'europa-park/blue-fire-megacoaster': '/images/parks/europa-park/blue-fire-megacoaster.jpg',
  'europa-park/eurosat-cancan-coaster': '/images/parks/europa-park/eurosat-cancan-coaster.jpg',
  'europa-park/madame-freudenreich-curiosites': '/images/parks/europa-park/madame-freudenreich-curiosites.jpg',
  'europa-park/pirates-in-batavia': '/images/parks/europa-park/pirates-in-batavia.jpg',
  'europa-park/silver-star': '/images/parks/europa-park/silver-star.jpg',
  'europa-park/voltron-nevera-powered-by-rimac': '/images/parks/europa-park/voltron-nevera-powered-by-rimac.jpg',
  'europa-park/water-rollercoaster-poseidon': '/images/parks/europa-park/water-rollercoaster-poseidon.jpg',
  'europa-park/wodan-timburcoaster': '/images/parks/europa-park/wodan-timburcoaster.jpg',
  'movie-park-germany/area-51-top-secret': '/images/parks/movie-park-germany/area-51-top-secret.jpg',
  'movie-park-germany/iron-claw': '/images/parks/movie-park-germany/iron-claw.jpg',
  'movie-park-germany/movie-park-studio-tour': '/images/parks/movie-park-germany/movie-park-studio-tour.jpg',
  'movie-park-germany/star-trek-operation-enterprise': '/images/parks/movie-park-germany/star-trek-operation-enterprise.jpg',
  'phantasialand/black-mamba': '/images/parks/phantasialand/black-mamba.jpg',
  'phantasialand/chiapas-die-wasserbahn': '/images/parks/phantasialand/chiapas-die-wasserbahn.jpg',
  'phantasialand/fly': '/images/parks/phantasialand/fly.jpg',
  'phantasialand/mystery-castle': '/images/parks/phantasialand/mystery-castle.jpg',
  'phantasialand/raik': '/images/parks/phantasialand/raik.jpg',
  'phantasialand/river-quest': '/images/parks/phantasialand/river-quest.jpg',
  'phantasialand/taron': '/images/parks/phantasialand/taron.jpg',
  'phantasialand/winjas-fear': '/images/parks/phantasialand/winjas-fear.jpg',
  'phantasialand/winjas-force': '/images/parks/phantasialand/winjas-force.jpg',
  'walibi-belgium/kondaa': '/images/parks/walibi-belgium/kondaa.jpg',
  'walibi-belgium/mecalodon': '/images/parks/walibi-belgium/mecalodon.jpg',
  'walibi-holland/condor': '/images/parks/walibi-holland/condor.jpg',
  'walibi-holland/crazy-river': '/images/parks/walibi-holland/crazy-river.jpg',
  'walibi-holland/eat-my-dust': '/images/parks/walibi-holland/eat-my-dust.jpg',
  'walibi-holland/goliath': '/images/parks/walibi-holland/goliath.jpg',
  'walibi-holland/lost-gravity': '/images/parks/walibi-holland/lost-gravity.jpg',
  'walibi-holland/speed-of-sound': '/images/parks/walibi-holland/speed-of-sound.jpg',
  'walibi-holland/untamed': '/images/parks/walibi-holland/untamed.jpg',
  'walibi-holland/xpress-platform-13': '/images/parks/walibi-holland/xpress-platform-13.jpg',
  'walibi-holland/yoy-chill': '/images/parks/walibi-holland/yoy-chill.jpg',
  'walibi-holland/yoy-thrill': '/images/parks/walibi-holland/yoy-thrill.jpg',
};

/**
 * Get attraction background image path
 * @param parkSlug - Park slug
 * @param attractionSlug - Attraction slug
 * @returns Image path or null if not found
 */
export function getAttractionImage(parkSlug: string, attractionSlug: string): string | null {
  return ATTRACTION_IMAGES[`${parkSlug}/${attractionSlug}`] || null;
}
