import type { GlossaryTermData } from './types';

export const GLOSSARY_TERMS: GlossaryTermData[] = [
  // ── Wait Times ─────────────────────────────────────────────────────────────
  {
    id: 'wait-time',
    category: 'wait-times',
    slugs: {
      en: 'wait-time',
      de: 'wartezeit',
      fr: 'temps-attente',
      it: 'tempo-attesa',
      nl: 'wachttijd',
      es: 'tiempo-espera',
    },
  },
  {
    id: 'single-rider',
    category: 'wait-times',
    slugs: {
      en: 'single-rider',
      de: 'einzelfahrer', // Used on German park signage (Europa-Park, Phantasialand)
      fr: 'single-rider',
      it: 'single-rider',
      nl: 'single-rider',
      es: 'single-rider',
    },
  },
  {
    id: 'virtual-queue',
    category: 'wait-times',
    slugs: {
      en: 'virtual-queue',
      de: 'virtuelle-warteschlange',
      fr: 'file-attente-virtuelle',
      it: 'coda-virtuale',
      nl: 'virtuele-wachtrij',
      es: 'cola-virtual',
    },
  },
  {
    id: 'express-pass',
    category: 'wait-times',
    slugs: {
      en: 'express-pass',
      de: 'expresspass',
      fr: 'pass-express',
      it: 'pass-express',
      nl: 'express-pas',
      es: 'pase-express',
    },
  },
  {
    id: 'posted-wait-time',
    category: 'wait-times',
    slugs: {
      en: 'posted-wait-time',
      de: 'angezeigte-wartezeit',
      fr: 'temps-affiche',
      it: 'tempo-segnalato',
      nl: 'aangegeven-wachttijd',
      es: 'tiempo-publicado',
    },
  },
  {
    id: 'standby-queue',
    category: 'wait-times',
    slugs: {
      en: 'standby-queue',
      de: 'standby',
      fr: 'file-standby',
      it: 'coda-standby',
      nl: 'standby-wachtrij',
      es: 'cola-standby',
    },
  },
  {
    id: 'lightning-lane',
    category: 'wait-times',
    slugs: {
      en: 'lightning-lane',
      de: 'lightning-lane',
      fr: 'lightning-lane',
      it: 'lightning-lane',
      nl: 'lightning-lane',
      es: 'lightning-lane',
    },
  },
  {
    id: 'genie-plus',
    category: 'wait-times',
    slugs: {
      en: 'genie-plus',
      de: 'genie-plus',
      fr: 'genie-plus',
      it: 'genie-plus',
      nl: 'genie-plus',
      es: 'genie-plus',
    },
  },
  {
    id: 'boarding-group',
    category: 'wait-times',
    slugs: {
      en: 'boarding-group',
      de: 'boarding-group',
      fr: 'boarding-group',
      it: 'boarding-group',
      nl: 'boarding-group',
      es: 'boarding-group',
    },
  },
  {
    id: 'fastpass',
    category: 'wait-times',
    slugs: {
      en: 'fastpass',
      de: 'fastpass',
      fr: 'fastpass',
      it: 'fastpass',
      nl: 'fastpass',
      es: 'fastpass',
    },
  },
  {
    id: 'return-time',
    category: 'wait-times',
    slugs: {
      en: 'return-time',
      de: 'rueckkehrzeit',
      fr: 'creneau-retour',
      it: 'orario-ritorno',
      nl: 'terugkeertijd',
      es: 'hora-regreso',
    },
  },
  {
    id: 'rider-switch',
    category: 'wait-times',
    slugs: {
      en: 'rider-switch',
      de: 'rider-switch',
      fr: 'rider-switch',
      it: 'rider-switch',
      nl: 'rider-switch',
      es: 'rider-switch',
    },
  },
  {
    id: 'queue-line',
    category: 'wait-times',
    slugs: {
      en: 'queue-line',
      de: 'warteschlange',
      fr: 'file-attente',
      it: 'coda',
      nl: 'wachtrij',
      es: 'cola',
    },
  },
  // ── Crowd Levels ───────────────────────────────────────────────────────────
  {
    id: 'crowd-level',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-level',
      de: 'besucherdichte',
      fr: 'niveau-affluence',
      it: 'livello-affluenza',
      nl: 'drukte-niveau',
      es: 'nivel-afluencia',
    },
  },
  {
    id: 'crowd-calendar',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-calendar',
      de: 'besucherkalender',
      fr: 'calendrier-affluence',
      it: 'calendario-affluenza',
      nl: 'druktekalender',
      es: 'calendario-afluencia',
    },
  },
  {
    id: 'peak-day',
    category: 'crowd-levels',
    slugs: {
      en: 'peak-day',
      de: 'spitzentag',
      fr: 'jour-pic',
      it: 'giorno-picco',
      nl: 'piekdag',
      es: 'dia-pico',
    },
  },
  {
    id: 'off-peak',
    category: 'crowd-levels',
    slugs: {
      en: 'off-peak',
      de: 'nebensaison',
      fr: 'hors-saison',
      it: 'fuori-stagione',
      nl: 'laagseizoen',
      es: 'temporada-baja',
    },
  },
  // ── Park Operations ────────────────────────────────────────────────────────
  {
    id: 'offseason',
    category: 'park-operations',
    slugs: {
      en: 'offseason',
      de: 'offseason',
      fr: 'fermeture-saisonniere',
      it: 'chiusura-stagionale',
      nl: 'seizoenssluiting',
      es: 'cierre-temporal',
    },
  },
  {
    id: 'refurbishment',
    category: 'park-operations',
    slugs: {
      en: 'refurbishment',
      de: 'renovierung',
      fr: 'renovation',
      it: 'ristrutturazione',
      nl: 'renovatie',
      es: 'renovacion',
    },
  },
  {
    id: 'downtime',
    category: 'park-operations',
    slugs: {
      en: 'downtime',
      de: 'betriebsstoerung',
      fr: 'temps-arret',
      it: 'tempo-fermo',
      nl: 'stilstand',
      es: 'tiempo-inactividad',
    },
  },
  {
    id: 'ride-capacity',
    category: 'park-operations',
    slugs: {
      en: 'ride-capacity',
      de: 'kapazitaet',
      fr: 'capacite-attraction',
      it: 'capacita-attrazione',
      nl: 'capaciteit',
      es: 'capacidad-atraccion',
    },
  },
  {
    id: 'soft-opening',
    category: 'park-operations',
    slugs: {
      en: 'soft-opening',
      de: 'soft-opening',
      fr: 'soft-opening',
      it: 'soft-opening',
      nl: 'soft-opening',
      es: 'soft-opening',
    },
  },
  {
    id: 'opening-day',
    category: 'park-operations',
    slugs: {
      en: 'opening-day',
      de: 'eroeffnungstag',
      fr: 'jour-ouverture',
      it: 'giorno-inaugurazione',
      nl: 'openingsdag',
      es: 'dia-apertura',
    },
  },
  {
    id: 'hard-ticket-event',
    category: 'park-operations',
    slugs: {
      en: 'hard-ticket-event',
      de: 'sonderveranstaltung',
      fr: 'evenement-special',
      it: 'evento-speciale',
      nl: 'speciaal-evenement',
      es: 'evento-especial',
    },
  },
  // ── Planning ───────────────────────────────────────────────────────────────
  {
    id: 'rope-drop',
    category: 'planning',
    slugs: {
      en: 'rope-drop',
      de: 'rope-drop',
      fr: 'rope-drop',
      it: 'rope-drop',
      nl: 'rope-drop',
      es: 'rope-drop',
    },
  },
  {
    id: 'early-entry',
    category: 'planning',
    slugs: {
      en: 'early-entry',
      de: 'frueheinlass', // Used at German parks; "Früheinlass" is the official term
      fr: 'entree-anticipee', // Disneyland Paris uses "entrée anticipée"
      it: 'early-entry',
      nl: 'early-entry',
      es: 'early-entry',
    },
  },
  {
    id: 'park-hopper',
    category: 'planning',
    slugs: {
      en: 'park-hopper',
      de: 'park-hopper',
      fr: 'park-hopper',
      it: 'park-hopper',
      nl: 'park-hopper',
      es: 'park-hopper',
    },
  },
  {
    id: 'season-pass',
    category: 'planning',
    slugs: {
      en: 'season-pass',
      de: 'jahrespass',
      fr: 'abonnement-annuel',
      it: 'abbonamento-annuale',
      nl: 'jaarkaart',
      es: 'pase-anual',
    },
  },
  {
    id: 'blockout-date',
    category: 'planning',
    slugs: {
      en: 'blockout-date',
      de: 'sperrtag',
      fr: 'date-bloquee',
      it: 'giorno-bloccato',
      nl: 'geblokkeerde-dag',
      es: 'fecha-bloqueada',
    },
  },
  {
    id: 'ai-forecast',
    category: 'planning',
    slugs: {
      en: 'ai-forecast',
      de: 'ki-prognose',
      fr: 'prevision-ia',
      it: 'previsione-ia',
      nl: 'ai-voorspelling',
      es: 'prediccion-ia',
    },
  },
  {
    id: 'ki',
    category: 'planning',
    slugs: {
      en: 'artificial-intelligence',
      de: 'kuenstliche-intelligenz',
      fr: 'intelligence-artificielle',
      it: 'intelligenza-artificiale',
      nl: 'kunstmatige-intelligentie',
      es: 'inteligencia-artificial',
    },
  },
  {
    id: 'realtime-wait-time',
    category: 'wait-times',
    slugs: {
      en: 'live-wait-time',
      de: 'echtzeit-wartezeit',
      fr: 'attente-temps-reel',
      it: 'attesa-tempo-reale',
      nl: 'realtime-wachttijd',
      es: 'espera-tiempo-real',
    },
  },
  {
    id: 'crowd-forecast',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-forecast',
      de: 'crowd-prognose',
      fr: 'prevision-affluence',
      it: 'previsione-affluenza',
      nl: 'drukte-prognose',
      es: 'prevision-afluencia',
    },
  },
  {
    id: 'opening-hours',
    category: 'park-operations',
    slugs: {
      en: 'opening-hours',
      de: 'oeffnungszeiten',
      fr: 'horaires-ouverture',
      it: 'orari-apertura',
      nl: 'openingstijden',
      es: 'horarios-apertura',
    },
  },
  {
    id: 'wait-time-trend',
    category: 'wait-times',
    slugs: {
      en: 'wait-time-trend',
      de: 'wartezeit-trend',
      fr: 'tendance-attente',
      it: 'tendenza-attesa',
      nl: 'wachttijd-trend',
      es: 'tendencia-espera',
    },
  },
  // ── Attractions ────────────────────────────────────────────────────────────
  {
    id: 'height-requirement',
    category: 'attractions',
    slugs: {
      en: 'height-requirement',
      de: 'mindestgroesse',
      fr: 'taille-minimale',
      it: 'altezza-minima',
      nl: 'minimumlengte',
      es: 'talla-minima',
    },
  },
  {
    id: 'themed-land',
    category: 'attractions',
    slugs: {
      en: 'themed-land',
      de: 'themenbereich',
      fr: 'univers-thematique',
      it: 'area-tematica',
      nl: 'themagebied',
      es: 'zona-tematica',
    },
  },
  {
    id: 'dark-ride',
    category: 'attractions',
    slugs: {
      en: 'dark-ride',
      de: 'dark-ride',
      fr: 'dark-ride',
      it: 'dark-ride',
      nl: 'dark-ride',
      es: 'dark-ride',
    },
  },
  {
    id: 'ride-photo',
    category: 'attractions',
    slugs: {
      en: 'ride-photo',
      de: 'fahrfoto',
      fr: 'photo-de-manege',
      it: 'foto-attrazione',
      nl: 'rit-foto',
      es: 'foto-atraccion',
    },
  },
  // ── Coasters ───────────────────────────────────────────────────────────────
  {
    id: 'airtime',
    category: 'coaster-elements',
    slugs: {
      en: 'airtime',
      de: 'airtime',
      fr: 'airtime',
      it: 'airtime',
      nl: 'airtime',
      es: 'airtime',
    },
  },
  {
    id: 'inversion',
    category: 'coaster-elements',
    slugs: {
      en: 'inversion',
      de: 'inversion',
      fr: 'inversion',
      it: 'inversione',
      nl: 'inversie',
      es: 'inversion',
    },
  },
  {
    id: 'vertical-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'vertical-loop',
      de: 'looping',
      fr: 'looping',
      it: 'looping',
      nl: 'looping',
      es: 'looping',
    },
  },
  {
    id: 'immelmann',
    category: 'coaster-elements',
    slugs: {
      en: 'immelmann',
      de: 'immelmann',
      fr: 'immelmann',
      it: 'immelmann',
      nl: 'immelmann',
      es: 'immelmann',
    },
  },
  {
    id: 'zero-g-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'zero-g-roll',
      de: 'zero-g-roll',
      fr: 'zero-g-roll',
      it: 'zero-g-roll',
      nl: 'zero-g-roll',
      es: 'zero-g-roll',
    },
  },
  {
    id: 'launch-coaster',
    category: 'coasters',
    slugs: {
      en: 'launch-coaster',
      de: 'launch-coaster',
      fr: 'launch-coaster',
      it: 'launch-coaster',
      nl: 'launch-coaster',
      es: 'launch-coaster',
    },
  },
  {
    id: 'wooden-coaster',
    category: 'coasters',
    slugs: {
      en: 'wooden-coaster',
      de: 'holzachterbahn',
      fr: 'montagne-russe-bois',
      it: 'montagna-russa-legno',
      nl: 'houten-achtbaan',
      es: 'montana-rusa-madera',
    },
  },
  {
    id: 'hybrid-coaster',
    category: 'coasters',
    slugs: {
      en: 'hybrid-coaster',
      de: 'hybrid-coaster',
      fr: 'hybrid-coaster',
      it: 'hybrid-coaster',
      nl: 'hybrid-coaster',
      es: 'hybrid-coaster',
    },
  },
  {
    id: 'b-and-m',
    category: 'coasters',
    slugs: {
      en: 'b-and-m',
      de: 'b-and-m',
      fr: 'b-and-m',
      it: 'b-and-m',
      nl: 'b-and-m',
      es: 'b-and-m',
    },
  },
  {
    id: 'intamin',
    category: 'coasters',
    slugs: {
      en: 'intamin',
      de: 'intamin',
      fr: 'intamin',
      it: 'intamin',
      nl: 'intamin',
      es: 'intamin',
    },
  },
  {
    id: 'mack-rides',
    category: 'coasters',
    slugs: {
      en: 'mack-rides',
      de: 'mack-rides',
      fr: 'mack-rides',
      it: 'mack-rides',
      nl: 'mack-rides',
      es: 'mack-rides',
    },
  },
  {
    id: 'rmc',
    category: 'coasters',
    slugs: {
      en: 'rmc',
      de: 'rmc',
      fr: 'rmc',
      it: 'rmc',
      nl: 'rmc',
      es: 'rmc',
    },
  },
  {
    id: 'vekoma',
    category: 'coasters',
    slugs: {
      en: 'vekoma',
      de: 'vekoma',
      fr: 'vekoma',
      it: 'vekoma',
      nl: 'vekoma',
      es: 'vekoma',
    },
  },
  {
    id: 'gerstlauer',
    category: 'coasters',
    slugs: {
      en: 'gerstlauer',
      de: 'gerstlauer',
      fr: 'gerstlauer',
      it: 'gerstlauer',
      nl: 'gerstlauer',
      es: 'gerstlauer',
    },
  },
  {
    id: 'schwarzkopf',
    category: 'coasters',
    slugs: {
      en: 'schwarzkopf',
      de: 'schwarzkopf',
      fr: 'schwarzkopf',
      it: 'schwarzkopf',
      nl: 'schwarzkopf',
      es: 'schwarzkopf',
    },
  },
  // ── Coaster Elements ───────────────────────────────────────────────────────
  {
    id: 'lifthill',
    category: 'coaster-elements',
    slugs: {
      en: 'lifthill',
      de: 'lifthill',
      fr: 'lifthill',
      it: 'lifthill',
      nl: 'lifthill',
      es: 'lifthill',
    },
  },
  {
    id: 'first-drop',
    category: 'coaster-elements',
    slugs: {
      en: 'first-drop',
      de: 'first-drop',
      fr: 'first-drop',
      it: 'first-drop',
      nl: 'first-drop',
      es: 'first-drop',
    },
  },
  {
    id: 'airtime-hill',
    category: 'coaster-elements',
    slugs: {
      en: 'airtime-hill',
      de: 'airtime-huegel',
      fr: 'airtime-hill',
      it: 'airtime-hill',
      nl: 'airtime-hill',
      es: 'airtime-hill',
    },
  },
  {
    id: 'helix',
    category: 'coaster-elements',
    slugs: {
      en: 'helix',
      de: 'helix',
      fr: 'helix',
      it: 'helix',
      nl: 'helix',
      es: 'helix',
    },
  },
  {
    id: 'block-brake',
    category: 'coaster-elements',
    slugs: {
      en: 'block-brake',
      de: 'blockbremse',
      fr: 'block-brake',
      it: 'block-brake',
      nl: 'block-brake',
      es: 'block-brake',
    },
  },
  {
    id: 'brake-run',
    category: 'coaster-elements',
    slugs: {
      en: 'brake-run',
      de: 'brake-run',
      fr: 'brake-run',
      it: 'brake-run',
      nl: 'brake-run',
      es: 'brake-run',
    },
  },
  {
    id: 'cobra-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'cobra-roll',
      de: 'cobra-roll',
      fr: 'cobra-roll',
      it: 'cobra-roll',
      nl: 'cobra-roll',
      es: 'cobra-roll',
    },
  },
  {
    id: 'corkscrew',
    category: 'coaster-elements',
    slugs: {
      en: 'corkscrew',
      de: 'korkenzieher',
      fr: 'corkscrew',
      it: 'corkscrew',
      nl: 'corkscrew',
      es: 'corkscrew',
    },
  },
  {
    id: 'dive-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'dive-loop',
      de: 'dive-loop',
      fr: 'dive-loop',
      it: 'dive-loop',
      nl: 'dive-loop',
      es: 'dive-loop',
    },
  },
  {
    id: 'inline-twist',
    category: 'coaster-elements',
    slugs: {
      en: 'inline-twist',
      de: 'inline-twist',
      fr: 'inline-twist',
      it: 'inline-twist',
      nl: 'inline-twist',
      es: 'inline-twist',
    },
  },
  {
    id: 'heartline-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'heartline-roll',
      de: 'heartline-roll',
      fr: 'heartline-roll',
      it: 'heartline-roll',
      nl: 'heartline-roll',
      es: 'heartline-roll',
    },
  },
  {
    id: 'sidewinder',
    category: 'coaster-elements',
    slugs: {
      en: 'sidewinder',
      de: 'sidewinder',
      fr: 'sidewinder',
      it: 'sidewinder',
      nl: 'sidewinder',
      es: 'sidewinder',
    },
  },
  {
    id: 'pretzel-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'pretzel-loop',
      de: 'pretzel-loop',
      fr: 'pretzel-loop',
      it: 'pretzel-loop',
      nl: 'pretzel-loop',
      es: 'pretzel-loop',
    },
  },
  {
    id: 'batwing',
    category: 'coaster-elements',
    slugs: {
      en: 'batwing',
      de: 'batwing',
      fr: 'batwing',
      it: 'batwing',
      nl: 'batwing',
      es: 'batwing',
    },
  },
  {
    id: 'norwegian-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'norwegian-loop',
      de: 'norwegian-loop',
      fr: 'norwegian-loop',
      it: 'norwegian-loop',
      nl: 'norwegian-loop',
      es: 'norwegian-loop',
    },
  },
  {
    id: 'flat-spin',
    category: 'coaster-elements',
    slugs: {
      en: 'flat-spin',
      de: 'flat-spin',
      fr: 'flat-spin',
      it: 'flat-spin',
      nl: 'flat-spin',
      es: 'flat-spin',
    },
  },
  {
    id: 'cutback',
    category: 'coaster-elements',
    slugs: {
      en: 'cutback',
      de: 'cutback',
      fr: 'cutback',
      it: 'cutback',
      nl: 'cutback',
      es: 'cutback',
    },
  },
  {
    id: 'butterfly',
    category: 'coaster-elements',
    slugs: {
      en: 'butterfly',
      de: 'butterfly',
      fr: 'butterfly',
      it: 'butterfly',
      nl: 'butterfly',
      es: 'butterfly',
    },
  },
  {
    id: 'bowtie',
    category: 'coaster-elements',
    slugs: {
      en: 'bowtie',
      de: 'bowtie',
      fr: 'bowtie',
      it: 'bowtie',
      nl: 'bowtie',
      es: 'bowtie',
    },
  },
  {
    id: 'bunnyhop',
    category: 'coaster-elements',
    slugs: {
      en: 'bunnyhop',
      de: 'bunnyhop',
      fr: 'bunnyhop',
      it: 'bunnyhop',
      nl: 'bunnyhop',
      es: 'bunnyhop',
    },
  },
  {
    id: 'stengel-dive',
    category: 'coaster-elements',
    slugs: {
      en: 'stengel-dive',
      de: 'stengel-dive',
      fr: 'stengel-dive',
      it: 'stengel-dive',
      nl: 'stengel-dive',
      es: 'stengel-dive',
    },
  },
  {
    id: 'horseshoe',
    category: 'coaster-elements',
    slugs: {
      en: 'horseshoe',
      de: 'horseshoe',
      fr: 'horseshoe',
      it: 'horseshoe',
      nl: 'horseshoe',
      es: 'horseshoe',
    },
  },
  {
    id: 'predrop',
    category: 'coaster-elements',
    slugs: {
      en: 'predrop',
      de: 'predrop',
      fr: 'predrop',
      it: 'predrop',
      nl: 'predrop',
      es: 'predrop',
    },
  },
  {
    id: 'top-hat',
    category: 'coaster-elements',
    slugs: {
      en: 'top-hat',
      de: 'top-hat',
      fr: 'top-hat',
      it: 'top-hat',
      nl: 'top-hat',
      es: 'top-hat',
    },
  },
  {
    id: 'boomerang',
    category: 'coasters',
    slugs: {
      en: 'boomerang',
      de: 'boomerang',
      fr: 'boomerang',
      it: 'boomerang',
      nl: 'boomerang',
      es: 'boomerang',
    },
  },
  {
    id: 'euro-fighter',
    category: 'coasters',
    slugs: {
      en: 'euro-fighter',
      de: 'euro-fighter',
      fr: 'euro-fighter',
      it: 'euro-fighter',
      nl: 'euro-fighter',
      es: 'euro-fighter',
    },
  },
  {
    id: 'dive-coaster',
    category: 'coasters',
    slugs: {
      en: 'dive-coaster',
      de: 'dive-coaster',
      fr: 'dive-coaster',
      it: 'dive-coaster',
      nl: 'dive-coaster',
      es: 'dive-coaster',
    },
  },
  {
    id: 'credit',
    category: 'coasters',
    slugs: {
      en: 'credit',
      de: 'credit',
      fr: 'credit',
      it: 'credit',
      nl: 'credit',
      es: 'credit',
    },
  },
  {
    id: 'pov',
    category: 'coasters',
    slugs: {
      en: 'pov',
      de: 'pov',
      fr: 'pov',
      it: 'pov',
      nl: 'pov',
      es: 'pov',
    },
  },
  {
    id: 'vr-coaster',
    category: 'coasters',
    slugs: {
      en: 'vr-coaster',
      de: 'vr-coaster',
      fr: 'vr-coaster',
      it: 'vr-coaster',
      nl: 'vr-coaster',
      es: 'vr-coaster',
    },
  },
  {
    id: 'ert',
    category: 'planning',
    slugs: {
      en: 'ert',
      de: 'ert',
      fr: 'ert',
      it: 'ert',
      nl: 'ert',
      es: 'ert',
    },
  },
  {
    id: 'touring-plan',
    category: 'planning',
    slugs: {
      en: 'touring-plan',
      de: 'touringplan',
      fr: 'plan-visite',
      it: 'piano-visita',
      nl: 'bezoekplan',
      es: 'plan-visita',
    },
  },
  {
    id: 'stacking',
    category: 'coasters',
    slugs: {
      en: 'stacking',
      de: 'stacking',
      fr: 'stacking',
      it: 'stacking',
      nl: 'stacking',
      es: 'stacking',
    },
  },
  // ── New Coaster Types ──────────────────────────────────────────────────────
  {
    id: 'inverted-coaster',
    category: 'coasters',
    slugs: {
      en: 'inverted-coaster',
      de: 'inverted-coaster',
      fr: 'inverted-coaster',
      it: 'inverted-coaster',
      nl: 'inverted-coaster',
      es: 'inverted-coaster',
    },
  },
  {
    id: 'wing-coaster',
    category: 'coasters',
    slugs: {
      en: 'wing-coaster',
      de: 'wing-coaster',
      fr: 'wing-coaster',
      it: 'wing-coaster',
      nl: 'wing-coaster',
      es: 'wing-coaster',
    },
  },
  {
    id: 'spinning-coaster',
    category: 'coasters',
    slugs: {
      en: 'spinning-coaster',
      de: 'spinning-coaster',
      fr: 'spinning-coaster',
      it: 'spinning-coaster',
      nl: 'spinning-coaster',
      es: 'spinning-coaster',
    },
  },
  {
    id: 'hyper-coaster',
    category: 'coasters',
    slugs: {
      en: 'hyper-coaster',
      de: 'hyper-coaster',
      fr: 'hyper-coaster',
      it: 'hyper-coaster',
      nl: 'hyper-coaster',
      es: 'hyper-coaster',
    },
  },
  {
    id: 'giga-coaster',
    category: 'coasters',
    slugs: {
      en: 'giga-coaster',
      de: 'giga-coaster',
      fr: 'giga-coaster',
      it: 'giga-coaster',
      nl: 'giga-coaster',
      es: 'giga-coaster',
    },
  },
  // ── New Coaster Elements ───────────────────────────────────────────────────
  {
    id: 'overbank',
    category: 'coaster-elements',
    slugs: {
      en: 'overbank',
      de: 'uebergeneigte-kurve', // German: "übergeneigte Kurve" — standard DE community term
      fr: 'overbank',
      it: 'overbank',
      nl: 'overbank',
      es: 'overbank',
    },
  },
  {
    id: 'trim-brake',
    category: 'coaster-elements',
    slugs: {
      en: 'trim-brake',
      de: 'trim-bremse', // German: "Trim-Bremse" — standard DE community term
      fr: 'trim-brake',
      it: 'trim-brake',
      nl: 'trim-brake',
      es: 'trim-brake',
    },
  },
  {
    id: 'rollback',
    category: 'coaster-elements',
    slugs: {
      en: 'rollback',
      de: 'rollback',
      fr: 'rollback',
      it: 'rollback',
      nl: 'rollback',
      es: 'rollback',
    },
  },
  // ── New Attractions ────────────────────────────────────────────────────────
  {
    id: 'animatronics',
    category: 'attractions',
    slugs: {
      en: 'animatronics',
      de: 'animatronics',
      fr: 'animatronique', // French: established loanword, Wikipedia "Animatronique"
      it: 'animatronica', // Italian: established form
      nl: 'animatronics',
      es: 'animatronica', // Spanish: Wikipedia "Animatrónica"
    },
  },
  {
    id: 'trackless-ride',
    category: 'attractions',
    slugs: {
      en: 'trackless-ride',
      de: 'trackless-ride',
      fr: 'trackless-ride',
      it: 'trackless-ride',
      nl: 'trackless-ride',
      es: 'trackless-ride',
    },
  },
];
