import type { GlossaryTermData } from './types';

export const GLOSSARY_TERMS: GlossaryTermData[] = [
  // ── Wait Times ─────────────────────────────────────────────────────────────
  {
    id: 'wait-time',
    category: 'wait-times',
    slugs: {
      en: 'wait-time',
      de: 'wartezeit',
      fr: 'temps-attente',
      it: 'tempo-attesa',
      nl: 'wachttijd',
      es: 'tiempo-espera',
    },
  },
  {
    id: 'single-rider',
    category: 'wait-times',
    slugs: {
      en: 'single-rider',
      de: 'einzelfahrer', // Used on German park signage (Europa-Park, Phantasialand)
      fr: 'single-rider',
      it: 'single-rider',
      nl: 'single-rider',
      es: 'single-rider',
    },
  },
  {
    id: 'virtual-queue',
    category: 'wait-times',
    slugs: {
      en: 'virtual-queue',
      de: 'virtuelle-warteschlange',
      fr: 'file-attente-virtuelle',
      it: 'coda-virtuale',
      nl: 'virtuele-wachtrij',
      es: 'cola-virtual',
    },
  },
  {
    id: 'express-pass',
    category: 'wait-times',
    slugs: {
      en: 'express-pass',
      de: 'expresspass',
      fr: 'pass-express',
      it: 'pass-express',
      nl: 'express-pas',
      es: 'pase-express',
    },
  },
  {
    id: 'posted-wait-time',
    category: 'wait-times',
    slugs: {
      en: 'posted-wait-time',
      de: 'angezeigte-wartezeit',
      fr: 'temps-affiche',
      it: 'tempo-segnalato',
      nl: 'aangegeven-wachttijd',
      es: 'tiempo-publicado',
    },
  },
  {
    id: 'standby-queue',
    category: 'wait-times',
    slugs: {
      en: 'standby-queue',
      de: 'standby',
      fr: 'file-standby',
      it: 'coda-standby',
      nl: 'standby-wachtrij',
      es: 'cola-standby',
    },
  },
  {
    id: 'lightning-lane',
    category: 'wait-times',
    slugs: {
      en: 'lightning-lane',
      de: 'lightning-lane',
      fr: 'lightning-lane',
      it: 'lightning-lane',
      nl: 'lightning-lane',
      es: 'lightning-lane',
    },
  },
  {
    id: 'genie-plus',
    category: 'wait-times',
    slugs: {
      en: 'genie-plus',
      de: 'genie-plus',
      fr: 'genie-plus',
      it: 'genie-plus',
      nl: 'genie-plus',
      es: 'genie-plus',
    },
  },
  {
    id: 'boarding-group',
    category: 'wait-times',
    slugs: {
      en: 'boarding-group',
      de: 'boarding-group',
      fr: 'boarding-group',
      it: 'boarding-group',
      nl: 'boarding-group',
      es: 'boarding-group',
    },
  },
  {
    id: 'fastpass',
    category: 'wait-times',
    slugs: {
      en: 'fastpass',
      de: 'fastpass',
      fr: 'fastpass',
      it: 'fastpass',
      nl: 'fastpass',
      es: 'fastpass',
    },
  },
  {
    id: 'return-time',
    category: 'wait-times',
    slugs: {
      en: 'return-time',
      de: 'rueckkehrzeit',
      fr: 'creneau-retour',
      it: 'orario-ritorno',
      nl: 'terugkeertijd',
      es: 'hora-regreso',
    },
  },
  {
    id: 'rider-switch',
    category: 'wait-times',
    slugs: {
      en: 'rider-switch',
      de: 'rider-switch',
      fr: 'rider-switch',
      it: 'rider-switch',
      nl: 'rider-switch',
      es: 'rider-switch',
    },
  },
  {
    id: 'queue-line',
    category: 'wait-times',
    slugs: {
      en: 'queue-line',
      de: 'warteschlange',
      fr: 'file-attente',
      it: 'coda',
      nl: 'wachtrij',
      es: 'cola',
    },
  },
  // ── Crowd Levels ───────────────────────────────────────────────────────────
  {
    id: 'crowd-level',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-level',
      de: 'besucherdichte',
      fr: 'niveau-affluence',
      it: 'livello-affluenza',
      nl: 'drukte-niveau',
      es: 'nivel-afluencia',
    },
  },
  {
    id: 'crowd-calendar',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-calendar',
      de: 'besucherkalender',
      fr: 'calendrier-affluence',
      it: 'calendario-affluenza',
      nl: 'druktekalender',
      es: 'calendario-afluencia',
    },
  },
  {
    id: 'peak-day',
    category: 'crowd-levels',
    slugs: {
      en: 'peak-day',
      de: 'spitzentag',
      fr: 'jour-pic',
      it: 'giorno-picco',
      nl: 'piekdag',
      es: 'dia-pico',
    },
  },
  {
    id: 'off-peak',
    category: 'crowd-levels',
    slugs: {
      en: 'off-peak',
      de: 'nebensaison',
      fr: 'hors-saison',
      it: 'fuori-stagione',
      nl: 'laagseizoen',
      es: 'temporada-baja',
    },
  },
  // ── Park Operations ────────────────────────────────────────────────────────
  {
    id: 'offseason',
    category: 'park-operations',
    slugs: {
      en: 'offseason',
      de: 'offseason',
      fr: 'fermeture-saisonniere',
      it: 'chiusura-stagionale',
      nl: 'seizoenssluiting',
      es: 'cierre-temporal',
    },
  },
  {
    id: 'refurbishment',
    category: 'park-operations',
    slugs: {
      en: 'refurbishment',
      de: 'renovierung',
      fr: 'renovation',
      it: 'ristrutturazione',
      nl: 'renovatie',
      es: 'renovacion',
    },
  },
  {
    id: 'downtime',
    category: 'park-operations',
    slugs: {
      en: 'downtime',
      de: 'betriebsstoerung',
      fr: 'temps-arret',
      it: 'tempo-fermo',
      nl: 'stilstand',
      es: 'tiempo-inactividad',
    },
  },
  {
    id: 'ride-capacity',
    category: 'park-operations',
    slugs: {
      en: 'ride-capacity',
      de: 'kapazitaet',
      fr: 'capacite-attraction',
      it: 'capacita-attrazione',
      nl: 'capaciteit',
      es: 'capacidad-atraccion',
    },
  },
  {
    id: 'soft-opening',
    category: 'park-operations',
    slugs: {
      en: 'soft-opening',
      de: 'soft-opening',
      fr: 'soft-opening',
      it: 'soft-opening',
      nl: 'soft-opening',
      es: 'soft-opening',
    },
  },
  {
    id: 'opening-day',
    category: 'park-operations',
    slugs: {
      en: 'opening-day',
      de: 'eroeffnungstag',
      fr: 'jour-ouverture',
      it: 'giorno-inaugurazione',
      nl: 'openingsdag',
      es: 'dia-apertura',
    },
  },
  {
    id: 'hard-ticket-event',
    category: 'park-operations',
    slugs: {
      en: 'hard-ticket-event',
      de: 'sonderveranstaltung',
      fr: 'evenement-special',
      it: 'evento-speciale',
      nl: 'speciaal-evenement',
      es: 'evento-especial',
    },
  },
  // ── Planning ───────────────────────────────────────────────────────────────
  {
    id: 'rope-drop',
    category: 'planning',
    slugs: {
      en: 'rope-drop',
      de: 'rope-drop',
      fr: 'rope-drop',
      it: 'rope-drop',
      nl: 'rope-drop',
      es: 'rope-drop',
    },
  },
  {
    id: 'early-entry',
    category: 'planning',
    slugs: {
      en: 'early-entry',
      de: 'frueheinlass', // Used at German parks; "Früheinlass" is the official term
      fr: 'entree-anticipee', // Disneyland Paris uses "entrée anticipée"
      it: 'early-entry',
      nl: 'early-entry',
      es: 'early-entry',
    },
  },
  {
    id: 'park-hopper',
    category: 'planning',
    slugs: {
      en: 'park-hopper',
      de: 'park-hopper',
      fr: 'park-hopper',
      it: 'park-hopper',
      nl: 'park-hopper',
      es: 'park-hopper',
    },
  },
  {
    id: 'season-pass',
    category: 'planning',
    slugs: {
      en: 'season-pass',
      de: 'jahrespass',
      fr: 'abonnement-annuel',
      it: 'abbonamento-annuale',
      nl: 'jaarkaart',
      es: 'pase-anual',
    },
  },
  {
    id: 'blockout-date',
    category: 'planning',
    slugs: {
      en: 'blockout-date',
      de: 'sperrtag',
      fr: 'date-bloquee',
      it: 'giorno-bloccato',
      nl: 'geblokkeerde-dag',
      es: 'fecha-bloqueada',
    },
  },
  {
    id: 'ai-forecast',
    category: 'planning',
    slugs: {
      en: 'ai-forecast',
      de: 'ki-prognose',
      fr: 'prevision-ia',
      it: 'previsione-ia',
      nl: 'ai-voorspelling',
      es: 'prediccion-ia',
    },
  },
  {
    id: 'ki',
    category: 'planning',
    slugs: {
      en: 'artificial-intelligence',
      de: 'kuenstliche-intelligenz',
      fr: 'intelligence-artificielle',
      it: 'intelligenza-artificiale',
      nl: 'kunstmatige-intelligentie',
      es: 'inteligencia-artificial',
    },
  },
  {
    id: 'realtime-wait-time',
    category: 'wait-times',
    slugs: {
      en: 'live-wait-time',
      de: 'echtzeit-wartezeit',
      fr: 'attente-temps-reel',
      it: 'attesa-tempo-reale',
      nl: 'realtime-wachttijd',
      es: 'espera-tiempo-real',
    },
  },
  {
    id: 'crowd-forecast',
    category: 'crowd-levels',
    slugs: {
      en: 'crowd-forecast',
      de: 'crowd-prognose',
      fr: 'prevision-affluence',
      it: 'previsione-affluenza',
      nl: 'drukte-prognose',
      es: 'prevision-afluencia',
    },
  },
  {
    id: 'mae',
    category: 'planning',
    slugs: {
      en: 'mae',
      de: 'mae',
      fr: 'mae',
      it: 'mae',
      nl: 'mae',
      es: 'mae',
    },
  },
  {
    id: 'rmse',
    category: 'planning',
    slugs: {
      en: 'rmse',
      de: 'rmse',
      fr: 'rmse',
      it: 'rmse',
      nl: 'rmse',
      es: 'rmse',
    },
  },
  {
    id: 'mape',
    category: 'planning',
    slugs: {
      en: 'mape',
      de: 'mape',
      fr: 'mape',
      it: 'mape',
      nl: 'mape',
      es: 'mape',
    },
  },
  {
    id: 'r-squared',
    category: 'planning',
    slugs: {
      en: 'r-squared',
      de: 'r-squared',
      fr: 'r-squared',
      it: 'r-squared',
      nl: 'r-squared',
      es: 'r-squared',
    },
  },
  {
    id: 'opening-hours',
    category: 'park-operations',
    slugs: {
      en: 'opening-hours',
      de: 'oeffnungszeiten',
      fr: 'horaires-ouverture',
      it: 'orari-apertura',
      nl: 'openingstijden',
      es: 'horarios-apertura',
    },
  },
  {
    id: 'wait-time-trend',
    category: 'wait-times',
    slugs: {
      en: 'wait-time-trend',
      de: 'wartezeit-trend',
      fr: 'tendance-attente',
      it: 'tendenza-attesa',
      nl: 'wachttijd-trend',
      es: 'tendencia-espera',
    },
  },
  // ── Attractions ────────────────────────────────────────────────────────────
  {
    id: 'height-requirement',
    category: 'attractions',
    slugs: {
      en: 'height-requirement',
      de: 'mindestgroesse',
      fr: 'taille-minimale',
      it: 'altezza-minima',
      nl: 'minimumlengte',
      es: 'talla-minima',
    },
  },
  {
    id: 'themed-land',
    category: 'attractions',
    slugs: {
      en: 'themed-land',
      de: 'themenbereich',
      fr: 'univers-thematique',
      it: 'area-tematica',
      nl: 'themagebied',
      es: 'zona-tematica',
    },
  },
  {
    id: 'dark-ride',
    category: 'attractions',
    slugs: {
      en: 'dark-ride',
      de: 'dark-ride',
      fr: 'dark-ride',
      it: 'dark-ride',
      nl: 'dark-ride',
      es: 'dark-ride',
    },
  },
  {
    id: 'ride-photo',
    category: 'attractions',
    slugs: {
      en: 'ride-photo',
      de: 'fahrfoto',
      fr: 'photo-de-manege',
      it: 'foto-attrazione',
      nl: 'rit-foto',
      es: 'foto-atraccion',
    },
  },
  // ── Coasters ───────────────────────────────────────────────────────────────
  {
    id: 'airtime',
    category: 'coaster-elements',
    slugs: {
      en: 'airtime',
      de: 'airtime',
      fr: 'airtime',
      it: 'airtime',
      nl: 'airtime',
      es: 'airtime',
    },
  },
  {
    id: 'inversion',
    category: 'coaster-elements',
    slugs: {
      en: 'inversion',
      de: 'inversion',
      fr: 'inversion',
      it: 'inversione',
      nl: 'inversie',
      es: 'inversion',
    },
  },
  {
    id: 'vertical-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'vertical-loop',
      de: 'looping',
      fr: 'looping',
      it: 'looping',
      nl: 'looping',
      es: 'looping',
    },
  },
  {
    id: 'immelmann',
    category: 'coaster-elements',
    slugs: {
      en: 'immelmann',
      de: 'immelmann',
      fr: 'immelmann',
      it: 'immelmann',
      nl: 'immelmann',
      es: 'immelmann',
    },
  },
  {
    id: 'zero-g-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'zero-g-roll',
      de: 'zero-g-roll',
      fr: 'zero-g-roll',
      it: 'zero-g-roll',
      nl: 'zero-g-roll',
      es: 'zero-g-roll',
    },
  },
  {
    id: 'launch-coaster',
    category: 'coasters',
    slugs: {
      en: 'launch-coaster',
      de: 'launch-coaster',
      fr: 'launch-coaster',
      it: 'launch-coaster',
      nl: 'launch-coaster',
      es: 'launch-coaster',
    },
  },
  {
    id: 'wooden-coaster',
    category: 'coasters',
    slugs: {
      en: 'wooden-coaster',
      de: 'holzachterbahn',
      fr: 'montagne-russe-bois',
      it: 'montagna-russa-legno',
      nl: 'houten-achtbaan',
      es: 'montana-rusa-madera',
    },
  },
  {
    id: 'steel-coaster',
    category: 'coasters',
    slugs: {
      en: 'steel-coaster',
      de: 'stahlachterbahn',
      fr: 'montagne-russe-acier',
      it: 'montagna-russa-acciaio',
      nl: 'stalen-achtbaan',
      es: 'montana-rusa-acero',
    },
  },
  {
    id: 'suspended-coaster',
    category: 'coasters',
    slugs: {
      en: 'suspended-coaster',
      de: 'suspended-coaster',
      fr: 'suspended-coaster',
      it: 'suspended-coaster',
      nl: 'suspended-coaster',
      es: 'suspended-coaster',
    },
  },
  {
    id: 'hybrid-coaster',
    category: 'coasters',
    slugs: {
      en: 'hybrid-coaster',
      de: 'hybrid-coaster',
      fr: 'hybrid-coaster',
      it: 'hybrid-coaster',
      nl: 'hybrid-coaster',
      es: 'hybrid-coaster',
    },
  },
  {
    id: 'b-and-m',
    category: 'manufacturers',
    slugs: {
      en: 'b-and-m',
      de: 'b-and-m',
      fr: 'b-and-m',
      it: 'b-and-m',
      nl: 'b-and-m',
      es: 'b-and-m',
    },
  },
  {
    id: 'intamin',
    category: 'manufacturers',
    slugs: {
      en: 'intamin',
      de: 'intamin',
      fr: 'intamin',
      it: 'intamin',
      nl: 'intamin',
      es: 'intamin',
    },
  },
  {
    id: 'mack-rides',
    category: 'manufacturers',
    slugs: {
      en: 'mack-rides',
      de: 'mack-rides',
      fr: 'mack-rides',
      it: 'mack-rides',
      nl: 'mack-rides',
      es: 'mack-rides',
    },
  },
  {
    id: 'rmc',
    category: 'manufacturers',
    slugs: {
      en: 'rmc',
      de: 'rmc',
      fr: 'rmc',
      it: 'rmc',
      nl: 'rmc',
      es: 'rmc',
    },
  },
  {
    id: 'vekoma',
    category: 'manufacturers',
    slugs: {
      en: 'vekoma',
      de: 'vekoma',
      fr: 'vekoma',
      it: 'vekoma',
      nl: 'vekoma',
      es: 'vekoma',
    },
  },
  {
    id: 'gerstlauer',
    category: 'manufacturers',
    slugs: {
      en: 'gerstlauer',
      de: 'gerstlauer',
      fr: 'gerstlauer',
      it: 'gerstlauer',
      nl: 'gerstlauer',
      es: 'gerstlauer',
    },
  },
  {
    id: 'schwarzkopf',
    category: 'manufacturers',
    slugs: {
      en: 'schwarzkopf',
      de: 'schwarzkopf',
      fr: 'schwarzkopf',
      it: 'schwarzkopf',
      nl: 'schwarzkopf',
      es: 'schwarzkopf',
    },
  },
  // ── Coaster Elements ───────────────────────────────────────────────────────
  {
    id: 'lifthill',
    category: 'coaster-elements',
    slugs: {
      en: 'lifthill',
      de: 'lifthill',
      fr: 'lifthill',
      it: 'lifthill',
      nl: 'lifthill',
      es: 'lifthill',
    },
  },
  {
    id: 'first-drop',
    category: 'coaster-elements',
    slugs: {
      en: 'first-drop',
      de: 'first-drop',
      fr: 'first-drop',
      it: 'first-drop',
      nl: 'first-drop',
      es: 'first-drop',
    },
  },
  {
    id: 'airtime-hill',
    category: 'coaster-elements',
    slugs: {
      en: 'airtime-hill',
      de: 'airtime-huegel',
      fr: 'airtime-hill',
      it: 'airtime-hill',
      nl: 'airtime-hill',
      es: 'airtime-hill',
    },
  },
  {
    id: 'helix',
    category: 'coaster-elements',
    slugs: {
      en: 'helix',
      de: 'helix',
      fr: 'helix',
      it: 'helix',
      nl: 'helix',
      es: 'helix',
    },
  },
  {
    id: 'block-brake',
    category: 'coaster-elements',
    slugs: {
      en: 'block-brake',
      de: 'blockbremse',
      fr: 'block-brake',
      it: 'block-brake',
      nl: 'block-brake',
      es: 'block-brake',
    },
  },
  {
    id: 'brake-run',
    category: 'coaster-elements',
    slugs: {
      en: 'brake-run',
      de: 'brake-run',
      fr: 'brake-run',
      it: 'brake-run',
      nl: 'brake-run',
      es: 'brake-run',
    },
  },
  {
    id: 'cobra-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'cobra-roll',
      de: 'cobra-roll',
      fr: 'cobra-roll',
      it: 'cobra-roll',
      nl: 'cobra-roll',
      es: 'cobra-roll',
    },
  },
  {
    id: 'corkscrew',
    category: 'coaster-elements',
    slugs: {
      en: 'corkscrew',
      de: 'korkenzieher',
      fr: 'corkscrew',
      it: 'corkscrew',
      nl: 'corkscrew',
      es: 'corkscrew',
    },
  },
  {
    id: 'dive-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'dive-loop',
      de: 'dive-loop',
      fr: 'dive-loop',
      it: 'dive-loop',
      nl: 'dive-loop',
      es: 'dive-loop',
    },
  },
  {
    id: 'inline-twist',
    category: 'coaster-elements',
    slugs: {
      en: 'inline-twist',
      de: 'inline-twist',
      fr: 'inline-twist',
      it: 'inline-twist',
      nl: 'inline-twist',
      es: 'inline-twist',
    },
  },
  {
    id: 'heartline-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'heartline-roll',
      de: 'heartline-roll',
      fr: 'heartline-roll',
      it: 'heartline-roll',
      nl: 'heartline-roll',
      es: 'heartline-roll',
    },
  },
  {
    id: 'sidewinder',
    category: 'coaster-elements',
    slugs: {
      en: 'sidewinder',
      de: 'sidewinder',
      fr: 'sidewinder',
      it: 'sidewinder',
      nl: 'sidewinder',
      es: 'sidewinder',
    },
  },
  {
    id: 'pretzel-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'pretzel-loop',
      de: 'pretzel-loop',
      fr: 'pretzel-loop',
      it: 'pretzel-loop',
      nl: 'pretzel-loop',
      es: 'pretzel-loop',
    },
  },
  {
    id: 'batwing',
    category: 'coaster-elements',
    slugs: {
      en: 'batwing',
      de: 'batwing',
      fr: 'batwing',
      it: 'batwing',
      nl: 'batwing',
      es: 'batwing',
    },
  },
  {
    id: 'norwegian-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'norwegian-loop',
      de: 'norwegian-loop',
      fr: 'norwegian-loop',
      it: 'norwegian-loop',
      nl: 'norwegian-loop',
      es: 'norwegian-loop',
    },
  },
  {
    id: 'flat-spin',
    category: 'coaster-elements',
    slugs: {
      en: 'flat-spin',
      de: 'flat-spin',
      fr: 'flat-spin',
      it: 'flat-spin',
      nl: 'flat-spin',
      es: 'flat-spin',
    },
  },
  {
    id: 'cutback',
    category: 'coaster-elements',
    slugs: {
      en: 'cutback',
      de: 'cutback',
      fr: 'cutback',
      it: 'cutback',
      nl: 'cutback',
      es: 'cutback',
    },
  },
  {
    id: 'butterfly',
    category: 'coaster-elements',
    slugs: {
      en: 'butterfly',
      de: 'butterfly',
      fr: 'butterfly',
      it: 'butterfly',
      nl: 'butterfly',
      es: 'butterfly',
    },
  },
  {
    id: 'bowtie',
    category: 'coaster-elements',
    slugs: {
      en: 'bowtie',
      de: 'bowtie',
      fr: 'bowtie',
      it: 'bowtie',
      nl: 'bowtie',
      es: 'bowtie',
    },
  },
  {
    id: 'bunnyhop',
    category: 'coaster-elements',
    slugs: {
      en: 'bunnyhop',
      de: 'bunnyhop',
      fr: 'bunnyhop',
      it: 'bunnyhop',
      nl: 'bunnyhop',
      es: 'bunnyhop',
    },
  },
  {
    id: 'stengel-dive',
    category: 'coaster-elements',
    slugs: {
      en: 'stengel-dive',
      de: 'stengel-dive',
      fr: 'stengel-dive',
      it: 'stengel-dive',
      nl: 'stengel-dive',
      es: 'stengel-dive',
    },
  },
  {
    id: 'horseshoe',
    category: 'coaster-elements',
    slugs: {
      en: 'horseshoe',
      de: 'horseshoe',
      fr: 'horseshoe',
      it: 'horseshoe',
      nl: 'horseshoe',
      es: 'horseshoe',
    },
  },
  {
    id: 'predrop',
    category: 'coaster-elements',
    slugs: {
      en: 'predrop',
      de: 'predrop',
      fr: 'predrop',
      it: 'predrop',
      nl: 'predrop',
      es: 'predrop',
    },
  },
  {
    id: 'top-hat',
    category: 'coaster-elements',
    slugs: {
      en: 'top-hat',
      de: 'top-hat',
      fr: 'top-hat',
      it: 'top-hat',
      nl: 'top-hat',
      es: 'top-hat',
    },
  },
  {
    id: 'boomerang',
    category: 'coasters',
    slugs: {
      en: 'boomerang',
      de: 'boomerang',
      fr: 'boomerang',
      it: 'boomerang',
      nl: 'boomerang',
      es: 'boomerang',
    },
  },
  {
    id: 'euro-fighter',
    category: 'coasters',
    slugs: {
      en: 'euro-fighter',
      de: 'euro-fighter',
      fr: 'euro-fighter',
      it: 'euro-fighter',
      nl: 'euro-fighter',
      es: 'euro-fighter',
    },
  },
  {
    id: 'dive-coaster',
    category: 'coasters',
    slugs: {
      en: 'dive-coaster',
      de: 'dive-coaster',
      fr: 'dive-coaster',
      it: 'dive-coaster',
      nl: 'dive-coaster',
      es: 'dive-coaster',
    },
  },
  {
    id: 'credit',
    category: 'planning',
    slugs: {
      en: 'credit',
      de: 'credit',
      fr: 'credit',
      it: 'credit',
      nl: 'credit',
      es: 'credit',
    },
  },
  {
    id: 'pov',
    category: 'ride-experience',
    slugs: {
      en: 'pov',
      de: 'pov',
      fr: 'pov',
      it: 'pov',
      nl: 'pov',
      es: 'pov',
    },
  },
  {
    id: 'vr-coaster',
    category: 'coasters',
    slugs: {
      en: 'vr-coaster',
      de: 'vr-coaster',
      fr: 'vr-coaster',
      it: 'vr-coaster',
      nl: 'vr-coaster',
      es: 'vr-coaster',
    },
  },
  {
    id: 'ert',
    category: 'planning',
    slugs: {
      en: 'ert',
      de: 'ert',
      fr: 'ert',
      it: 'ert',
      nl: 'ert',
      es: 'ert',
    },
  },
  {
    id: 'touring-plan',
    category: 'planning',
    slugs: {
      en: 'touring-plan',
      de: 'touringplan',
      fr: 'plan-visite',
      it: 'piano-visita',
      nl: 'bezoekplan',
      es: 'plan-visita',
    },
  },
  {
    id: 'stacking',
    category: 'park-operations',
    slugs: {
      en: 'stacking',
      de: 'stacking',
      fr: 'stacking',
      it: 'stacking',
      nl: 'stacking',
      es: 'stacking',
    },
  },
  // ── New Coaster Types ──────────────────────────────────────────────────────
  {
    id: 'inverted-coaster',
    category: 'coasters',
    slugs: {
      en: 'inverted-coaster',
      de: 'inverted-coaster',
      fr: 'inverted-coaster',
      it: 'inverted-coaster',
      nl: 'inverted-coaster',
      es: 'inverted-coaster',
    },
  },
  {
    id: 'wing-coaster',
    category: 'coasters',
    slugs: {
      en: 'wing-coaster',
      de: 'wing-coaster',
      fr: 'wing-coaster',
      it: 'wing-coaster',
      nl: 'wing-coaster',
      es: 'wing-coaster',
    },
  },
  {
    id: 'spinning-coaster',
    category: 'coasters',
    slugs: {
      en: 'spinning-coaster',
      de: 'spinning-coaster',
      fr: 'spinning-coaster',
      it: 'spinning-coaster',
      nl: 'spinning-coaster',
      es: 'spinning-coaster',
    },
  },
  {
    id: 'xtreme-spinning-coaster',
    category: 'coasters',
    slugs: {
      en: 'xtreme-spinning-coaster',
      de: 'xtreme-spinning-coaster',
      fr: 'xtreme-spinning-coaster',
      it: 'xtreme-spinning-coaster',
      nl: 'xtreme-spinning-coaster',
      es: 'xtreme-spinning-coaster',
    },
  },
  {
    id: 'hyper-coaster',
    category: 'coasters',
    slugs: {
      en: 'hyper-coaster',
      de: 'hyper-coaster',
      fr: 'hyper-coaster',
      it: 'hyper-coaster',
      nl: 'hyper-coaster',
      es: 'hyper-coaster',
    },
  },
  {
    id: 'giga-coaster',
    category: 'coasters',
    slugs: {
      en: 'giga-coaster',
      de: 'giga-coaster',
      fr: 'giga-coaster',
      it: 'giga-coaster',
      nl: 'giga-coaster',
      es: 'giga-coaster',
    },
  },
  // ── New Coaster Elements ───────────────────────────────────────────────────
  {
    id: 'overbank',
    category: 'coaster-elements',
    slugs: {
      en: 'overbank',
      de: 'uebergeneigte-kurve', // German: "übergeneigte Kurve" — standard DE community term
      fr: 'overbank',
      it: 'overbank',
      nl: 'overbank',
      es: 'overbank',
    },
  },
  {
    id: 'trim-brake',
    category: 'coaster-elements',
    slugs: {
      en: 'trim-brake',
      de: 'trim-bremse', // German: "Trim-Bremse" — standard DE community term
      fr: 'trim-brake',
      it: 'trim-brake',
      nl: 'trim-brake',
      es: 'trim-brake',
    },
  },
  {
    id: 'rollback',
    category: 'coaster-elements',
    slugs: {
      en: 'rollback',
      de: 'rollback',
      fr: 'rollback',
      it: 'rollback',
      nl: 'rollback',
      es: 'rollback',
    },
  },
  {
    id: 'g-force',
    category: 'coaster-elements',
    slugs: {
      en: 'g-force',
      de: 'g-kraft',
      fr: 'force-g',
      it: 'forza-g',
      nl: 'g-kracht',
      es: 'fuerza-g',
    },
  },
  {
    id: 'greyout',
    category: 'ride-experience',
    slugs: {
      en: 'greyout',
      de: 'greyout',
      fr: 'greyout',
      it: 'greyout',
      nl: 'greyout',
      es: 'greyout',
    },
  },
  {
    id: 'grey-zone',
    category: 'coaster-elements',
    slugs: {
      en: 'grey-zone',
      de: 'grauzone',
      fr: 'zone-grise',
      it: 'zona-grigia',
      nl: 'grijze-zone',
      es: 'zona-gris',
    },
  },
  {
    id: 'lateral-gs',
    category: 'coaster-elements',
    slugs: {
      en: 'lateral-gs',
      de: 'laterale-g-kraefte',
      fr: 'forces-laterales',
      it: 'forze-laterali',
      nl: 'laterale-g-krachten',
      es: 'fuerzas-laterales',
    },
  },
  {
    id: 'ejector-airtime',
    category: 'coaster-elements',
    slugs: {
      en: 'ejector-airtime',
      de: 'ejector-airtime',
      fr: 'ejector-airtime',
      it: 'ejector-airtime',
      nl: 'ejector-airtime',
      es: 'ejector-airtime',
    },
  },
  {
    id: 'floater-airtime',
    category: 'coaster-elements',
    slugs: {
      en: 'floater-airtime',
      de: 'floater-airtime',
      fr: 'floater-airtime',
      it: 'floater-airtime',
      nl: 'floater-airtime',
      es: 'floater-airtime',
    },
  },
  {
    id: 'hangtime',
    category: 'coaster-elements',
    slugs: {
      en: 'hangtime',
      de: 'hangtime',
      fr: 'hangtime',
      it: 'hangtime',
      nl: 'hangtime',
      es: 'hangtime',
    },
  },
  // ── Roller Coaster Element (meta term) ────────────────────────────────────
  {
    id: 'roller-coaster-element',
    category: 'coaster-elements',
    slugs: {
      en: 'roller-coaster-element',
      de: 'achterbahn-element',
      fr: 'element-montagnes-russes',
      it: 'elemento-montagne-russe',
      nl: 'achtbaanelement',
      es: 'elemento-montana-rusa',
    },
  },
  // ── New Attractions ────────────────────────────────────────────────────────
  {
    id: 'animatronics',
    category: 'attractions',
    slugs: {
      en: 'animatronics',
      de: 'animatronics',
      fr: 'animatronique', // French: established loanword, Wikipedia "Animatronique"
      it: 'animatronica', // Italian: established form
      nl: 'animatronics',
      es: 'animatronica', // Spanish: Wikipedia "Animatrónica"
    },
  },
  {
    id: 'trackless-ride',
    category: 'attractions',
    slugs: {
      en: 'trackless-ride',
      de: 'trackless-ride',
      fr: 'trackless-ride',
      it: 'trackless-ride',
      nl: 'trackless-ride',
      es: 'trackless-ride',
    },
  },
  // ── Ride Experience ────────────────────────────────────────────────────────
  {
    id: 'front-row',
    category: 'ride-experience',
    slugs: {
      en: 'front-row',
      de: 'erste-reihe',
      fr: 'premiere-rangee',
      it: 'prima-fila',
      nl: 'eerste-rij',
      es: 'primera-fila',
    },
  },
  {
    id: 'back-row',
    category: 'ride-experience',
    slugs: {
      en: 'back-row',
      de: 'letzte-reihe',
      fr: 'derniere-rangee',
      it: 'ultima-fila',
      nl: 'laatste-rij',
      es: 'ultima-fila',
    },
  },
  {
    id: 'middle-row',
    category: 'ride-experience',
    slugs: {
      en: 'middle-row',
      de: 'mittlere-reihe',
      fr: 'rangee-centrale',
      it: 'fila-centrale',
      nl: 'middelste-rij',
      es: 'fila-central',
    },
  },
  {
    id: 'ride-cart',
    category: 'ride-experience',
    slugs: {
      en: 'ride-cart',
      de: 'fahrwagen',
      fr: 'wagon',
      it: 'vagone',
      nl: 'wagentje',
      es: 'carrito',
    },
  },
  {
    id: 'lap-bar',
    category: 'ride-experience',
    slugs: {
      en: 'lap-bar',
      de: 'schossbugel',
      fr: 'barre-genoux',
      it: 'barra-inguine',
      nl: 'schootbeugel',
      es: 'barra-cintura',
    },
  },
  {
    id: 'shoulder-harness',
    category: 'ride-experience',
    slugs: {
      en: 'shoulder-harness',
      de: 'schulterbuegel',
      fr: 'harnais-epaules',
      it: 'imbracatura-spalle',
      nl: 'schouderbeugel',
      es: 'arnés-hombros',
    },
  },
  // ── Shopping ───────────────────────────────────────────────────────────────
  {
    id: 'souvenir',
    category: 'shopping',
    slugs: {
      en: 'souvenir',
      de: 'andenken',
      fr: 'souvenir',
      it: 'ricordo',
      nl: 'souvenir',
      es: 'recuerdo',
    },
  },
  {
    id: 'merchandise',
    category: 'shopping',
    slugs: {
      en: 'merchandise',
      de: 'merchandise',
      fr: 'merchandise',
      it: 'merchandise',
      nl: 'merchandise',
      es: 'merchandise',
    },
  },
  {
    id: 'gift-shop',
    category: 'shopping',
    slugs: {
      en: 'gift-shop',
      de: 'geschenkeladen',
      fr: 'boutique-souvenirs',
      it: 'negozio-souvenir',
      nl: 'cadeauwinkel',
      es: 'tienda-regalos',
    },
  },
  {
    id: 'park-exclusive',
    category: 'shopping',
    slugs: {
      en: 'park-exclusive',
      de: 'parkexklusiv',
      fr: 'exclusif-parc',
      it: 'esclusiva-parco',
      nl: 'parkexclusief',
      es: 'exclusiva-parque',
    },
  },
  // ── New Coaster Types (P1/P2) ─────────────────────────────────────────────
  {
    id: 'flying-coaster',
    category: 'coasters',
    slugs: {
      en: 'flying-coaster',
      de: 'flying-coaster',
      fr: 'flying-coaster',
      it: 'flying-coaster',
      nl: 'flying-coaster',
      es: 'flying-coaster',
    },
  },
  {
    id: 'mine-train',
    category: 'coasters',
    slugs: {
      en: 'mine-train',
      de: 'mine-train',
      fr: 'train-mine',
      it: 'mine-train',
      nl: 'mijntrein',
      es: 'tren-minero',
    },
  },
  {
    id: 'terrain-coaster',
    category: 'coasters',
    slugs: {
      en: 'terrain-coaster',
      de: 'terrain-coaster',
      fr: 'terrain-coaster',
      it: 'terrain-coaster',
      nl: 'terrain-coaster',
      es: 'terrain-coaster',
    },
  },
  {
    id: 'floorless-coaster',
    category: 'coasters',
    slugs: {
      en: 'floorless-coaster',
      de: 'floorless-coaster',
      fr: 'floorless-coaster',
      it: 'floorless-coaster',
      nl: 'floorless-coaster',
      es: 'floorless-coaster',
    },
  },
  {
    id: 'arrow-dynamics',
    category: 'manufacturers',
    slugs: {
      en: 'arrow-dynamics',
      de: 'arrow-dynamics',
      fr: 'arrow-dynamics',
      it: 'arrow-dynamics',
      nl: 'arrow-dynamics',
      es: 'arrow-dynamics',
    },
  },
  {
    id: 'gci',
    category: 'manufacturers',
    slugs: {
      en: 'great-coasters-international',
      de: 'gci',
      fr: 'gci',
      it: 'gci',
      nl: 'gci',
      es: 'gci',
    },
  },
  {
    id: 'premier-rides',
    category: 'manufacturers',
    slugs: {
      en: 'premier-rides',
      de: 'premier-rides',
      fr: 'premier-rides',
      it: 'premier-rides',
      nl: 'premier-rides',
      es: 'premier-rides',
    },
  },
  {
    id: 'maurer-rides',
    category: 'manufacturers',
    slugs: {
      en: 'maurer-rides',
      de: 'maurer-rides',
      fr: 'maurer-rides',
      it: 'maurer-rides',
      nl: 'maurer-rides',
      es: 'maurer-rides',
    },
  },
  {
    id: 'zamperla',
    category: 'manufacturers',
    slugs: {
      en: 'zamperla',
      de: 'zamperla',
      fr: 'zamperla',
      it: 'zamperla',
      nl: 'zamperla',
      es: 'zamperla',
    },
  },
  {
    id: 's-and-s-worldwide',
    category: 'manufacturers',
    slugs: {
      en: 's-and-s-worldwide',
      de: 's-and-s-worldwide',
      fr: 's-and-s-worldwide',
      it: 's-and-s-worldwide',
      nl: 's-and-s-worldwide',
      es: 's-and-s-worldwide',
    },
  },
  {
    id: 'zierer',
    category: 'manufacturers',
    slugs: {
      en: 'zierer',
      de: 'zierer',
      fr: 'zierer',
      it: 'zierer',
      nl: 'zierer',
      es: 'zierer',
    },
  },
  // ── New Coaster Elements (P1/P2) ───────────────────────────────────────────
  {
    id: 'stall',
    category: 'coaster-elements',
    slugs: {
      en: 'stall',
      de: 'stall',
      fr: 'stall',
      it: 'stall',
      nl: 'stall',
      es: 'stall',
    },
  },
  {
    id: 'wave-turn',
    category: 'coaster-elements',
    slugs: {
      en: 'wave-turn',
      de: 'wave-turn',
      fr: 'wave-turn',
      it: 'wave-turn',
      nl: 'wave-turn',
      es: 'wave-turn',
    },
  },
  {
    id: 'high-five',
    category: 'coaster-elements',
    slugs: {
      en: 'high-five',
      de: 'high-five',
      fr: 'high-five',
      it: 'high-five',
      nl: 'high-five',
      es: 'high-five',
    },
  },
  // ── New Crowd/Planning (P1/P2) ─────────────────────────────────────────────
  {
    id: 'shoulder-season',
    category: 'crowd-levels',
    slugs: {
      en: 'shoulder-season',
      de: 'zwischensaison',
      fr: 'intersaison',
      it: 'mezza-stagione',
      nl: 'tussenseizoen',
      es: 'temporada-intermedia',
    },
  },
  {
    id: 'school-holiday',
    category: 'crowd-levels',
    slugs: {
      en: 'school-holiday',
      de: 'schulferien',
      fr: 'vacances-scolaires',
      it: 'vacanze-scolastiche',
      nl: 'schoolvakantie',
      es: 'vacaciones-escolares',
    },
  },
  {
    id: 'photo-pass',
    category: 'planning',
    slugs: {
      en: 'photo-pass',
      de: 'fotopass',
      fr: 'pass-photo',
      it: 'fotopass',
      nl: 'fotopass',
      es: 'fotopass',
    },
  },
  {
    id: 'accessibility-pass',
    category: 'planning',
    slugs: {
      en: 'accessibility-pass',
      de: 'barrierefreiheit-pass',
      fr: 'pass-accessibilite',
      it: 'pass-accessibilita',
      nl: 'toegankelijkheidspas',
      es: 'pase-accesibilidad',
    },
  },
  // ── New Attractions (P1/P2) ────────────────────────────────────────────────
  {
    id: 'motion-simulator',
    category: 'attractions',
    slugs: {
      en: 'motion-simulator',
      de: 'simulator-attraktion',
      fr: 'simulateur',
      it: 'simulatore',
      nl: 'bewegingssimulator',
      es: 'simulador',
    },
  },
  {
    id: 'character-meet-and-greet',
    category: 'attractions',
    slugs: {
      en: 'character-meet-and-greet',
      de: 'charakter-treffen',
      fr: 'rencontre-personnage',
      it: 'incontro-personaggio',
      nl: 'karakterontmoeting',
      es: 'encuentro-personaje',
    },
  },
  {
    id: 'pre-show',
    category: 'attractions',
    slugs: {
      en: 'pre-show',
      de: 'vorshow',
      fr: 'avant-spectacle',
      it: 'pre-show',
      nl: 'voorshow',
      es: 'pre-show',
    },
  },
  // ── Dining ─────────────────────────────────────────────────────────────────
  {
    id: 'quick-service',
    category: 'dining',
    slugs: {
      en: 'quick-service',
      de: 'schnellrestaurant',
      fr: 'restauration-rapide',
      it: 'self-service',
      nl: 'snelrestaurant',
      es: 'servicio-rapido',
    },
  },
  {
    id: 'table-service',
    category: 'dining',
    slugs: {
      en: 'table-service',
      de: 'tischservice',
      fr: 'service-a-table',
      it: 'servizio-al-tavolo',
      nl: 'tafelservice',
      es: 'servicio-de-mesa',
    },
  },
  {
    id: 'character-dining',
    category: 'dining',
    slugs: {
      en: 'character-dining',
      de: 'charakter-dinner',
      fr: 'repas-personnages',
      it: 'cena-con-personaggi',
      nl: 'karakterdiner',
      es: 'cena-con-personajes',
    },
  },
  // ── New Attractions ────────────────────────────────────────────────────────
  {
    id: 'flat-ride',
    category: 'attractions',
    slugs: {
      en: 'flat-ride',
      de: 'flat-ride',
      fr: 'manege-plat',
      it: 'flat-ride',
      nl: 'flat-ride',
      es: 'atraccion-plana',
    },
  },
  {
    id: 'water-ride',
    category: 'attractions',
    slugs: {
      en: 'water-ride',
      de: 'wasserfahrt',
      fr: 'attraction-aquatique',
      it: 'attrazione-acquatica',
      nl: 'waterattractie',
      es: 'atraccion-acuatica',
    },
  },
  {
    id: 'live-show',
    category: 'attractions',
    slugs: {
      en: 'live-show',
      de: 'live-show',
      fr: 'spectacle-vivant',
      it: 'spettacolo-dal-vivo',
      nl: 'live-show',
      es: 'espectaculo-en-vivo',
    },
  },
  // ── New Attractions (P2) ───────────────────────────────────────────────────
  {
    id: 'drop-tower',
    category: 'attractions',
    slugs: {
      en: 'drop-tower',
      de: 'drop-tower',
      fr: 'tour-de-chute',
      it: 'torre-di-caduta',
      nl: 'drop-tower',
      es: 'torre-de-caida',
    },
  },
  {
    id: 'log-flume',
    category: 'attractions',
    slugs: {
      en: 'log-flume',
      de: 'wildwasserbahn',
      fr: 'toboggan-aquatique',
      it: 'fiume-dei-tronchi',
      nl: 'wildwaterbaan',
      es: 'descenso-de-troncos',
    },
  },
  {
    id: 'river-rapids',
    category: 'attractions',
    slugs: {
      en: 'river-rapids',
      de: 'wildwasser-rafting',
      fr: 'rapides-riviere',
      it: 'rapide-del-fiume',
      nl: 'wildwaterrit',
      es: 'rrapids-rio',
    },
  },
  {
    id: 'swing-ride',
    category: 'attractions',
    slugs: {
      en: 'swing-ride',
      de: 'kettenkarussell',
      fr: 'chaises-volantes',
      it: 'giostra-a-catene',
      nl: 'zweefmolen',
      es: 'sillas-voladoras',
    },
  },
  // ── New Coasters (P2) ─────────────────────────────────────────────────────
  {
    id: 'racing-coaster',
    category: 'coasters',
    slugs: {
      en: 'racing-coaster',
      de: 'racing-coaster',
      fr: 'montagnes-russes-course',
      it: 'racing-coaster',
      nl: 'racing-coaster',
      es: 'montaña-rusa-carrera',
    },
  },
  // ── New Dining (P2) ───────────────────────────────────────────────────────
  {
    id: 'dining-reservation',
    category: 'dining',
    slugs: {
      en: 'dining-reservation',
      de: 'tischreservierung',
      fr: 'reservation-restaurant',
      it: 'prenotazione-ristorante',
      nl: 'tafelreservering',
      es: 'reserva-restaurante',
    },
  },
  {
    id: 'mobile-ordering',
    category: 'dining',
    slugs: {
      en: 'mobile-ordering',
      de: 'mobile-bestellung',
      fr: 'commande-mobile',
      it: 'ordine-mobile',
      nl: 'mobiel-bestellen',
      es: 'pedido-movil',
    },
  },
  {
    id: 'food-court',
    category: 'dining',
    slugs: {
      en: 'food-court',
      de: 'food-court',
      fr: 'food-court',
      it: 'food-court',
      nl: 'food-court',
      es: 'food-court',
    },
  },
  // ── New Park Operations (P2) ──────────────────────────────────────────────
  {
    id: 'capacity-closure',
    category: 'park-operations',
    slugs: {
      en: 'capacity-closure',
      de: 'kapazitaetsschliessung',
      fr: 'fermeture-capacite',
      it: 'chiusura-capacita',
      nl: 'capaciteitssluiting',
      es: 'cierre-por-capacidad',
    },
  },
  {
    id: 'zero-g-winder',
    category: 'coaster-elements',
    slugs: {
      en: 'zero-g-winder',
      de: 'zero-g-winder',
      fr: 'zero-g-winder',
      it: 'zero-g-winder',
      nl: 'zero-g-winder',
      es: 'zero-g-winder',
    },
  },
  {
    id: 'banana-roll',
    category: 'coaster-elements',
    slugs: {
      en: 'banana-roll',
      de: 'banana-roll',
      fr: 'banana-roll',
      it: 'banana-roll',
      nl: 'banana-roll',
      es: 'banana-roll',
    },
  },
  {
    id: 'inclined-loop',
    category: 'coaster-elements',
    slugs: {
      en: 'inclined-loop',
      de: 'geneigter-looping',
      fr: 'looping-incline',
      it: 'looping-inclinato',
      nl: 'gekantelde-looping',
      es: 'looping-inclinado',
    },
  },
  {
    id: 'sea-serpent',
    category: 'coaster-elements',
    slugs: {
      en: 'sea-serpent',
      de: 'sea-serpent',
      fr: 'sea-serpent',
      it: 'sea-serpent',
      nl: 'sea-serpent',
      es: 'sea-serpent',
    },
  },
  {
    id: 'barrel-roll-drop',
    category: 'coaster-elements',
    slugs: {
      en: 'barrel-roll-drop',
      de: 'barrel-roll-drop',
      fr: 'barrel-roll-drop',
      it: 'barrel-roll-drop',
      nl: 'barrel-roll-drop',
      es: 'barrel-roll-drop',
    },
  },
  {
    id: 'mcbr',
    category: 'coaster-elements',
    slugs: {
      en: 'mcbr',
      de: 'mcbr',
      fr: 'mcbr',
      it: 'mcbr',
      nl: 'mcbr',
      es: 'mcbr',
    },
  },
  {
    id: 'interlocking-loops',
    category: 'coaster-elements',
    slugs: {
      en: 'interlocking-loops',
      de: 'verschlungene-loops',
      fr: 'loops-entrelaces',
      it: 'loops-intrecciati',
      nl: 'verstrengelde-loops',
      es: 'loops-entrelazados',
    },
  },
  {
    id: 'anti-rollback',
    category: 'coaster-elements',
    slugs: {
      en: 'anti-rollback',
      de: 'anti-rollback',
      fr: 'anti-rollback',
      it: 'anti-rollback',
      nl: 'anti-rollback',
      es: 'anti-rollback',
    },
  },
  {
    id: 'head-choppers',
    category: 'coaster-elements',
    slugs: {
      en: 'head-choppers',
      de: 'head-choppers',
      fr: 'head-choppers',
      it: 'head-choppers',
      nl: 'head-choppers',
      es: 'head-choppers',
    },
  },
  {
    id: 'stapling',
    category: 'ride-experience',
    slugs: {
      en: 'stapling',
      de: 'stapling',
      fr: 'stapling',
      it: 'stapling',
      nl: 'stapling',
      es: 'stapling',
    },
  },
  {
    id: 'valleying',
    category: 'park-operations',
    slugs: {
      en: 'valleying',
      de: 'valleying',
      fr: 'valleying',
      it: 'valleying',
      nl: 'valleying',
      es: 'valleying',
    },
  },
  {
    id: 'wild-mouse',
    category: 'coasters',
    slugs: {
      en: 'wild-mouse',
      de: 'wilde-maus',
      fr: 'wild-mouse',
      it: 'wild-mouse',
      nl: 'wild-mouse',
      es: 'wild-mouse',
    },
  },
  {
    id: 'fourth-dimension-coaster',
    category: 'coasters',
    slugs: {
      en: 'fourth-dimension-coaster',
      de: 'fourth-dimension-coaster',
      fr: 'fourth-dimension-coaster',
      it: 'fourth-dimension-coaster',
      nl: 'fourth-dimension-coaster',
      es: 'fourth-dimension-coaster',
    },
  },
  {
    id: 'out-and-back',
    category: 'coasters',
    slugs: {
      en: 'out-and-back',
      de: 'out-and-back',
      fr: 'out-and-back',
      it: 'out-and-back',
      nl: 'out-and-back',
      es: 'out-and-back',
    },
  },
  {
    id: 'twister-coaster',
    category: 'coasters',
    slugs: {
      en: 'twister-coaster',
      de: 'twister-coaster',
      fr: 'twister-coaster',
      it: 'twister-coaster',
      nl: 'twister-coaster',
      es: 'twister-coaster',
    },
  },
  {
    id: 'seasonal-attraction',
    category: 'attractions',
    slugs: {
      en: 'seasonal-attraction',
      de: 'saisonale-attraktion',
      fr: 'attraction-saisonniere',
      it: 'attrazione-stagionale',
      nl: 'seizoensattractie',
      es: 'atraccion-de-temporada',
    },
  },
];
