import type { AbstractIntlMessages } from 'next-intl';

/**
 * Narrowing helpers for the messages that reach the browser. Everything handed to
 * `<NextIntlClientProvider>` is serialized into the page's HTML, so the locale layout ships only
 * the chrome namespaces and each route adds its delta through `<RouteMessages>`, merged on the
 * client. Both lists are generated by `pnpm generate:route-namespaces`. See
 * docs/rules/translations-are-routed-not-bundled.md.
 */

/**
 * Narrows a message tree to the given namespaces, keeping key paths so
 * `useTranslations('seo.faq')` still resolves. An entry is a top-level namespace or a dotted path
 * such as `'contribute.form'`; one that does not exist is skipped.
 */
export function pickMessages(
  messages: AbstractIntlMessages,
  namespaces: readonly string[]
): AbstractIntlMessages {
  const picked: Record<string, unknown> = {};

  for (const namespace of namespaces) {
    const segments = namespace.split('.');

    let source: unknown = messages;
    for (const segment of segments) {
      if (typeof source !== 'object' || source === null) {
        source = undefined;
        break;
      }
      source = (source as Record<string, unknown>)[segment];
    }
    if (source === undefined) continue;

    let target = picked;
    for (const segment of segments.slice(0, -1)) {
      const existing = target[segment];
      target[segment] =
        typeof existing === 'object' && existing !== null
          ? existing
          : ({} as Record<string, unknown>);
      target = target[segment] as Record<string, unknown>;
    }
    target[segments[segments.length - 1]] = source;
  }

  return picked as AbstractIntlMessages;
}

/**
 * Deep-merges a delta onto a base message tree, returning a new object. A plain spread would let
 * a route's `parks` replace the layout's `parks.status`, which next-intl reports only at render
 * time as MISSING_MESSAGE. Leaves and arrays are taken from `delta`.
 */
export function mergeMessages(
  base: AbstractIntlMessages,
  delta: AbstractIntlMessages
): AbstractIntlMessages {
  const merged: Record<string, unknown> = { ...(base as Record<string, unknown>) };

  for (const [key, value] of Object.entries(delta as Record<string, unknown>)) {
    const existing = merged[key];
    const bothAreBranches =
      typeof existing === 'object' &&
      existing !== null &&
      !Array.isArray(existing) &&
      typeof value === 'object' &&
      value !== null &&
      !Array.isArray(value);

    merged[key] = bothAreBranches
      ? mergeMessages(existing as AbstractIntlMessages, value as AbstractIntlMessages)
      : value;
  }

  return merged as AbstractIntlMessages;
}
