// Generated by `pnpm generate:route-namespaces` — do not edit by hand.
// Re-run it whenever a component moves across the client boundary;
// `pnpm check:client-messages` fails when this file has drifted.

/**
 * Namespaces the layout chrome reads — header, footer, search, language banner.
 * Every route pays these, so they stay in the root `NextIntlClientProvider`.
 */
export const LAYOUT_MESSAGE_NAMESPACES = [
  'common',
  'favorites',
  'feedback',
  'footer',
  'geo',
  'navigation',
  'parks.crowdLevels',
  'parks.status',
  'search',
  'theme',
] as const;

/**
 * What each route needs ON TOP of {@link LAYOUT_MESSAGE_NAMESPACES}.
 * An empty list means the chrome set already covers the route.
 */
export const ROUTE_MESSAGE_NAMESPACES = {
  '/': ['attractions', 'home', 'homeStory.bestTime', 'nearby', 'parkCard', 'parks', 'stats'],
  '/best-time-to-visit': ['nearby', 'parkCard'],
  '/blog': ['nearby', 'parkCard'],
  '/blog/[slug]': ['attractions', 'blog', 'nearby', 'parkCard', 'parks', 'share'],
  '/blog/authors/[author]': ['nearby', 'parkCard'],
  '/blog/category/[...path]': ['nearby', 'parkCard'],
  '/blog/tag/[tag]': ['nearby', 'parkCard'],
  '/contribute': [
    'contribute.dropzone',
    'contribute.error',
    'contribute.form',
    'contribute.picker',
  ],
  '/contribute/thanks': [],
  '/datenschutz': ['datenschutz.analyticsOptOut'],
  '/fancast': ['home', 'nearby', 'parkCard'],
  '/glossary': ['glossary'],
  '/glossary/[term]': ['nearby', 'parkCard'],
  '/how-park-fan-works': ['attractions', 'nearby', 'parkCard', 'parks'],
  '/impressum': [],
  '/maintenance': [],
  '/parks': ['explore', 'nearby'],
  '/parks/[continent]': ['explore', 'nearby'],
  '/parks/[continent]/[country]': ['nearby', 'parkCard'],
  '/parks/[continent]/[country]/[city]': ['nearby', 'parkCard'],
  '/parks/[continent]/[country]/[city]/[park]': [
    'attractions',
    'nearby',
    'parkCard',
    'parks',
    'seo.faq',
    'share',
  ],
  '/parks/[continent]/[country]/[city]/[park]/[attraction]': [
    'attractions',
    'nearby',
    'parks',
    'share',
  ],
  '/parks/[continent]/[country]/[city]/[park]/wait-time-calendar/[[...date]]': [
    'attractions.historyLegend',
    'nearby',
    'parkCard',
    'parks',
    'share',
  ],
  '/search': [],
  '/ui': ['attractions', 'nearby', 'parkCard', 'parks', 'stats'],
} as const;

/**
 * Namespaces fetched on demand by a lazy boundary rather than shipped in the
 * page payload (see `LAZY_MESSAGE_BOUNDARIES` in
 * `lib/i18n/route-namespaces.mjs`).
 */
export const LAZY_CHUNK_NAMESPACES = ['attractions', 'parks'] as const;

export type RouteMessageKey = keyof typeof ROUTE_MESSAGE_NAMESPACES;
