import type { AbstractIntlMessages } from 'next-intl';
import type { Locale } from '@/i18n/config';

/**
 * Lazy, per-locale loader for the message namespaces a lazy boundary fetches
 * instead of taking them from the page payload.
 *
 * Same shape as `lib/glossary/client-data-loader.ts` and for the same reason:
 * static dynamic imports (one per locale) so every bundler emits a discrete
 * chunk and only the requested language is fetched. A template-literal import
 * would work too but is fuzzier to trace.
 *
 * The modules are generated by `pnpm generate:message-chunks` in prebuild.
 */
function importLocale(locale: Locale): Promise<{ MESSAGES: AbstractIntlMessages }> {
  switch (locale) {
    case 'de':
      return import('./message-chunks/de');
    case 'fr':
      return import('./message-chunks/fr');
    case 'it':
      return import('./message-chunks/it');
    case 'nl':
      return import('./message-chunks/nl');
    case 'es':
      return import('./message-chunks/es');
    case 'en':
    default:
      return import('./message-chunks/en');
  }
}

const resolved = new Map<Locale, AbstractIntlMessages>();
const inflight = new Map<Locale, Promise<AbstractIntlMessages | null>>();

/** Already-loaded chunk for a locale, or `undefined` when it has not been fetched yet. */
export function getLoadedMessageChunk(locale: Locale): AbstractIntlMessages | undefined {
  return resolved.get(locale);
}

/**
 * Kicks off the (deduplicated) fetch for a locale's chunk.
 *
 * Resolves to `null` when the chunk cannot be loaded — the caller keeps showing
 * its placeholder rather than rendering raw message keys.
 */
export function loadMessageChunk(locale: Locale): Promise<AbstractIntlMessages | null> {
  const alreadyResolved = resolved.get(locale);
  if (alreadyResolved) return Promise.resolve(alreadyResolved);

  const pending = inflight.get(locale);
  if (pending) return pending;

  const promise = importLocale(locale)
    .then((module) => {
      resolved.set(locale, module.MESSAGES);
      return module.MESSAGES;
    })
    .catch(() => null)
    .finally(() => {
      inflight.delete(locale);
    });

  inflight.set(locale, promise);
  return promise;
}
