// Auto-generated by scripts/generate-media-manifest.mjs
// DO NOT EDIT MANUALLY — edit the sidecar JSON next to the image and re-run
// 'pnpm generate:media' (also runs in prebuild).

import type { MediaParkRef } from './types';

/** Park reference data for every park the media database has images of, by path. */
export const MEDIA_PARKS: Record<string, MediaParkRef> = {
  "europe/belgium/kasterlee/bobbejaanland": {
    "slug": "bobbejaanland",
    "name": "Bobbejaanland",
    "city": "Kasterlee",
    "countrySlug": "belgium",
    "path": "europe/belgium/kasterlee/bobbejaanland"
  },
  "europe/belgium/wavre/walibi-belgium": {
    "slug": "walibi-belgium",
    "name": "Walibi Belgium",
    "city": "Wavre",
    "countrySlug": "belgium",
    "path": "europe/belgium/wavre/walibi-belgium"
  },
  "europe/france/paris/disneyland-park": {
    "slug": "disneyland-park",
    "name": "Disneyland Park",
    "city": "Paris",
    "countrySlug": "france",
    "path": "europe/france/paris/disneyland-park"
  },
  "europe/germany/bottrop/movie-park-germany": {
    "slug": "movie-park-germany",
    "name": "Movie Park Germany",
    "city": "Bottrop",
    "countrySlug": "germany",
    "path": "europe/germany/bottrop/movie-park-germany"
  },
  "europe/germany/bruehl/phantasialand": {
    "slug": "phantasialand",
    "name": "Phantasialand",
    "city": "Brühl",
    "countrySlug": "germany",
    "path": "europe/germany/bruehl/phantasialand"
  },
  "europe/germany/rust/europa-park": {
    "slug": "europa-park",
    "name": "Europa-Park",
    "city": "Rust",
    "countrySlug": "germany",
    "path": "europe/germany/rust/europa-park"
  },
  "europe/netherlands/biddinghuizen/walibi-holland": {
    "slug": "walibi-holland",
    "name": "Walibi Holland",
    "city": "Biddinghuizen",
    "countrySlug": "netherlands",
    "path": "europe/netherlands/biddinghuizen/walibi-holland"
  },
  "europe/netherlands/kaatsheuvel/efteling": {
    "slug": "efteling",
    "name": "Efteling",
    "city": "Kaatsheuvel",
    "countrySlug": "netherlands",
    "path": "europe/netherlands/kaatsheuvel/efteling"
  },
  "europe/netherlands/sevenum/attractiepark-toverland": {
    "slug": "attractiepark-toverland",
    "name": "Attractiepark Toverland",
    "city": "Sevenum",
    "countrySlug": "netherlands",
    "path": "europe/netherlands/sevenum/attractiepark-toverland"
  },
  "north-america/united-states/anaheim/disneyland-park": {
    "slug": "disneyland-park",
    "name": "Disneyland Park",
    "city": "Anaheim",
    "countrySlug": "united-states",
    "path": "north-america/united-states/anaheim/disneyland-park"
  },
  "north-america/united-states/orlando/disneys-animal-kingdom-theme-park": {
    "slug": "disneys-animal-kingdom-theme-park",
    "name": "Disney's Animal Kingdom Theme Park",
    "city": "Orlando",
    "countrySlug": "united-states",
    "path": "north-america/united-states/orlando/disneys-animal-kingdom-theme-park"
  },
  "north-america/united-states/orlando/disneys-hollywood-studios": {
    "slug": "disneys-hollywood-studios",
    "name": "Disney's Hollywood Studios",
    "city": "Orlando",
    "countrySlug": "united-states",
    "path": "north-america/united-states/orlando/disneys-hollywood-studios"
  },
  "north-america/united-states/orlando/epcot": {
    "slug": "epcot",
    "name": "EPCOT",
    "city": "Orlando",
    "countrySlug": "united-states",
    "path": "north-america/united-states/orlando/epcot"
  },
  "north-america/united-states/orlando/magic-kingdom-park": {
    "slug": "magic-kingdom-park",
    "name": "Magic Kingdom Park",
    "city": "Orlando",
    "countrySlug": "united-states",
    "path": "north-america/united-states/orlando/magic-kingdom-park"
  },
  "north-america/united-states/orlando/universal-islands-of-adventure": {
    "slug": "universal-islands-of-adventure",
    "name": "Universal Islands of Adventure",
    "city": "Orlando",
    "countrySlug": "united-states",
    "path": "north-america/united-states/orlando/universal-islands-of-adventure"
  }
};

/**
 * Default path per slug. Two slugs in the catalog are not unique
 * (`disneyland-park`, `universal-islands-of-adventure`); images of those carry
 * an explicit `parkPath` and never rely on this.
 */
export const MEDIA_PARK_PATH_BY_SLUG: Record<string, string> = {
  "bobbejaanland": "europe/belgium/kasterlee/bobbejaanland",
  "walibi-belgium": "europe/belgium/wavre/walibi-belgium",
  "disneyland-park": "europe/france/paris/disneyland-park",
  "movie-park-germany": "europe/germany/bottrop/movie-park-germany",
  "phantasialand": "europe/germany/bruehl/phantasialand",
  "europa-park": "europe/germany/rust/europa-park",
  "walibi-holland": "europe/netherlands/biddinghuizen/walibi-holland",
  "efteling": "europe/netherlands/kaatsheuvel/efteling",
  "attractiepark-toverland": "europe/netherlands/sevenum/attractiepark-toverland",
  "disneys-animal-kingdom-theme-park": "north-america/united-states/orlando/disneys-animal-kingdom-theme-park",
  "disneys-hollywood-studios": "north-america/united-states/orlando/disneys-hollywood-studios",
  "epcot": "north-america/united-states/orlando/epcot",
  "magic-kingdom-park": "north-america/united-states/orlando/magic-kingdom-park",
  "universal-islands-of-adventure": "north-america/united-states/orlando/universal-islands-of-adventure"
};
